// to compile: xpidl -m typelib -I J:\teamswt\swt-builddir\gecko-sdk\idl\ -e External.xpt External.idl

#include "nsISupports.idl"
#include "nsIVariant.idl"

[scriptable, uuid(ded01d20-ba6f-11dd-ad8b-0800200c9a66)]

interface External : nsISupports {
    nsIVariant callJava (in unsigned long index, in nsIVariant args);
};
