// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$69 {

    static final FunctionDescriptor glMultiTexCoord3sv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glMultiTexCoord3sv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3sv",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$69.glMultiTexCoord3sv$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord4d$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle glMultiTexCoord4d$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord4d",
        "(IDDDD)V",
        constants$69.glMultiTexCoord4d$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord4dv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glMultiTexCoord4dv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord4dv",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$69.glMultiTexCoord4dv$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord4f$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle glMultiTexCoord4f$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord4f",
        "(IFFFF)V",
        constants$69.glMultiTexCoord4f$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord4fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glMultiTexCoord4fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord4fv",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$69.glMultiTexCoord4fv$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord4i$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glMultiTexCoord4i$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord4i",
        "(IIIII)V",
        constants$69.glMultiTexCoord4i$FUNC, false
    );
}


