// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$102 {

    static final FunctionDescriptor PFNGLWINDOWPOS2FVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLWINDOWPOS2FVPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$102.PFNGLWINDOWPOS2FVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS2IPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLWINDOWPOS2IPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$102.PFNGLWINDOWPOS2IPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS2IVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLWINDOWPOS2IVPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$102.PFNGLWINDOWPOS2IVPROC$FUNC, false
    );
}


