// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$876 {

    static final FunctionDescriptor PFNGLPIXELTEXGENPARAMETERISGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLPIXELTEXGENPARAMETERISGISPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$876.PFNGLPIXELTEXGENPARAMETERISGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPIXELTEXGENPARAMETERIVSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPIXELTEXGENPARAMETERIVSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$876.PFNGLPIXELTEXGENPARAMETERIVSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPIXELTEXGENPARAMETERFSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLPIXELTEXGENPARAMETERFSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(IF)V",
        constants$876.PFNGLPIXELTEXGENPARAMETERFSGISPROC$FUNC, false
    );
}


