// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$137 {

    static final FunctionDescriptor PFNGLVERTEXATTRIB3FVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIB3FVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$137.PFNGLVERTEXATTRIB3FVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB3SPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_SHORT,
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle PFNGLVERTEXATTRIB3SPROC$MH = RuntimeHelper.downcallHandle(
        "(ISSS)V",
        constants$137.PFNGLVERTEXATTRIB3SPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB3SVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIB3SVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$137.PFNGLVERTEXATTRIB3SVPROC$FUNC, false
    );
}


