// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$779 {

    static final FunctionDescriptor PFNGLPROGRAMBUFFERPARAMETERSFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMBUFFERPARAMETERSFVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$779.PFNGLPROGRAMBUFFERPARAMETERSFVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMBUFFERPARAMETERSIIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMBUFFERPARAMETERSIIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$779.PFNGLPROGRAMBUFFERPARAMETERSIIVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMBUFFERPARAMETERSIUIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMBUFFERPARAMETERSIUIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$779.PFNGLPROGRAMBUFFERPARAMETERSIUIVNVPROC$FUNC, false
    );
}


