// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$91 {

    static final FunctionDescriptor PFNGLMULTITEXCOORD4SVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMULTITEXCOORD4SVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$91.PFNGLMULTITEXCOORD4SVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBLENDFUNCSEPARATEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLBLENDFUNCSEPARATEPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$91.PFNGLBLENDFUNCSEPARATEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTIDRAWARRAYSPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle PFNGLMULTIDRAWARRAYSPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$91.PFNGLMULTIDRAWARRAYSPROC$FUNC, false
    );
}


