// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$883 {

    static final FunctionDescriptor PFNGLFLUSHRASTERSGIXPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLFLUSHRASTERSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$883.PFNGLFLUSHRASTERSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFRAGMENTCOLORMATERIALSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLFRAGMENTCOLORMATERIALSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$883.PFNGLFRAGMENTCOLORMATERIALSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFRAGMENTLIGHTFSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLFRAGMENTLIGHTFSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(IIF)V",
        constants$883.PFNGLFRAGMENTLIGHTFSGIXPROC$FUNC, false
    );
}


