// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$925 {

    static final FunctionDescriptor gluNewQuadric$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle gluNewQuadric$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNewQuadric",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$925.gluNewQuadric$FUNC, false
    );
    static final FunctionDescriptor gluNewTess$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle gluNewTess$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNewTess",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$925.gluNewTess$FUNC, false
    );
    static final FunctionDescriptor gluNextContour$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle gluNextContour$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNextContour",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$925.gluNextContour$FUNC, false
    );
    static final FunctionDescriptor gluNurbsCallback$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle gluNurbsCallback$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNurbsCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$925.gluNurbsCallback$FUNC, false
    );
    static final FunctionDescriptor gluNurbsCallbackData$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gluNurbsCallbackData$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNurbsCallbackData",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$925.gluNurbsCallbackData$FUNC, false
    );
    static final FunctionDescriptor gluNurbsCallbackDataEXT$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gluNurbsCallbackDataEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNurbsCallbackDataEXT",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$925.gluNurbsCallbackDataEXT$FUNC, false
    );
}


