// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$15 {

    static final FunctionDescriptor glVertex2iv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glVertex2iv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertex2iv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$15.glVertex2iv$FUNC, false
    );
    static final FunctionDescriptor glVertex2sv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glVertex2sv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertex2sv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$15.glVertex2sv$FUNC, false
    );
    static final FunctionDescriptor glVertex3dv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glVertex3dv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertex3dv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$15.glVertex3dv$FUNC, false
    );
    static final FunctionDescriptor glVertex3fv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glVertex3fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertex3fv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$15.glVertex3fv$FUNC, false
    );
    static final FunctionDescriptor glVertex3iv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glVertex3iv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertex3iv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$15.glVertex3iv$FUNC, false
    );
    static final FunctionDescriptor glVertex3sv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glVertex3sv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertex3sv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$15.glVertex3sv$FUNC, false
    );
}


