// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$542 {

    static final FunctionDescriptor PFNGLCLIENTATTRIBDEFAULTEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLCLIENTATTRIBDEFAULTEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$542.PFNGLCLIENTATTRIBDEFAULTEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPUSHCLIENTATTRIBDEFAULTEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLPUSHCLIENTATTRIBDEFAULTEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$542.PFNGLPUSHCLIENTATTRIBDEFAULTEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREPARAMETERFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERFEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIF)V",
        constants$542.PFNGLTEXTUREPARAMETERFEXTPROC$FUNC, false
    );
}


