// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$62 {

    static final FunctionDescriptor glConvolutionParameterfv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glConvolutionParameterfv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glConvolutionParameterfv",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$62.glConvolutionParameterfv$FUNC, false
    );
    static final FunctionDescriptor glConvolutionParameteri$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glConvolutionParameteri$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glConvolutionParameteri",
        "(III)V",
        constants$62.glConvolutionParameteri$FUNC, false
    );
    static final FunctionDescriptor glConvolutionParameteriv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glConvolutionParameteriv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glConvolutionParameteriv",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$62.glConvolutionParameteriv$FUNC, false
    );
    static final FunctionDescriptor glCopyConvolutionFilter1D$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glCopyConvolutionFilter1D$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glCopyConvolutionFilter1D",
        "(IIIII)V",
        constants$62.glCopyConvolutionFilter1D$FUNC, false
    );
    static final FunctionDescriptor glCopyConvolutionFilter2D$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glCopyConvolutionFilter2D$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glCopyConvolutionFilter2D",
        "(IIIIII)V",
        constants$62.glCopyConvolutionFilter2D$FUNC, false
    );
    static final FunctionDescriptor glGetConvolutionFilter$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetConvolutionFilter$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetConvolutionFilter",
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$62.glGetConvolutionFilter$FUNC, false
    );
}


