// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$615 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORMMATRIX2X3DVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMMATRIX2X3DVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$615.PFNGLPROGRAMUNIFORMMATRIX2X3DVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORMMATRIX2X4DVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMMATRIX2X4DVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$615.PFNGLPROGRAMUNIFORMMATRIX2X4DVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORMMATRIX3X2DVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMMATRIX3X2DVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$615.PFNGLPROGRAMUNIFORMMATRIX3X2DVEXTPROC$FUNC, false
    );
}


