// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$904 {

    static final FunctionDescriptor PFNGLREPLACEMENTCODEUBSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_CHAR
    );
    static final MethodHandle PFNGLREPLACEMENTCODEUBSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(B)V",
        constants$904.PFNGLREPLACEMENTCODEUBSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLREPLACEMENTCODEUIVSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLREPLACEMENTCODEUIVSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$904.PFNGLREPLACEMENTCODEUIVSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLREPLACEMENTCODEUSVSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLREPLACEMENTCODEUSVSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$904.PFNGLREPLACEMENTCODEUSVSUNPROC$FUNC, false
    );
}


