// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$18 {

    static final FunctionDescriptor glNormal3iv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glNormal3iv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glNormal3iv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$18.glNormal3iv$FUNC, false
    );
    static final FunctionDescriptor glNormal3sv$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glNormal3sv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glNormal3sv",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$18.glNormal3sv$FUNC, false
    );
    static final FunctionDescriptor glIndexd$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE
    );
    static final MethodHandle glIndexd$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glIndexd",
        "(D)V",
        constants$18.glIndexd$FUNC, false
    );
    static final FunctionDescriptor glIndexf$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT
    );
    static final MethodHandle glIndexf$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glIndexf",
        "(F)V",
        constants$18.glIndexf$FUNC, false
    );
    static final FunctionDescriptor glIndexi$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle glIndexi$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glIndexi",
        "(I)V",
        constants$18.glIndexi$FUNC, false
    );
    static final FunctionDescriptor glIndexs$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT
    );
    static final MethodHandle glIndexs$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glIndexs",
        "(S)V",
        constants$18.glIndexs$FUNC, false
    );
}


