// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$342 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORM3UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM3UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJJJ)V",
        constants$342.PFNGLPROGRAMUNIFORM3UI64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM4UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM4UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJJJJ)V",
        constants$342.PFNGLPROGRAMUNIFORM4UI64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM1UI64VARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM1UI64VARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$342.PFNGLPROGRAMUNIFORM1UI64VARBPROC$FUNC, false
    );
}


