// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$317 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$317.PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISTEXTUREHANDLERESIDENTARBPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_LONG
    );
    static final MethodHandle PFNGLISTEXTUREHANDLERESIDENTARBPROC$MH = RuntimeHelper.downcallHandle(
        "(J)B",
        constants$317.PFNGLISTEXTUREHANDLERESIDENTARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISIMAGEHANDLERESIDENTARBPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_LONG
    );
    static final MethodHandle PFNGLISIMAGEHANDLERESIDENTARBPROC$MH = RuntimeHelper.downcallHandle(
        "(J)B",
        constants$317.PFNGLISIMAGEHANDLERESIDENTARBPROC$FUNC, false
    );
}


