// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$451 {

    static final FunctionDescriptor PFNGLORTHOFOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLORTHOFOESPROC$MH = RuntimeHelper.downcallHandle(
        "(FFFFFF)V",
        constants$451.PFNGLORTHOFOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTBUFFERMASK3DFXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLTBUFFERMASK3DFXPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$451.PFNGLTBUFFERMASK3DFXPROC$FUNC, false
    );
    static final FunctionDescriptor GLDEBUGPROCAMD$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle GLDEBUGPROCAMD$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$451.GLDEBUGPROCAMD$FUNC, false
    );
}


