// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$419 {

    static final FunctionDescriptor PFNGLLIGHTMODELXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLLIGHTMODELXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$419.PFNGLLIGHTMODELXOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLLIGHTMODELXVOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLLIGHTMODELXVOESPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$419.PFNGLLIGHTMODELXVOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLLIGHTXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLLIGHTXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$419.PFNGLLIGHTXOESPROC$FUNC, false
    );
}


