// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$985 {

    static final MemorySegment PRIuFAST8$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST16$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST32$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIx8$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIx16$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
}


