// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$832 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBL4I64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIBL4I64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$832.PFNGLVERTEXATTRIBL4I64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL1UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL1UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJ)V",
        constants$832.PFNGLVERTEXATTRIBL1UI64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL2UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL2UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$832.PFNGLVERTEXATTRIBL2UI64NVPROC$FUNC, false
    );
}


