// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$638 {

    static final FunctionDescriptor PFNGLGETMINMAXPARAMETERFVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETMINMAXPARAMETERFVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$638.PFNGLGETMINMAXPARAMETERFVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETMINMAXPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETMINMAXPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$638.PFNGLGETMINMAXPARAMETERIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLHISTOGRAMEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_CHAR
    );
    static final MethodHandle PFNGLHISTOGRAMEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIB)V",
        constants$638.PFNGLHISTOGRAMEXTPROC$FUNC, false
    );
}


