// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$68 {

    static final FunctionDescriptor glMultiTexCoord3dv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glMultiTexCoord3dv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3dv",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$68.glMultiTexCoord3dv$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord3f$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle glMultiTexCoord3f$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3f",
        "(IFFF)V",
        constants$68.glMultiTexCoord3f$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord3fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glMultiTexCoord3fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3fv",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$68.glMultiTexCoord3fv$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord3i$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glMultiTexCoord3i$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3i",
        "(IIII)V",
        constants$68.glMultiTexCoord3i$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord3iv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glMultiTexCoord3iv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3iv",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$68.glMultiTexCoord3iv$FUNC, false
    );
    static final FunctionDescriptor glMultiTexCoord3s$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_SHORT,
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle glMultiTexCoord3s$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiTexCoord3s",
        "(ISSS)V",
        constants$68.glMultiTexCoord3s$FUNC, false
    );
}


