// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$26 {

    static final FunctionDescriptor glTexCoord2d$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle glTexCoord2d$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glTexCoord2d",
        "(DD)V",
        constants$26.glTexCoord2d$FUNC, false
    );
    static final FunctionDescriptor glTexCoord2f$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle glTexCoord2f$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glTexCoord2f",
        "(FF)V",
        constants$26.glTexCoord2f$FUNC, false
    );
    static final FunctionDescriptor glTexCoord2i$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle glTexCoord2i$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glTexCoord2i",
        "(II)V",
        constants$26.glTexCoord2i$FUNC, false
    );
    static final FunctionDescriptor glTexCoord2s$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle glTexCoord2s$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glTexCoord2s",
        "(SS)V",
        constants$26.glTexCoord2s$FUNC, false
    );
    static final FunctionDescriptor glTexCoord3d$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle glTexCoord3d$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glTexCoord3d",
        "(DDD)V",
        constants$26.glTexCoord3d$FUNC, false
    );
    static final FunctionDescriptor glTexCoord3f$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle glTexCoord3f$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glTexCoord3f",
        "(FFF)V",
        constants$26.glTexCoord3f$FUNC, false
    );
}


