// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$621 {

    static final FunctionDescriptor PFNGLVERTEXARRAYVERTEXATTRIBLOFFSETEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXARRAYVERTEXATTRIBLOFFSETEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIJ)V",
        constants$621.PFNGLVERTEXARRAYVERTEXATTRIBLOFFSETEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREPAGECOMMITMENTEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_CHAR
    );
    static final MethodHandle PFNGLTEXTUREPAGECOMMITMENTEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIIB)V",
        constants$621.PFNGLTEXTUREPAGECOMMITMENTEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXARRAYVERTEXATTRIBDIVISOREXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLVERTEXARRAYVERTEXATTRIBDIVISOREXTPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$621.PFNGLVERTEXARRAYVERTEXATTRIBDIVISOREXTPROC$FUNC, false
    );
}


