// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$248 {

    static final FunctionDescriptor PFNGLSCISSORINDEXEDVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLSCISSORINDEXEDVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$248.PFNGLSCISSORINDEXEDVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEPTHRANGEARRAYVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDEPTHRANGEARRAYVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$248.PFNGLDEPTHRANGEARRAYVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEPTHRANGEINDEXEDPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLDEPTHRANGEINDEXEDPROC$MH = RuntimeHelper.downcallHandle(
        "(IDD)V",
        constants$248.PFNGLDEPTHRANGEINDEXEDPROC$FUNC, false
    );
}


