// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$252 {

    static final FunctionDescriptor PFNGLTEXSTORAGE1DPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXSTORAGE1DPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$252.PFNGLTEXSTORAGE1DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXSTORAGE2DPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXSTORAGE2DPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$252.PFNGLTEXSTORAGE2DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXSTORAGE3DPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXSTORAGE3DPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIII)V",
        constants$252.PFNGLTEXSTORAGE3DPROC$FUNC, false
    );
}


