// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$641 {

    static final FunctionDescriptor PFNGLTEXTURELIGHTEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLTEXTURELIGHTEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$641.PFNGLTEXTURELIGHTEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREMATERIALEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXTUREMATERIALEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$641.PFNGLTEXTUREMATERIALEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETUNSIGNEDBYTEVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETUNSIGNEDBYTEVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$641.PFNGLGETUNSIGNEDBYTEVEXTPROC$FUNC, false
    );
}


