// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$296 {

    static final FunctionDescriptor PFNGLGETTEXTUREPARAMETERIIVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXTUREPARAMETERIIVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$296.PFNGLGETTEXTUREPARAMETERIIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETTEXTUREPARAMETERIUIVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXTUREPARAMETERIUIVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$296.PFNGLGETTEXTUREPARAMETERIUIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETTEXTUREPARAMETERIVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXTUREPARAMETERIVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$296.PFNGLGETTEXTUREPARAMETERIVPROC$FUNC, false
    );
}


