// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$894 {

    static final FunctionDescriptor PFNGLPIXELTEXGENSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLPIXELTEXGENSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$894.PFNGLPIXELTEXGENSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEFORMATIONMAP3DSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_INT,
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_INT,
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDEFORMATIONMAP3DSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(IDDIIDDIIDDIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$894.PFNGLDEFORMATIONMAP3DSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEFORMATIONMAP3FSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_INT,
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_INT,
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDEFORMATIONMAP3FSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(IFFIIFFIIFFIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$894.PFNGLDEFORMATIONMAP3FSGIXPROC$FUNC, false
    );
}


