// Generated by jextract

package org.eclipse.swt.opengl.panama;

import jdk.incubator.foreign.*;
public class glut_h extends glut_h_6 {

    static {
        System.loadLibrary("glut");
        System.loadLibrary("GLU");
        System.loadLibrary("GL");
        System.loadLibrary("GLX");
    }

    static final SymbolLookup LIBRARIES = RuntimeHelper.lookup();
    public static int FREEGLUT() {
        return (int)1L;
    }
    public static int GLUT_API_VERSION() {
        return (int)4L;
    }
    public static int GLUT_XLIB_IMPLEMENTATION() {
        return (int)13L;
    }
    public static int FREEGLUT_VERSION_2_0() {
        return (int)1L;
    }
    public static int GL_VERSION_1_1() {
        return (int)1L;
    }
    public static int GL_VERSION_1_2() {
        return (int)1L;
    }
    public static int GL_VERSION_1_3() {
        return (int)1L;
    }
    public static int GL_ARB_imaging() {
        return (int)1L;
    }
    public static int GL_FALSE() {
        return (int)0L;
    }
    public static int GL_TRUE() {
        return (int)1L;
    }
    public static int GL_BYTE() {
        return (int)5120L;
    }
    public static int GL_UNSIGNED_BYTE() {
        return (int)5121L;
    }
    public static int GL_SHORT() {
        return (int)5122L;
    }
    public static int GL_UNSIGNED_SHORT() {
        return (int)5123L;
    }
    public static int GL_INT() {
        return (int)5124L;
    }
    public static int GL_UNSIGNED_INT() {
        return (int)5125L;
    }
    public static int GL_FLOAT() {
        return (int)5126L;
    }
    public static int GL_2_BYTES() {
        return (int)5127L;
    }
    public static int GL_3_BYTES() {
        return (int)5128L;
    }
    public static int GL_4_BYTES() {
        return (int)5129L;
    }
    public static int GL_DOUBLE() {
        return (int)5130L;
    }
    public static int GL_POINTS() {
        return (int)0L;
    }
    public static int GL_LINES() {
        return (int)1L;
    }
    public static int GL_LINE_LOOP() {
        return (int)2L;
    }
    public static int GL_LINE_STRIP() {
        return (int)3L;
    }
    public static int GL_TRIANGLES() {
        return (int)4L;
    }
    public static int GL_TRIANGLE_STRIP() {
        return (int)5L;
    }
    public static int GL_TRIANGLE_FAN() {
        return (int)6L;
    }
    public static int GL_QUADS() {
        return (int)7L;
    }
    public static int GL_QUAD_STRIP() {
        return (int)8L;
    }
    public static int GL_POLYGON() {
        return (int)9L;
    }
    public static int GL_VERTEX_ARRAY() {
        return (int)32884L;
    }
    public static int GL_NORMAL_ARRAY() {
        return (int)32885L;
    }
    public static int GL_COLOR_ARRAY() {
        return (int)32886L;
    }
    public static int GL_INDEX_ARRAY() {
        return (int)32887L;
    }
    public static int GL_TEXTURE_COORD_ARRAY() {
        return (int)32888L;
    }
    public static int GL_EDGE_FLAG_ARRAY() {
        return (int)32889L;
    }
    public static int GL_VERTEX_ARRAY_SIZE() {
        return (int)32890L;
    }
    public static int GL_VERTEX_ARRAY_TYPE() {
        return (int)32891L;
    }
    public static int GL_VERTEX_ARRAY_STRIDE() {
        return (int)32892L;
    }
    public static int GL_NORMAL_ARRAY_TYPE() {
        return (int)32894L;
    }
    public static int GL_NORMAL_ARRAY_STRIDE() {
        return (int)32895L;
    }
    public static int GL_COLOR_ARRAY_SIZE() {
        return (int)32897L;
    }
    public static int GL_COLOR_ARRAY_TYPE() {
        return (int)32898L;
    }
    public static int GL_COLOR_ARRAY_STRIDE() {
        return (int)32899L;
    }
    public static int GL_INDEX_ARRAY_TYPE() {
        return (int)32901L;
    }
    public static int GL_INDEX_ARRAY_STRIDE() {
        return (int)32902L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_SIZE() {
        return (int)32904L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_TYPE() {
        return (int)32905L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_STRIDE() {
        return (int)32906L;
    }
    public static int GL_EDGE_FLAG_ARRAY_STRIDE() {
        return (int)32908L;
    }
    public static int GL_VERTEX_ARRAY_POINTER() {
        return (int)32910L;
    }
    public static int GL_NORMAL_ARRAY_POINTER() {
        return (int)32911L;
    }
    public static int GL_COLOR_ARRAY_POINTER() {
        return (int)32912L;
    }
    public static int GL_INDEX_ARRAY_POINTER() {
        return (int)32913L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_POINTER() {
        return (int)32914L;
    }
    public static int GL_EDGE_FLAG_ARRAY_POINTER() {
        return (int)32915L;
    }
    public static int GL_V2F() {
        return (int)10784L;
    }
    public static int GL_V3F() {
        return (int)10785L;
    }
    public static int GL_C4UB_V2F() {
        return (int)10786L;
    }
    public static int GL_C4UB_V3F() {
        return (int)10787L;
    }
    public static int GL_C3F_V3F() {
        return (int)10788L;
    }
    public static int GL_N3F_V3F() {
        return (int)10789L;
    }
    public static int GL_C4F_N3F_V3F() {
        return (int)10790L;
    }
    public static int GL_T2F_V3F() {
        return (int)10791L;
    }
    public static int GL_T4F_V4F() {
        return (int)10792L;
    }
    public static int GL_T2F_C4UB_V3F() {
        return (int)10793L;
    }
    public static int GL_T2F_C3F_V3F() {
        return (int)10794L;
    }
    public static int GL_T2F_N3F_V3F() {
        return (int)10795L;
    }
    public static int GL_T2F_C4F_N3F_V3F() {
        return (int)10796L;
    }
    public static int GL_T4F_C4F_N3F_V4F() {
        return (int)10797L;
    }
    public static int GL_MATRIX_MODE() {
        return (int)2976L;
    }
    public static int GL_MODELVIEW() {
        return (int)5888L;
    }
    public static int GL_PROJECTION() {
        return (int)5889L;
    }
    public static int GL_TEXTURE() {
        return (int)5890L;
    }
    public static int GL_POINT_SMOOTH() {
        return (int)2832L;
    }
    public static int GL_POINT_SIZE() {
        return (int)2833L;
    }
    public static int GL_POINT_SIZE_GRANULARITY() {
        return (int)2835L;
    }
    public static int GL_POINT_SIZE_RANGE() {
        return (int)2834L;
    }
    public static int GL_LINE_SMOOTH() {
        return (int)2848L;
    }
    public static int GL_LINE_STIPPLE() {
        return (int)2852L;
    }
    public static int GL_LINE_STIPPLE_PATTERN() {
        return (int)2853L;
    }
    public static int GL_LINE_STIPPLE_REPEAT() {
        return (int)2854L;
    }
    public static int GL_LINE_WIDTH() {
        return (int)2849L;
    }
    public static int GL_LINE_WIDTH_GRANULARITY() {
        return (int)2851L;
    }
    public static int GL_LINE_WIDTH_RANGE() {
        return (int)2850L;
    }
    public static int GL_POINT() {
        return (int)6912L;
    }
    public static int GL_LINE() {
        return (int)6913L;
    }
    public static int GL_FILL() {
        return (int)6914L;
    }
    public static int GL_CW() {
        return (int)2304L;
    }
    public static int GL_CCW() {
        return (int)2305L;
    }
    public static int GL_FRONT() {
        return (int)1028L;
    }
    public static int GL_BACK() {
        return (int)1029L;
    }
    public static int GL_POLYGON_MODE() {
        return (int)2880L;
    }
    public static int GL_POLYGON_SMOOTH() {
        return (int)2881L;
    }
    public static int GL_POLYGON_STIPPLE() {
        return (int)2882L;
    }
    public static int GL_EDGE_FLAG() {
        return (int)2883L;
    }
    public static int GL_CULL_FACE() {
        return (int)2884L;
    }
    public static int GL_CULL_FACE_MODE() {
        return (int)2885L;
    }
    public static int GL_FRONT_FACE() {
        return (int)2886L;
    }
    public static int GL_POLYGON_OFFSET_FACTOR() {
        return (int)32824L;
    }
    public static int GL_POLYGON_OFFSET_UNITS() {
        return (int)10752L;
    }
    public static int GL_POLYGON_OFFSET_POINT() {
        return (int)10753L;
    }
    public static int GL_POLYGON_OFFSET_LINE() {
        return (int)10754L;
    }
    public static int GL_POLYGON_OFFSET_FILL() {
        return (int)32823L;
    }
    public static int GL_COMPILE() {
        return (int)4864L;
    }
    public static int GL_COMPILE_AND_EXECUTE() {
        return (int)4865L;
    }
    public static int GL_LIST_BASE() {
        return (int)2866L;
    }
    public static int GL_LIST_INDEX() {
        return (int)2867L;
    }
    public static int GL_LIST_MODE() {
        return (int)2864L;
    }
    public static int GL_NEVER() {
        return (int)512L;
    }
    public static int GL_LESS() {
        return (int)513L;
    }
    public static int GL_EQUAL() {
        return (int)514L;
    }
    public static int GL_LEQUAL() {
        return (int)515L;
    }
    public static int GL_GREATER() {
        return (int)516L;
    }
    public static int GL_NOTEQUAL() {
        return (int)517L;
    }
    public static int GL_GEQUAL() {
        return (int)518L;
    }
    public static int GL_ALWAYS() {
        return (int)519L;
    }
    public static int GL_DEPTH_TEST() {
        return (int)2929L;
    }
    public static int GL_DEPTH_BITS() {
        return (int)3414L;
    }
    public static int GL_DEPTH_CLEAR_VALUE() {
        return (int)2931L;
    }
    public static int GL_DEPTH_FUNC() {
        return (int)2932L;
    }
    public static int GL_DEPTH_RANGE() {
        return (int)2928L;
    }
    public static int GL_DEPTH_WRITEMASK() {
        return (int)2930L;
    }
    public static int GL_DEPTH_COMPONENT() {
        return (int)6402L;
    }
    public static int GL_LIGHTING() {
        return (int)2896L;
    }
    public static int GL_LIGHT0() {
        return (int)16384L;
    }
    public static int GL_LIGHT1() {
        return (int)16385L;
    }
    public static int GL_LIGHT2() {
        return (int)16386L;
    }
    public static int GL_LIGHT3() {
        return (int)16387L;
    }
    public static int GL_LIGHT4() {
        return (int)16388L;
    }
    public static int GL_LIGHT5() {
        return (int)16389L;
    }
    public static int GL_LIGHT6() {
        return (int)16390L;
    }
    public static int GL_LIGHT7() {
        return (int)16391L;
    }
    public static int GL_SPOT_EXPONENT() {
        return (int)4613L;
    }
    public static int GL_SPOT_CUTOFF() {
        return (int)4614L;
    }
    public static int GL_CONSTANT_ATTENUATION() {
        return (int)4615L;
    }
    public static int GL_LINEAR_ATTENUATION() {
        return (int)4616L;
    }
    public static int GL_QUADRATIC_ATTENUATION() {
        return (int)4617L;
    }
    public static int GL_AMBIENT() {
        return (int)4608L;
    }
    public static int GL_DIFFUSE() {
        return (int)4609L;
    }
    public static int GL_SPECULAR() {
        return (int)4610L;
    }
    public static int GL_SHININESS() {
        return (int)5633L;
    }
    public static int GL_EMISSION() {
        return (int)5632L;
    }
    public static int GL_POSITION() {
        return (int)4611L;
    }
    public static int GL_SPOT_DIRECTION() {
        return (int)4612L;
    }
    public static int GL_AMBIENT_AND_DIFFUSE() {
        return (int)5634L;
    }
    public static int GL_COLOR_INDEXES() {
        return (int)5635L;
    }
    public static int GL_LIGHT_MODEL_TWO_SIDE() {
        return (int)2898L;
    }
    public static int GL_LIGHT_MODEL_LOCAL_VIEWER() {
        return (int)2897L;
    }
    public static int GL_LIGHT_MODEL_AMBIENT() {
        return (int)2899L;
    }
    public static int GL_FRONT_AND_BACK() {
        return (int)1032L;
    }
    public static int GL_SHADE_MODEL() {
        return (int)2900L;
    }
    public static int GL_FLAT() {
        return (int)7424L;
    }
    public static int GL_SMOOTH() {
        return (int)7425L;
    }
    public static int GL_COLOR_MATERIAL() {
        return (int)2903L;
    }
    public static int GL_COLOR_MATERIAL_FACE() {
        return (int)2901L;
    }
    public static int GL_COLOR_MATERIAL_PARAMETER() {
        return (int)2902L;
    }
    public static int GL_NORMALIZE() {
        return (int)2977L;
    }
    public static int GL_CLIP_PLANE0() {
        return (int)12288L;
    }
    public static int GL_CLIP_PLANE1() {
        return (int)12289L;
    }
    public static int GL_CLIP_PLANE2() {
        return (int)12290L;
    }
    public static int GL_CLIP_PLANE3() {
        return (int)12291L;
    }
    public static int GL_CLIP_PLANE4() {
        return (int)12292L;
    }
    public static int GL_CLIP_PLANE5() {
        return (int)12293L;
    }
    public static int GL_ACCUM_RED_BITS() {
        return (int)3416L;
    }
    public static int GL_ACCUM_GREEN_BITS() {
        return (int)3417L;
    }
    public static int GL_ACCUM_BLUE_BITS() {
        return (int)3418L;
    }
    public static int GL_ACCUM_ALPHA_BITS() {
        return (int)3419L;
    }
    public static int GL_ACCUM_CLEAR_VALUE() {
        return (int)2944L;
    }
    public static int GL_ACCUM() {
        return (int)256L;
    }
    public static int GL_ADD() {
        return (int)260L;
    }
    public static int GL_LOAD() {
        return (int)257L;
    }
    public static int GL_MULT() {
        return (int)259L;
    }
    public static int GL_RETURN() {
        return (int)258L;
    }
    public static int GL_ALPHA_TEST() {
        return (int)3008L;
    }
    public static int GL_ALPHA_TEST_REF() {
        return (int)3010L;
    }
    public static int GL_ALPHA_TEST_FUNC() {
        return (int)3009L;
    }
    public static int GL_BLEND() {
        return (int)3042L;
    }
    public static int GL_BLEND_SRC() {
        return (int)3041L;
    }
    public static int GL_BLEND_DST() {
        return (int)3040L;
    }
    public static int GL_ZERO() {
        return (int)0L;
    }
    public static int GL_ONE() {
        return (int)1L;
    }
    public static int GL_SRC_COLOR() {
        return (int)768L;
    }
    public static int GL_ONE_MINUS_SRC_COLOR() {
        return (int)769L;
    }
    public static int GL_SRC_ALPHA() {
        return (int)770L;
    }
    public static int GL_ONE_MINUS_SRC_ALPHA() {
        return (int)771L;
    }
    public static int GL_DST_ALPHA() {
        return (int)772L;
    }
    public static int GL_ONE_MINUS_DST_ALPHA() {
        return (int)773L;
    }
    public static int GL_DST_COLOR() {
        return (int)774L;
    }
    public static int GL_ONE_MINUS_DST_COLOR() {
        return (int)775L;
    }
    public static int GL_SRC_ALPHA_SATURATE() {
        return (int)776L;
    }
    public static int GL_FEEDBACK() {
        return (int)7169L;
    }
    public static int GL_RENDER() {
        return (int)7168L;
    }
    public static int GL_SELECT() {
        return (int)7170L;
    }
    public static int GL_2D() {
        return (int)1536L;
    }
    public static int GL_3D() {
        return (int)1537L;
    }
    public static int GL_3D_COLOR() {
        return (int)1538L;
    }
    public static int GL_3D_COLOR_TEXTURE() {
        return (int)1539L;
    }
    public static int GL_4D_COLOR_TEXTURE() {
        return (int)1540L;
    }
    public static int GL_POINT_TOKEN() {
        return (int)1793L;
    }
    public static int GL_LINE_TOKEN() {
        return (int)1794L;
    }
    public static int GL_LINE_RESET_TOKEN() {
        return (int)1799L;
    }
    public static int GL_POLYGON_TOKEN() {
        return (int)1795L;
    }
    public static int GL_BITMAP_TOKEN() {
        return (int)1796L;
    }
    public static int GL_DRAW_PIXEL_TOKEN() {
        return (int)1797L;
    }
    public static int GL_COPY_PIXEL_TOKEN() {
        return (int)1798L;
    }
    public static int GL_PASS_THROUGH_TOKEN() {
        return (int)1792L;
    }
    public static int GL_FEEDBACK_BUFFER_POINTER() {
        return (int)3568L;
    }
    public static int GL_FEEDBACK_BUFFER_SIZE() {
        return (int)3569L;
    }
    public static int GL_FEEDBACK_BUFFER_TYPE() {
        return (int)3570L;
    }
    public static int GL_SELECTION_BUFFER_POINTER() {
        return (int)3571L;
    }
    public static int GL_SELECTION_BUFFER_SIZE() {
        return (int)3572L;
    }
    public static int GL_FOG() {
        return (int)2912L;
    }
    public static int GL_FOG_MODE() {
        return (int)2917L;
    }
    public static int GL_FOG_DENSITY() {
        return (int)2914L;
    }
    public static int GL_FOG_COLOR() {
        return (int)2918L;
    }
    public static int GL_FOG_INDEX() {
        return (int)2913L;
    }
    public static int GL_FOG_START() {
        return (int)2915L;
    }
    public static int GL_FOG_END() {
        return (int)2916L;
    }
    public static int GL_LINEAR() {
        return (int)9729L;
    }
    public static int GL_EXP() {
        return (int)2048L;
    }
    public static int GL_EXP2() {
        return (int)2049L;
    }
    public static int GL_LOGIC_OP() {
        return (int)3057L;
    }
    public static int GL_INDEX_LOGIC_OP() {
        return (int)3057L;
    }
    public static int GL_COLOR_LOGIC_OP() {
        return (int)3058L;
    }
    public static int GL_LOGIC_OP_MODE() {
        return (int)3056L;
    }
    public static int GL_CLEAR() {
        return (int)5376L;
    }
    public static int GL_SET() {
        return (int)5391L;
    }
    public static int GL_COPY() {
        return (int)5379L;
    }
    public static int GL_COPY_INVERTED() {
        return (int)5388L;
    }
    public static int GL_NOOP() {
        return (int)5381L;
    }
    public static int GL_INVERT() {
        return (int)5386L;
    }
    public static int GL_AND() {
        return (int)5377L;
    }
    public static int GL_NAND() {
        return (int)5390L;
    }
    public static int GL_OR() {
        return (int)5383L;
    }
    public static int GL_NOR() {
        return (int)5384L;
    }
    public static int GL_XOR() {
        return (int)5382L;
    }
    public static int GL_EQUIV() {
        return (int)5385L;
    }
    public static int GL_AND_REVERSE() {
        return (int)5378L;
    }
    public static int GL_AND_INVERTED() {
        return (int)5380L;
    }
    public static int GL_OR_REVERSE() {
        return (int)5387L;
    }
    public static int GL_OR_INVERTED() {
        return (int)5389L;
    }
    public static int GL_STENCIL_BITS() {
        return (int)3415L;
    }
    public static int GL_STENCIL_TEST() {
        return (int)2960L;
    }
    public static int GL_STENCIL_CLEAR_VALUE() {
        return (int)2961L;
    }
    public static int GL_STENCIL_FUNC() {
        return (int)2962L;
    }
    public static int GL_STENCIL_VALUE_MASK() {
        return (int)2963L;
    }
    public static int GL_STENCIL_FAIL() {
        return (int)2964L;
    }
    public static int GL_STENCIL_PASS_DEPTH_FAIL() {
        return (int)2965L;
    }
    public static int GL_STENCIL_PASS_DEPTH_PASS() {
        return (int)2966L;
    }
    public static int GL_STENCIL_REF() {
        return (int)2967L;
    }
    public static int GL_STENCIL_WRITEMASK() {
        return (int)2968L;
    }
    public static int GL_STENCIL_INDEX() {
        return (int)6401L;
    }
    public static int GL_KEEP() {
        return (int)7680L;
    }
    public static int GL_REPLACE() {
        return (int)7681L;
    }
    public static int GL_INCR() {
        return (int)7682L;
    }
    public static int GL_DECR() {
        return (int)7683L;
    }
    public static int GL_NONE() {
        return (int)0L;
    }
    public static int GL_LEFT() {
        return (int)1030L;
    }
    public static int GL_RIGHT() {
        return (int)1031L;
    }
    public static int GL_FRONT_LEFT() {
        return (int)1024L;
    }
    public static int GL_FRONT_RIGHT() {
        return (int)1025L;
    }
    public static int GL_BACK_LEFT() {
        return (int)1026L;
    }
    public static int GL_BACK_RIGHT() {
        return (int)1027L;
    }
    public static int GL_AUX0() {
        return (int)1033L;
    }
    public static int GL_AUX1() {
        return (int)1034L;
    }
    public static int GL_AUX2() {
        return (int)1035L;
    }
    public static int GL_AUX3() {
        return (int)1036L;
    }
    public static int GL_COLOR_INDEX() {
        return (int)6400L;
    }
    public static int GL_RED() {
        return (int)6403L;
    }
    public static int GL_GREEN() {
        return (int)6404L;
    }
    public static int GL_BLUE() {
        return (int)6405L;
    }
    public static int GL_ALPHA() {
        return (int)6406L;
    }
    public static int GL_LUMINANCE() {
        return (int)6409L;
    }
    public static int GL_LUMINANCE_ALPHA() {
        return (int)6410L;
    }
    public static int GL_ALPHA_BITS() {
        return (int)3413L;
    }
    public static int GL_RED_BITS() {
        return (int)3410L;
    }
    public static int GL_GREEN_BITS() {
        return (int)3411L;
    }
    public static int GL_BLUE_BITS() {
        return (int)3412L;
    }
    public static int GL_INDEX_BITS() {
        return (int)3409L;
    }
    public static int GL_SUBPIXEL_BITS() {
        return (int)3408L;
    }
    public static int GL_AUX_BUFFERS() {
        return (int)3072L;
    }
    public static int GL_READ_BUFFER() {
        return (int)3074L;
    }
    public static int GL_DRAW_BUFFER() {
        return (int)3073L;
    }
    public static int GL_DOUBLEBUFFER() {
        return (int)3122L;
    }
    public static int GL_STEREO() {
        return (int)3123L;
    }
    public static int GL_BITMAP() {
        return (int)6656L;
    }
    public static int GL_COLOR() {
        return (int)6144L;
    }
    public static int GL_DEPTH() {
        return (int)6145L;
    }
    public static int GL_STENCIL() {
        return (int)6146L;
    }
    public static int GL_DITHER() {
        return (int)3024L;
    }
    public static int GL_RGB() {
        return (int)6407L;
    }
    public static int GL_RGBA() {
        return (int)6408L;
    }
    public static int GL_MAX_LIST_NESTING() {
        return (int)2865L;
    }
    public static int GL_MAX_EVAL_ORDER() {
        return (int)3376L;
    }
    public static int GL_MAX_LIGHTS() {
        return (int)3377L;
    }
    public static int GL_MAX_CLIP_PLANES() {
        return (int)3378L;
    }
    public static int GL_MAX_TEXTURE_SIZE() {
        return (int)3379L;
    }
    public static int GL_MAX_PIXEL_MAP_TABLE() {
        return (int)3380L;
    }
    public static int GL_MAX_ATTRIB_STACK_DEPTH() {
        return (int)3381L;
    }
    public static int GL_MAX_MODELVIEW_STACK_DEPTH() {
        return (int)3382L;
    }
    public static int GL_MAX_NAME_STACK_DEPTH() {
        return (int)3383L;
    }
    public static int GL_MAX_PROJECTION_STACK_DEPTH() {
        return (int)3384L;
    }
    public static int GL_MAX_TEXTURE_STACK_DEPTH() {
        return (int)3385L;
    }
    public static int GL_MAX_VIEWPORT_DIMS() {
        return (int)3386L;
    }
    public static int GL_MAX_CLIENT_ATTRIB_STACK_DEPTH() {
        return (int)3387L;
    }
    public static int GL_ATTRIB_STACK_DEPTH() {
        return (int)2992L;
    }
    public static int GL_CLIENT_ATTRIB_STACK_DEPTH() {
        return (int)2993L;
    }
    public static int GL_COLOR_CLEAR_VALUE() {
        return (int)3106L;
    }
    public static int GL_COLOR_WRITEMASK() {
        return (int)3107L;
    }
    public static int GL_CURRENT_INDEX() {
        return (int)2817L;
    }
    public static int GL_CURRENT_COLOR() {
        return (int)2816L;
    }
    public static int GL_CURRENT_NORMAL() {
        return (int)2818L;
    }
    public static int GL_CURRENT_RASTER_COLOR() {
        return (int)2820L;
    }
    public static int GL_CURRENT_RASTER_DISTANCE() {
        return (int)2825L;
    }
    public static int GL_CURRENT_RASTER_INDEX() {
        return (int)2821L;
    }
    public static int GL_CURRENT_RASTER_POSITION() {
        return (int)2823L;
    }
    public static int GL_CURRENT_RASTER_TEXTURE_COORDS() {
        return (int)2822L;
    }
    public static int GL_CURRENT_RASTER_POSITION_VALID() {
        return (int)2824L;
    }
    public static int GL_CURRENT_TEXTURE_COORDS() {
        return (int)2819L;
    }
    public static int GL_INDEX_CLEAR_VALUE() {
        return (int)3104L;
    }
    public static int GL_INDEX_MODE() {
        return (int)3120L;
    }
    public static int GL_INDEX_WRITEMASK() {
        return (int)3105L;
    }
    public static int GL_MODELVIEW_MATRIX() {
        return (int)2982L;
    }
    public static int GL_MODELVIEW_STACK_DEPTH() {
        return (int)2979L;
    }
    public static int GL_NAME_STACK_DEPTH() {
        return (int)3440L;
    }
    public static int GL_PROJECTION_MATRIX() {
        return (int)2983L;
    }
    public static int GL_PROJECTION_STACK_DEPTH() {
        return (int)2980L;
    }
    public static int GL_RENDER_MODE() {
        return (int)3136L;
    }
    public static int GL_RGBA_MODE() {
        return (int)3121L;
    }
    public static int GL_TEXTURE_MATRIX() {
        return (int)2984L;
    }
    public static int GL_TEXTURE_STACK_DEPTH() {
        return (int)2981L;
    }
    public static int GL_VIEWPORT() {
        return (int)2978L;
    }
    public static int GL_AUTO_NORMAL() {
        return (int)3456L;
    }
    public static int GL_MAP1_COLOR_4() {
        return (int)3472L;
    }
    public static int GL_MAP1_INDEX() {
        return (int)3473L;
    }
    public static int GL_MAP1_NORMAL() {
        return (int)3474L;
    }
    public static int GL_MAP1_TEXTURE_COORD_1() {
        return (int)3475L;
    }
    public static int GL_MAP1_TEXTURE_COORD_2() {
        return (int)3476L;
    }
    public static int GL_MAP1_TEXTURE_COORD_3() {
        return (int)3477L;
    }
    public static int GL_MAP1_TEXTURE_COORD_4() {
        return (int)3478L;
    }
    public static int GL_MAP1_VERTEX_3() {
        return (int)3479L;
    }
    public static int GL_MAP1_VERTEX_4() {
        return (int)3480L;
    }
    public static int GL_MAP2_COLOR_4() {
        return (int)3504L;
    }
    public static int GL_MAP2_INDEX() {
        return (int)3505L;
    }
    public static int GL_MAP2_NORMAL() {
        return (int)3506L;
    }
    public static int GL_MAP2_TEXTURE_COORD_1() {
        return (int)3507L;
    }
    public static int GL_MAP2_TEXTURE_COORD_2() {
        return (int)3508L;
    }
    public static int GL_MAP2_TEXTURE_COORD_3() {
        return (int)3509L;
    }
    public static int GL_MAP2_TEXTURE_COORD_4() {
        return (int)3510L;
    }
    public static int GL_MAP2_VERTEX_3() {
        return (int)3511L;
    }
    public static int GL_MAP2_VERTEX_4() {
        return (int)3512L;
    }
    public static int GL_MAP1_GRID_DOMAIN() {
        return (int)3536L;
    }
    public static int GL_MAP1_GRID_SEGMENTS() {
        return (int)3537L;
    }
    public static int GL_MAP2_GRID_DOMAIN() {
        return (int)3538L;
    }
    public static int GL_MAP2_GRID_SEGMENTS() {
        return (int)3539L;
    }
    public static int GL_COEFF() {
        return (int)2560L;
    }
    public static int GL_ORDER() {
        return (int)2561L;
    }
    public static int GL_DOMAIN() {
        return (int)2562L;
    }
    public static int GL_PERSPECTIVE_CORRECTION_HINT() {
        return (int)3152L;
    }
    public static int GL_POINT_SMOOTH_HINT() {
        return (int)3153L;
    }
    public static int GL_LINE_SMOOTH_HINT() {
        return (int)3154L;
    }
    public static int GL_POLYGON_SMOOTH_HINT() {
        return (int)3155L;
    }
    public static int GL_FOG_HINT() {
        return (int)3156L;
    }
    public static int GL_DONT_CARE() {
        return (int)4352L;
    }
    public static int GL_FASTEST() {
        return (int)4353L;
    }
    public static int GL_NICEST() {
        return (int)4354L;
    }
    public static int GL_SCISSOR_BOX() {
        return (int)3088L;
    }
    public static int GL_SCISSOR_TEST() {
        return (int)3089L;
    }
    public static int GL_MAP_COLOR() {
        return (int)3344L;
    }
    public static int GL_MAP_STENCIL() {
        return (int)3345L;
    }
    public static int GL_INDEX_SHIFT() {
        return (int)3346L;
    }
    public static int GL_INDEX_OFFSET() {
        return (int)3347L;
    }
    public static int GL_RED_SCALE() {
        return (int)3348L;
    }
    public static int GL_RED_BIAS() {
        return (int)3349L;
    }
    public static int GL_GREEN_SCALE() {
        return (int)3352L;
    }
    public static int GL_GREEN_BIAS() {
        return (int)3353L;
    }
    public static int GL_BLUE_SCALE() {
        return (int)3354L;
    }
    public static int GL_BLUE_BIAS() {
        return (int)3355L;
    }
    public static int GL_ALPHA_SCALE() {
        return (int)3356L;
    }
    public static int GL_ALPHA_BIAS() {
        return (int)3357L;
    }
    public static int GL_DEPTH_SCALE() {
        return (int)3358L;
    }
    public static int GL_DEPTH_BIAS() {
        return (int)3359L;
    }
    public static int GL_PIXEL_MAP_S_TO_S_SIZE() {
        return (int)3249L;
    }
    public static int GL_PIXEL_MAP_I_TO_I_SIZE() {
        return (int)3248L;
    }
    public static int GL_PIXEL_MAP_I_TO_R_SIZE() {
        return (int)3250L;
    }
    public static int GL_PIXEL_MAP_I_TO_G_SIZE() {
        return (int)3251L;
    }
    public static int GL_PIXEL_MAP_I_TO_B_SIZE() {
        return (int)3252L;
    }
    public static int GL_PIXEL_MAP_I_TO_A_SIZE() {
        return (int)3253L;
    }
    public static int GL_PIXEL_MAP_R_TO_R_SIZE() {
        return (int)3254L;
    }
    public static int GL_PIXEL_MAP_G_TO_G_SIZE() {
        return (int)3255L;
    }
    public static int GL_PIXEL_MAP_B_TO_B_SIZE() {
        return (int)3256L;
    }
    public static int GL_PIXEL_MAP_A_TO_A_SIZE() {
        return (int)3257L;
    }
    public static int GL_PIXEL_MAP_S_TO_S() {
        return (int)3185L;
    }
    public static int GL_PIXEL_MAP_I_TO_I() {
        return (int)3184L;
    }
    public static int GL_PIXEL_MAP_I_TO_R() {
        return (int)3186L;
    }
    public static int GL_PIXEL_MAP_I_TO_G() {
        return (int)3187L;
    }
    public static int GL_PIXEL_MAP_I_TO_B() {
        return (int)3188L;
    }
    public static int GL_PIXEL_MAP_I_TO_A() {
        return (int)3189L;
    }
    public static int GL_PIXEL_MAP_R_TO_R() {
        return (int)3190L;
    }
    public static int GL_PIXEL_MAP_G_TO_G() {
        return (int)3191L;
    }
    public static int GL_PIXEL_MAP_B_TO_B() {
        return (int)3192L;
    }
    public static int GL_PIXEL_MAP_A_TO_A() {
        return (int)3193L;
    }
    public static int GL_PACK_ALIGNMENT() {
        return (int)3333L;
    }
    public static int GL_PACK_LSB_FIRST() {
        return (int)3329L;
    }
    public static int GL_PACK_ROW_LENGTH() {
        return (int)3330L;
    }
    public static int GL_PACK_SKIP_PIXELS() {
        return (int)3332L;
    }
    public static int GL_PACK_SKIP_ROWS() {
        return (int)3331L;
    }
    public static int GL_PACK_SWAP_BYTES() {
        return (int)3328L;
    }
    public static int GL_UNPACK_ALIGNMENT() {
        return (int)3317L;
    }
    public static int GL_UNPACK_LSB_FIRST() {
        return (int)3313L;
    }
    public static int GL_UNPACK_ROW_LENGTH() {
        return (int)3314L;
    }
    public static int GL_UNPACK_SKIP_PIXELS() {
        return (int)3316L;
    }
    public static int GL_UNPACK_SKIP_ROWS() {
        return (int)3315L;
    }
    public static int GL_UNPACK_SWAP_BYTES() {
        return (int)3312L;
    }
    public static int GL_ZOOM_X() {
        return (int)3350L;
    }
    public static int GL_ZOOM_Y() {
        return (int)3351L;
    }
    public static int GL_TEXTURE_ENV() {
        return (int)8960L;
    }
    public static int GL_TEXTURE_ENV_MODE() {
        return (int)8704L;
    }
    public static int GL_TEXTURE_1D() {
        return (int)3552L;
    }
    public static int GL_TEXTURE_2D() {
        return (int)3553L;
    }
    public static int GL_TEXTURE_WRAP_S() {
        return (int)10242L;
    }
    public static int GL_TEXTURE_WRAP_T() {
        return (int)10243L;
    }
    public static int GL_TEXTURE_MAG_FILTER() {
        return (int)10240L;
    }
    public static int GL_TEXTURE_MIN_FILTER() {
        return (int)10241L;
    }
    public static int GL_TEXTURE_ENV_COLOR() {
        return (int)8705L;
    }
    public static int GL_TEXTURE_GEN_S() {
        return (int)3168L;
    }
    public static int GL_TEXTURE_GEN_T() {
        return (int)3169L;
    }
    public static int GL_TEXTURE_GEN_R() {
        return (int)3170L;
    }
    public static int GL_TEXTURE_GEN_Q() {
        return (int)3171L;
    }
    public static int GL_TEXTURE_GEN_MODE() {
        return (int)9472L;
    }
    public static int GL_TEXTURE_BORDER_COLOR() {
        return (int)4100L;
    }
    public static int GL_TEXTURE_WIDTH() {
        return (int)4096L;
    }
    public static int GL_TEXTURE_HEIGHT() {
        return (int)4097L;
    }
    public static int GL_TEXTURE_BORDER() {
        return (int)4101L;
    }
    public static int GL_TEXTURE_COMPONENTS() {
        return (int)4099L;
    }
    public static int GL_TEXTURE_RED_SIZE() {
        return (int)32860L;
    }
    public static int GL_TEXTURE_GREEN_SIZE() {
        return (int)32861L;
    }
    public static int GL_TEXTURE_BLUE_SIZE() {
        return (int)32862L;
    }
    public static int GL_TEXTURE_ALPHA_SIZE() {
        return (int)32863L;
    }
    public static int GL_TEXTURE_LUMINANCE_SIZE() {
        return (int)32864L;
    }
    public static int GL_TEXTURE_INTENSITY_SIZE() {
        return (int)32865L;
    }
    public static int GL_NEAREST_MIPMAP_NEAREST() {
        return (int)9984L;
    }
    public static int GL_NEAREST_MIPMAP_LINEAR() {
        return (int)9986L;
    }
    public static int GL_LINEAR_MIPMAP_NEAREST() {
        return (int)9985L;
    }
    public static int GL_LINEAR_MIPMAP_LINEAR() {
        return (int)9987L;
    }
    public static int GL_OBJECT_LINEAR() {
        return (int)9217L;
    }
    public static int GL_OBJECT_PLANE() {
        return (int)9473L;
    }
    public static int GL_EYE_LINEAR() {
        return (int)9216L;
    }
    public static int GL_EYE_PLANE() {
        return (int)9474L;
    }
    public static int GL_SPHERE_MAP() {
        return (int)9218L;
    }
    public static int GL_DECAL() {
        return (int)8449L;
    }
    public static int GL_MODULATE() {
        return (int)8448L;
    }
    public static int GL_NEAREST() {
        return (int)9728L;
    }
    public static int GL_REPEAT() {
        return (int)10497L;
    }
    public static int GL_CLAMP() {
        return (int)10496L;
    }
    public static int GL_S() {
        return (int)8192L;
    }
    public static int GL_T() {
        return (int)8193L;
    }
    public static int GL_R() {
        return (int)8194L;
    }
    public static int GL_Q() {
        return (int)8195L;
    }
    public static int GL_VENDOR() {
        return (int)7936L;
    }
    public static int GL_RENDERER() {
        return (int)7937L;
    }
    public static int GL_VERSION() {
        return (int)7938L;
    }
    public static int GL_EXTENSIONS() {
        return (int)7939L;
    }
    public static int GL_NO_ERROR() {
        return (int)0L;
    }
    public static int GL_INVALID_ENUM() {
        return (int)1280L;
    }
    public static int GL_INVALID_VALUE() {
        return (int)1281L;
    }
    public static int GL_INVALID_OPERATION() {
        return (int)1282L;
    }
    public static int GL_STACK_OVERFLOW() {
        return (int)1283L;
    }
    public static int GL_STACK_UNDERFLOW() {
        return (int)1284L;
    }
    public static int GL_OUT_OF_MEMORY() {
        return (int)1285L;
    }
    public static int GL_CURRENT_BIT() {
        return (int)1L;
    }
    public static int GL_POINT_BIT() {
        return (int)2L;
    }
    public static int GL_LINE_BIT() {
        return (int)4L;
    }
    public static int GL_POLYGON_BIT() {
        return (int)8L;
    }
    public static int GL_POLYGON_STIPPLE_BIT() {
        return (int)16L;
    }
    public static int GL_PIXEL_MODE_BIT() {
        return (int)32L;
    }
    public static int GL_LIGHTING_BIT() {
        return (int)64L;
    }
    public static int GL_FOG_BIT() {
        return (int)128L;
    }
    public static int GL_DEPTH_BUFFER_BIT() {
        return (int)256L;
    }
    public static int GL_ACCUM_BUFFER_BIT() {
        return (int)512L;
    }
    public static int GL_STENCIL_BUFFER_BIT() {
        return (int)1024L;
    }
    public static int GL_VIEWPORT_BIT() {
        return (int)2048L;
    }
    public static int GL_TRANSFORM_BIT() {
        return (int)4096L;
    }
    public static int GL_ENABLE_BIT() {
        return (int)8192L;
    }
    public static int GL_COLOR_BUFFER_BIT() {
        return (int)16384L;
    }
    public static int GL_HINT_BIT() {
        return (int)32768L;
    }
    public static int GL_EVAL_BIT() {
        return (int)65536L;
    }
    public static int GL_LIST_BIT() {
        return (int)131072L;
    }
    public static int GL_TEXTURE_BIT() {
        return (int)262144L;
    }
    public static int GL_SCISSOR_BIT() {
        return (int)524288L;
    }
    public static int GL_PROXY_TEXTURE_1D() {
        return (int)32867L;
    }
    public static int GL_PROXY_TEXTURE_2D() {
        return (int)32868L;
    }
    public static int GL_TEXTURE_PRIORITY() {
        return (int)32870L;
    }
    public static int GL_TEXTURE_RESIDENT() {
        return (int)32871L;
    }
    public static int GL_TEXTURE_BINDING_1D() {
        return (int)32872L;
    }
    public static int GL_TEXTURE_BINDING_2D() {
        return (int)32873L;
    }
    public static int GL_TEXTURE_INTERNAL_FORMAT() {
        return (int)4099L;
    }
    public static int GL_ALPHA4() {
        return (int)32827L;
    }
    public static int GL_ALPHA8() {
        return (int)32828L;
    }
    public static int GL_ALPHA12() {
        return (int)32829L;
    }
    public static int GL_ALPHA16() {
        return (int)32830L;
    }
    public static int GL_LUMINANCE4() {
        return (int)32831L;
    }
    public static int GL_LUMINANCE8() {
        return (int)32832L;
    }
    public static int GL_LUMINANCE12() {
        return (int)32833L;
    }
    public static int GL_LUMINANCE16() {
        return (int)32834L;
    }
    public static int GL_LUMINANCE4_ALPHA4() {
        return (int)32835L;
    }
    public static int GL_LUMINANCE6_ALPHA2() {
        return (int)32836L;
    }
    public static int GL_LUMINANCE8_ALPHA8() {
        return (int)32837L;
    }
    public static int GL_LUMINANCE12_ALPHA4() {
        return (int)32838L;
    }
    public static int GL_LUMINANCE12_ALPHA12() {
        return (int)32839L;
    }
    public static int GL_LUMINANCE16_ALPHA16() {
        return (int)32840L;
    }
    public static int GL_INTENSITY() {
        return (int)32841L;
    }
    public static int GL_INTENSITY4() {
        return (int)32842L;
    }
    public static int GL_INTENSITY8() {
        return (int)32843L;
    }
    public static int GL_INTENSITY12() {
        return (int)32844L;
    }
    public static int GL_INTENSITY16() {
        return (int)32845L;
    }
    public static int GL_R3_G3_B2() {
        return (int)10768L;
    }
    public static int GL_RGB4() {
        return (int)32847L;
    }
    public static int GL_RGB5() {
        return (int)32848L;
    }
    public static int GL_RGB8() {
        return (int)32849L;
    }
    public static int GL_RGB10() {
        return (int)32850L;
    }
    public static int GL_RGB12() {
        return (int)32851L;
    }
    public static int GL_RGB16() {
        return (int)32852L;
    }
    public static int GL_RGBA2() {
        return (int)32853L;
    }
    public static int GL_RGBA4() {
        return (int)32854L;
    }
    public static int GL_RGB5_A1() {
        return (int)32855L;
    }
    public static int GL_RGBA8() {
        return (int)32856L;
    }
    public static int GL_RGB10_A2() {
        return (int)32857L;
    }
    public static int GL_RGBA12() {
        return (int)32858L;
    }
    public static int GL_RGBA16() {
        return (int)32859L;
    }
    public static int GL_CLIENT_PIXEL_STORE_BIT() {
        return (int)1L;
    }
    public static int GL_CLIENT_VERTEX_ARRAY_BIT() {
        return (int)2L;
    }
    public static int GL_RESCALE_NORMAL() {
        return (int)32826L;
    }
    public static int GL_CLAMP_TO_EDGE() {
        return (int)33071L;
    }
    public static int GL_MAX_ELEMENTS_VERTICES() {
        return (int)33000L;
    }
    public static int GL_MAX_ELEMENTS_INDICES() {
        return (int)33001L;
    }
    public static int GL_BGR() {
        return (int)32992L;
    }
    public static int GL_BGRA() {
        return (int)32993L;
    }
    public static int GL_UNSIGNED_BYTE_3_3_2() {
        return (int)32818L;
    }
    public static int GL_UNSIGNED_BYTE_2_3_3_REV() {
        return (int)33634L;
    }
    public static int GL_UNSIGNED_SHORT_5_6_5() {
        return (int)33635L;
    }
    public static int GL_UNSIGNED_SHORT_5_6_5_REV() {
        return (int)33636L;
    }
    public static int GL_UNSIGNED_SHORT_4_4_4_4() {
        return (int)32819L;
    }
    public static int GL_UNSIGNED_SHORT_4_4_4_4_REV() {
        return (int)33637L;
    }
    public static int GL_UNSIGNED_SHORT_5_5_5_1() {
        return (int)32820L;
    }
    public static int GL_UNSIGNED_SHORT_1_5_5_5_REV() {
        return (int)33638L;
    }
    public static int GL_UNSIGNED_INT_8_8_8_8() {
        return (int)32821L;
    }
    public static int GL_UNSIGNED_INT_8_8_8_8_REV() {
        return (int)33639L;
    }
    public static int GL_UNSIGNED_INT_10_10_10_2() {
        return (int)32822L;
    }
    public static int GL_UNSIGNED_INT_2_10_10_10_REV() {
        return (int)33640L;
    }
    public static int GL_LIGHT_MODEL_COLOR_CONTROL() {
        return (int)33272L;
    }
    public static int GL_SINGLE_COLOR() {
        return (int)33273L;
    }
    public static int GL_SEPARATE_SPECULAR_COLOR() {
        return (int)33274L;
    }
    public static int GL_TEXTURE_MIN_LOD() {
        return (int)33082L;
    }
    public static int GL_TEXTURE_MAX_LOD() {
        return (int)33083L;
    }
    public static int GL_TEXTURE_BASE_LEVEL() {
        return (int)33084L;
    }
    public static int GL_TEXTURE_MAX_LEVEL() {
        return (int)33085L;
    }
    public static int GL_SMOOTH_POINT_SIZE_RANGE() {
        return (int)2834L;
    }
    public static int GL_SMOOTH_POINT_SIZE_GRANULARITY() {
        return (int)2835L;
    }
    public static int GL_SMOOTH_LINE_WIDTH_RANGE() {
        return (int)2850L;
    }
    public static int GL_SMOOTH_LINE_WIDTH_GRANULARITY() {
        return (int)2851L;
    }
    public static int GL_ALIASED_POINT_SIZE_RANGE() {
        return (int)33901L;
    }
    public static int GL_ALIASED_LINE_WIDTH_RANGE() {
        return (int)33902L;
    }
    public static int GL_PACK_SKIP_IMAGES() {
        return (int)32875L;
    }
    public static int GL_PACK_IMAGE_HEIGHT() {
        return (int)32876L;
    }
    public static int GL_UNPACK_SKIP_IMAGES() {
        return (int)32877L;
    }
    public static int GL_UNPACK_IMAGE_HEIGHT() {
        return (int)32878L;
    }
    public static int GL_TEXTURE_3D() {
        return (int)32879L;
    }
    public static int GL_PROXY_TEXTURE_3D() {
        return (int)32880L;
    }
    public static int GL_TEXTURE_DEPTH() {
        return (int)32881L;
    }
    public static int GL_TEXTURE_WRAP_R() {
        return (int)32882L;
    }
    public static int GL_MAX_3D_TEXTURE_SIZE() {
        return (int)32883L;
    }
    public static int GL_TEXTURE_BINDING_3D() {
        return (int)32874L;
    }
    public static int GL_CONSTANT_COLOR() {
        return (int)32769L;
    }
    public static int GL_ONE_MINUS_CONSTANT_COLOR() {
        return (int)32770L;
    }
    public static int GL_CONSTANT_ALPHA() {
        return (int)32771L;
    }
    public static int GL_ONE_MINUS_CONSTANT_ALPHA() {
        return (int)32772L;
    }
    public static int GL_COLOR_TABLE() {
        return (int)32976L;
    }
    public static int GL_POST_CONVOLUTION_COLOR_TABLE() {
        return (int)32977L;
    }
    public static int GL_POST_COLOR_MATRIX_COLOR_TABLE() {
        return (int)32978L;
    }
    public static int GL_PROXY_COLOR_TABLE() {
        return (int)32979L;
    }
    public static int GL_PROXY_POST_CONVOLUTION_COLOR_TABLE() {
        return (int)32980L;
    }
    public static int GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE() {
        return (int)32981L;
    }
    public static int GL_COLOR_TABLE_SCALE() {
        return (int)32982L;
    }
    public static int GL_COLOR_TABLE_BIAS() {
        return (int)32983L;
    }
    public static int GL_COLOR_TABLE_FORMAT() {
        return (int)32984L;
    }
    public static int GL_COLOR_TABLE_WIDTH() {
        return (int)32985L;
    }
    public static int GL_COLOR_TABLE_RED_SIZE() {
        return (int)32986L;
    }
    public static int GL_COLOR_TABLE_GREEN_SIZE() {
        return (int)32987L;
    }
    public static int GL_COLOR_TABLE_BLUE_SIZE() {
        return (int)32988L;
    }
    public static int GL_COLOR_TABLE_ALPHA_SIZE() {
        return (int)32989L;
    }
    public static int GL_COLOR_TABLE_LUMINANCE_SIZE() {
        return (int)32990L;
    }
    public static int GL_COLOR_TABLE_INTENSITY_SIZE() {
        return (int)32991L;
    }
    public static int GL_CONVOLUTION_1D() {
        return (int)32784L;
    }
    public static int GL_CONVOLUTION_2D() {
        return (int)32785L;
    }
    public static int GL_SEPARABLE_2D() {
        return (int)32786L;
    }
    public static int GL_CONVOLUTION_BORDER_MODE() {
        return (int)32787L;
    }
    public static int GL_CONVOLUTION_FILTER_SCALE() {
        return (int)32788L;
    }
    public static int GL_CONVOLUTION_FILTER_BIAS() {
        return (int)32789L;
    }
    public static int GL_REDUCE() {
        return (int)32790L;
    }
    public static int GL_CONVOLUTION_FORMAT() {
        return (int)32791L;
    }
    public static int GL_CONVOLUTION_WIDTH() {
        return (int)32792L;
    }
    public static int GL_CONVOLUTION_HEIGHT() {
        return (int)32793L;
    }
    public static int GL_MAX_CONVOLUTION_WIDTH() {
        return (int)32794L;
    }
    public static int GL_MAX_CONVOLUTION_HEIGHT() {
        return (int)32795L;
    }
    public static int GL_POST_CONVOLUTION_RED_SCALE() {
        return (int)32796L;
    }
    public static int GL_POST_CONVOLUTION_GREEN_SCALE() {
        return (int)32797L;
    }
    public static int GL_POST_CONVOLUTION_BLUE_SCALE() {
        return (int)32798L;
    }
    public static int GL_POST_CONVOLUTION_ALPHA_SCALE() {
        return (int)32799L;
    }
    public static int GL_POST_CONVOLUTION_RED_BIAS() {
        return (int)32800L;
    }
    public static int GL_POST_CONVOLUTION_GREEN_BIAS() {
        return (int)32801L;
    }
    public static int GL_POST_CONVOLUTION_BLUE_BIAS() {
        return (int)32802L;
    }
    public static int GL_POST_CONVOLUTION_ALPHA_BIAS() {
        return (int)32803L;
    }
    public static int GL_CONSTANT_BORDER() {
        return (int)33105L;
    }
    public static int GL_REPLICATE_BORDER() {
        return (int)33107L;
    }
    public static int GL_CONVOLUTION_BORDER_COLOR() {
        return (int)33108L;
    }
    public static int GL_COLOR_MATRIX() {
        return (int)32945L;
    }
    public static int GL_COLOR_MATRIX_STACK_DEPTH() {
        return (int)32946L;
    }
    public static int GL_MAX_COLOR_MATRIX_STACK_DEPTH() {
        return (int)32947L;
    }
    public static int GL_POST_COLOR_MATRIX_RED_SCALE() {
        return (int)32948L;
    }
    public static int GL_POST_COLOR_MATRIX_GREEN_SCALE() {
        return (int)32949L;
    }
    public static int GL_POST_COLOR_MATRIX_BLUE_SCALE() {
        return (int)32950L;
    }
    public static int GL_POST_COLOR_MATRIX_ALPHA_SCALE() {
        return (int)32951L;
    }
    public static int GL_POST_COLOR_MATRIX_RED_BIAS() {
        return (int)32952L;
    }
    public static int GL_POST_COLOR_MATRIX_GREEN_BIAS() {
        return (int)32953L;
    }
    public static int GL_POST_COLOR_MATRIX_BLUE_BIAS() {
        return (int)32954L;
    }
    public static int GL_POST_COLOR_MATRIX_ALPHA_BIAS() {
        return (int)32955L;
    }
    public static int GL_HISTOGRAM() {
        return (int)32804L;
    }
    public static int GL_PROXY_HISTOGRAM() {
        return (int)32805L;
    }
    public static int GL_HISTOGRAM_WIDTH() {
        return (int)32806L;
    }
    public static int GL_HISTOGRAM_FORMAT() {
        return (int)32807L;
    }
    public static int GL_HISTOGRAM_RED_SIZE() {
        return (int)32808L;
    }
    public static int GL_HISTOGRAM_GREEN_SIZE() {
        return (int)32809L;
    }
    public static int GL_HISTOGRAM_BLUE_SIZE() {
        return (int)32810L;
    }
    public static int GL_HISTOGRAM_ALPHA_SIZE() {
        return (int)32811L;
    }
    public static int GL_HISTOGRAM_LUMINANCE_SIZE() {
        return (int)32812L;
    }
    public static int GL_HISTOGRAM_SINK() {
        return (int)32813L;
    }
    public static int GL_MINMAX() {
        return (int)32814L;
    }
    public static int GL_MINMAX_FORMAT() {
        return (int)32815L;
    }
    public static int GL_MINMAX_SINK() {
        return (int)32816L;
    }
    public static int GL_TABLE_TOO_LARGE() {
        return (int)32817L;
    }
    public static int GL_BLEND_EQUATION() {
        return (int)32777L;
    }
    public static int GL_MIN() {
        return (int)32775L;
    }
    public static int GL_MAX() {
        return (int)32776L;
    }
    public static int GL_FUNC_ADD() {
        return (int)32774L;
    }
    public static int GL_FUNC_SUBTRACT() {
        return (int)32778L;
    }
    public static int GL_FUNC_REVERSE_SUBTRACT() {
        return (int)32779L;
    }
    public static int GL_BLEND_COLOR() {
        return (int)32773L;
    }
    public static int GL_TEXTURE0() {
        return (int)33984L;
    }
    public static int GL_TEXTURE1() {
        return (int)33985L;
    }
    public static int GL_TEXTURE2() {
        return (int)33986L;
    }
    public static int GL_TEXTURE3() {
        return (int)33987L;
    }
    public static int GL_TEXTURE4() {
        return (int)33988L;
    }
    public static int GL_TEXTURE5() {
        return (int)33989L;
    }
    public static int GL_TEXTURE6() {
        return (int)33990L;
    }
    public static int GL_TEXTURE7() {
        return (int)33991L;
    }
    public static int GL_TEXTURE8() {
        return (int)33992L;
    }
    public static int GL_TEXTURE9() {
        return (int)33993L;
    }
    public static int GL_TEXTURE10() {
        return (int)33994L;
    }
    public static int GL_TEXTURE11() {
        return (int)33995L;
    }
    public static int GL_TEXTURE12() {
        return (int)33996L;
    }
    public static int GL_TEXTURE13() {
        return (int)33997L;
    }
    public static int GL_TEXTURE14() {
        return (int)33998L;
    }
    public static int GL_TEXTURE15() {
        return (int)33999L;
    }
    public static int GL_TEXTURE16() {
        return (int)34000L;
    }
    public static int GL_TEXTURE17() {
        return (int)34001L;
    }
    public static int GL_TEXTURE18() {
        return (int)34002L;
    }
    public static int GL_TEXTURE19() {
        return (int)34003L;
    }
    public static int GL_TEXTURE20() {
        return (int)34004L;
    }
    public static int GL_TEXTURE21() {
        return (int)34005L;
    }
    public static int GL_TEXTURE22() {
        return (int)34006L;
    }
    public static int GL_TEXTURE23() {
        return (int)34007L;
    }
    public static int GL_TEXTURE24() {
        return (int)34008L;
    }
    public static int GL_TEXTURE25() {
        return (int)34009L;
    }
    public static int GL_TEXTURE26() {
        return (int)34010L;
    }
    public static int GL_TEXTURE27() {
        return (int)34011L;
    }
    public static int GL_TEXTURE28() {
        return (int)34012L;
    }
    public static int GL_TEXTURE29() {
        return (int)34013L;
    }
    public static int GL_TEXTURE30() {
        return (int)34014L;
    }
    public static int GL_TEXTURE31() {
        return (int)34015L;
    }
    public static int GL_ACTIVE_TEXTURE() {
        return (int)34016L;
    }
    public static int GL_CLIENT_ACTIVE_TEXTURE() {
        return (int)34017L;
    }
    public static int GL_MAX_TEXTURE_UNITS() {
        return (int)34018L;
    }
    public static int GL_NORMAL_MAP() {
        return (int)34065L;
    }
    public static int GL_REFLECTION_MAP() {
        return (int)34066L;
    }
    public static int GL_TEXTURE_CUBE_MAP() {
        return (int)34067L;
    }
    public static int GL_TEXTURE_BINDING_CUBE_MAP() {
        return (int)34068L;
    }
    public static int GL_TEXTURE_CUBE_MAP_POSITIVE_X() {
        return (int)34069L;
    }
    public static int GL_TEXTURE_CUBE_MAP_NEGATIVE_X() {
        return (int)34070L;
    }
    public static int GL_TEXTURE_CUBE_MAP_POSITIVE_Y() {
        return (int)34071L;
    }
    public static int GL_TEXTURE_CUBE_MAP_NEGATIVE_Y() {
        return (int)34072L;
    }
    public static int GL_TEXTURE_CUBE_MAP_POSITIVE_Z() {
        return (int)34073L;
    }
    public static int GL_TEXTURE_CUBE_MAP_NEGATIVE_Z() {
        return (int)34074L;
    }
    public static int GL_PROXY_TEXTURE_CUBE_MAP() {
        return (int)34075L;
    }
    public static int GL_MAX_CUBE_MAP_TEXTURE_SIZE() {
        return (int)34076L;
    }
    public static int GL_COMPRESSED_ALPHA() {
        return (int)34025L;
    }
    public static int GL_COMPRESSED_LUMINANCE() {
        return (int)34026L;
    }
    public static int GL_COMPRESSED_LUMINANCE_ALPHA() {
        return (int)34027L;
    }
    public static int GL_COMPRESSED_INTENSITY() {
        return (int)34028L;
    }
    public static int GL_COMPRESSED_RGB() {
        return (int)34029L;
    }
    public static int GL_COMPRESSED_RGBA() {
        return (int)34030L;
    }
    public static int GL_TEXTURE_COMPRESSION_HINT() {
        return (int)34031L;
    }
    public static int GL_TEXTURE_COMPRESSED_IMAGE_SIZE() {
        return (int)34464L;
    }
    public static int GL_TEXTURE_COMPRESSED() {
        return (int)34465L;
    }
    public static int GL_NUM_COMPRESSED_TEXTURE_FORMATS() {
        return (int)34466L;
    }
    public static int GL_COMPRESSED_TEXTURE_FORMATS() {
        return (int)34467L;
    }
    public static int GL_MULTISAMPLE() {
        return (int)32925L;
    }
    public static int GL_SAMPLE_ALPHA_TO_COVERAGE() {
        return (int)32926L;
    }
    public static int GL_SAMPLE_ALPHA_TO_ONE() {
        return (int)32927L;
    }
    public static int GL_SAMPLE_COVERAGE() {
        return (int)32928L;
    }
    public static int GL_SAMPLE_BUFFERS() {
        return (int)32936L;
    }
    public static int GL_SAMPLES() {
        return (int)32937L;
    }
    public static int GL_SAMPLE_COVERAGE_VALUE() {
        return (int)32938L;
    }
    public static int GL_SAMPLE_COVERAGE_INVERT() {
        return (int)32939L;
    }
    public static int GL_MULTISAMPLE_BIT() {
        return (int)536870912L;
    }
    public static int GL_TRANSPOSE_MODELVIEW_MATRIX() {
        return (int)34019L;
    }
    public static int GL_TRANSPOSE_PROJECTION_MATRIX() {
        return (int)34020L;
    }
    public static int GL_TRANSPOSE_TEXTURE_MATRIX() {
        return (int)34021L;
    }
    public static int GL_TRANSPOSE_COLOR_MATRIX() {
        return (int)34022L;
    }
    public static int GL_COMBINE() {
        return (int)34160L;
    }
    public static int GL_COMBINE_RGB() {
        return (int)34161L;
    }
    public static int GL_COMBINE_ALPHA() {
        return (int)34162L;
    }
    public static int GL_SOURCE0_RGB() {
        return (int)34176L;
    }
    public static int GL_SOURCE1_RGB() {
        return (int)34177L;
    }
    public static int GL_SOURCE2_RGB() {
        return (int)34178L;
    }
    public static int GL_SOURCE0_ALPHA() {
        return (int)34184L;
    }
    public static int GL_SOURCE1_ALPHA() {
        return (int)34185L;
    }
    public static int GL_SOURCE2_ALPHA() {
        return (int)34186L;
    }
    public static int GL_OPERAND0_RGB() {
        return (int)34192L;
    }
    public static int GL_OPERAND1_RGB() {
        return (int)34193L;
    }
    public static int GL_OPERAND2_RGB() {
        return (int)34194L;
    }
    public static int GL_OPERAND0_ALPHA() {
        return (int)34200L;
    }
    public static int GL_OPERAND1_ALPHA() {
        return (int)34201L;
    }
    public static int GL_OPERAND2_ALPHA() {
        return (int)34202L;
    }
    public static int GL_RGB_SCALE() {
        return (int)34163L;
    }
    public static int GL_ADD_SIGNED() {
        return (int)34164L;
    }
    public static int GL_INTERPOLATE() {
        return (int)34165L;
    }
    public static int GL_SUBTRACT() {
        return (int)34023L;
    }
    public static int GL_CONSTANT() {
        return (int)34166L;
    }
    public static int GL_PRIMARY_COLOR() {
        return (int)34167L;
    }
    public static int GL_PREVIOUS() {
        return (int)34168L;
    }
    public static int GL_DOT3_RGB() {
        return (int)34478L;
    }
    public static int GL_DOT3_RGBA() {
        return (int)34479L;
    }
    public static int GL_CLAMP_TO_BORDER() {
        return (int)33069L;
    }
    public static int GL_ARB_multitexture() {
        return (int)1L;
    }
    public static int GL_TEXTURE0_ARB() {
        return (int)33984L;
    }
    public static int GL_TEXTURE1_ARB() {
        return (int)33985L;
    }
    public static int GL_TEXTURE2_ARB() {
        return (int)33986L;
    }
    public static int GL_TEXTURE3_ARB() {
        return (int)33987L;
    }
    public static int GL_TEXTURE4_ARB() {
        return (int)33988L;
    }
    public static int GL_TEXTURE5_ARB() {
        return (int)33989L;
    }
    public static int GL_TEXTURE6_ARB() {
        return (int)33990L;
    }
    public static int GL_TEXTURE7_ARB() {
        return (int)33991L;
    }
    public static int GL_TEXTURE8_ARB() {
        return (int)33992L;
    }
    public static int GL_TEXTURE9_ARB() {
        return (int)33993L;
    }
    public static int GL_TEXTURE10_ARB() {
        return (int)33994L;
    }
    public static int GL_TEXTURE11_ARB() {
        return (int)33995L;
    }
    public static int GL_TEXTURE12_ARB() {
        return (int)33996L;
    }
    public static int GL_TEXTURE13_ARB() {
        return (int)33997L;
    }
    public static int GL_TEXTURE14_ARB() {
        return (int)33998L;
    }
    public static int GL_TEXTURE15_ARB() {
        return (int)33999L;
    }
    public static int GL_TEXTURE16_ARB() {
        return (int)34000L;
    }
    public static int GL_TEXTURE17_ARB() {
        return (int)34001L;
    }
    public static int GL_TEXTURE18_ARB() {
        return (int)34002L;
    }
    public static int GL_TEXTURE19_ARB() {
        return (int)34003L;
    }
    public static int GL_TEXTURE20_ARB() {
        return (int)34004L;
    }
    public static int GL_TEXTURE21_ARB() {
        return (int)34005L;
    }
    public static int GL_TEXTURE22_ARB() {
        return (int)34006L;
    }
    public static int GL_TEXTURE23_ARB() {
        return (int)34007L;
    }
    public static int GL_TEXTURE24_ARB() {
        return (int)34008L;
    }
    public static int GL_TEXTURE25_ARB() {
        return (int)34009L;
    }
    public static int GL_TEXTURE26_ARB() {
        return (int)34010L;
    }
    public static int GL_TEXTURE27_ARB() {
        return (int)34011L;
    }
    public static int GL_TEXTURE28_ARB() {
        return (int)34012L;
    }
    public static int GL_TEXTURE29_ARB() {
        return (int)34013L;
    }
    public static int GL_TEXTURE30_ARB() {
        return (int)34014L;
    }
    public static int GL_TEXTURE31_ARB() {
        return (int)34015L;
    }
    public static int GL_ACTIVE_TEXTURE_ARB() {
        return (int)34016L;
    }
    public static int GL_CLIENT_ACTIVE_TEXTURE_ARB() {
        return (int)34017L;
    }
    public static int GL_MAX_TEXTURE_UNITS_ARB() {
        return (int)34018L;
    }
    public static int __gl_glext_h_() {
        return (int)1L;
    }
    public static int GL_GLEXT_VERSION() {
        return (int)20180725L;
    }
    public static int GL_VERSION_1_4() {
        return (int)1L;
    }
    public static int GL_BLEND_DST_RGB() {
        return (int)32968L;
    }
    public static int GL_BLEND_SRC_RGB() {
        return (int)32969L;
    }
    public static int GL_BLEND_DST_ALPHA() {
        return (int)32970L;
    }
    public static int GL_BLEND_SRC_ALPHA() {
        return (int)32971L;
    }
    public static int GL_POINT_FADE_THRESHOLD_SIZE() {
        return (int)33064L;
    }
    public static int GL_DEPTH_COMPONENT16() {
        return (int)33189L;
    }
    public static int GL_DEPTH_COMPONENT24() {
        return (int)33190L;
    }
    public static int GL_DEPTH_COMPONENT32() {
        return (int)33191L;
    }
    public static int GL_MIRRORED_REPEAT() {
        return (int)33648L;
    }
    public static int GL_MAX_TEXTURE_LOD_BIAS() {
        return (int)34045L;
    }
    public static int GL_TEXTURE_LOD_BIAS() {
        return (int)34049L;
    }
    public static int GL_INCR_WRAP() {
        return (int)34055L;
    }
    public static int GL_DECR_WRAP() {
        return (int)34056L;
    }
    public static int GL_TEXTURE_DEPTH_SIZE() {
        return (int)34890L;
    }
    public static int GL_TEXTURE_COMPARE_MODE() {
        return (int)34892L;
    }
    public static int GL_TEXTURE_COMPARE_FUNC() {
        return (int)34893L;
    }
    public static int GL_POINT_SIZE_MIN() {
        return (int)33062L;
    }
    public static int GL_POINT_SIZE_MAX() {
        return (int)33063L;
    }
    public static int GL_POINT_DISTANCE_ATTENUATION() {
        return (int)33065L;
    }
    public static int GL_GENERATE_MIPMAP() {
        return (int)33169L;
    }
    public static int GL_GENERATE_MIPMAP_HINT() {
        return (int)33170L;
    }
    public static int GL_FOG_COORDINATE_SOURCE() {
        return (int)33872L;
    }
    public static int GL_FOG_COORDINATE() {
        return (int)33873L;
    }
    public static int GL_FRAGMENT_DEPTH() {
        return (int)33874L;
    }
    public static int GL_CURRENT_FOG_COORDINATE() {
        return (int)33875L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_TYPE() {
        return (int)33876L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_STRIDE() {
        return (int)33877L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_POINTER() {
        return (int)33878L;
    }
    public static int GL_FOG_COORDINATE_ARRAY() {
        return (int)33879L;
    }
    public static int GL_COLOR_SUM() {
        return (int)33880L;
    }
    public static int GL_CURRENT_SECONDARY_COLOR() {
        return (int)33881L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_SIZE() {
        return (int)33882L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_TYPE() {
        return (int)33883L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_STRIDE() {
        return (int)33884L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_POINTER() {
        return (int)33885L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY() {
        return (int)33886L;
    }
    public static int GL_TEXTURE_FILTER_CONTROL() {
        return (int)34048L;
    }
    public static int GL_DEPTH_TEXTURE_MODE() {
        return (int)34891L;
    }
    public static int GL_COMPARE_R_TO_TEXTURE() {
        return (int)34894L;
    }
    public static int GL_VERSION_1_5() {
        return (int)1L;
    }
    public static int _STDINT_H() {
        return (int)1L;
    }
    public static int _FEATURES_H() {
        return (int)1L;
    }
    public static int _DEFAULT_SOURCE() {
        return (int)1L;
    }
    public static int __USE_ISOC11() {
        return (int)1L;
    }
    public static int __USE_ISOC99() {
        return (int)1L;
    }
    public static int __USE_ISOC95() {
        return (int)1L;
    }
    public static int __USE_POSIX_IMPLICITLY() {
        return (int)1L;
    }
    public static int _POSIX_SOURCE() {
        return (int)1L;
    }
    public static int __USE_POSIX() {
        return (int)1L;
    }
    public static int __USE_POSIX2() {
        return (int)1L;
    }
    public static int __USE_POSIX199309() {
        return (int)1L;
    }
    public static int __USE_POSIX199506() {
        return (int)1L;
    }
    public static int __USE_XOPEN2K() {
        return (int)1L;
    }
    public static int __USE_XOPEN2K8() {
        return (int)1L;
    }
    public static int _ATFILE_SOURCE() {
        return (int)1L;
    }
    public static int __USE_MISC() {
        return (int)1L;
    }
    public static int __USE_ATFILE() {
        return (int)1L;
    }
    public static int __USE_FORTIFY_LEVEL() {
        return (int)0L;
    }
    public static int __GLIBC_USE_DEPRECATED_GETS() {
        return (int)0L;
    }
    public static int _STDC_PREDEF_H() {
        return (int)1L;
    }
    public static int __STDC_IEC_559__() {
        return (int)1L;
    }
    public static int __STDC_IEC_559_COMPLEX__() {
        return (int)1L;
    }
    public static int __GNU_LIBRARY__() {
        return (int)6L;
    }
    public static int __GLIBC__() {
        return (int)2L;
    }
    public static int __GLIBC_MINOR__() {
        return (int)28L;
    }
    public static int _SYS_CDEFS_H() {
        return (int)1L;
    }
    public static int __glibc_c99_flexarr_available() {
        return (int)1L;
    }
    public static int __WORDSIZE() {
        return (int)64L;
    }
    public static int __WORDSIZE_TIME64_COMPAT32() {
        return (int)1L;
    }
    public static int __SYSCALL_WORDSIZE() {
        return (int)64L;
    }
    public static int __HAVE_GENERIC_SELECTION() {
        return (int)1L;
    }
    public static int __GLIBC_USE_LIB_EXT2() {
        return (int)0L;
    }
    public static int __GLIBC_USE_IEC_60559_BFP_EXT() {
        return (int)0L;
    }
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT() {
        return (int)0L;
    }
    public static int __GLIBC_USE_IEC_60559_TYPES_EXT() {
        return (int)0L;
    }
    public static int _BITS_TYPES_H() {
        return (int)1L;
    }
    public static int _BITS_TYPESIZES_H() {
        return (int)1L;
    }
    public static int __OFF_T_MATCHES_OFF64_T() {
        return (int)1L;
    }
    public static int __INO_T_MATCHES_INO64_T() {
        return (int)1L;
    }
    public static int __RLIM_T_MATCHES_RLIM64_T() {
        return (int)1L;
    }
    public static int __FD_SETSIZE() {
        return (int)1024L;
    }
    public static int _BITS_WCHAR_H() {
        return (int)1L;
    }
    public static int _BITS_STDINT_INTN_H() {
        return (int)1L;
    }
    public static int _BITS_STDINT_UINTN_H() {
        return (int)1L;
    }
    public static int KHRONOS_SUPPORT_INT64() {
        return (int)1L;
    }
    public static int KHRONOS_SUPPORT_FLOAT() {
        return (int)1L;
    }
    public static int KHRONOS_MAX_ENUM() {
        return (int)2147483647L;
    }
    public static int GL_BUFFER_SIZE() {
        return (int)34660L;
    }
    public static int GL_BUFFER_USAGE() {
        return (int)34661L;
    }
    public static int GL_QUERY_COUNTER_BITS() {
        return (int)34916L;
    }
    public static int GL_CURRENT_QUERY() {
        return (int)34917L;
    }
    public static int GL_QUERY_RESULT() {
        return (int)34918L;
    }
    public static int GL_QUERY_RESULT_AVAILABLE() {
        return (int)34919L;
    }
    public static int GL_ARRAY_BUFFER() {
        return (int)34962L;
    }
    public static int GL_ELEMENT_ARRAY_BUFFER() {
        return (int)34963L;
    }
    public static int GL_ARRAY_BUFFER_BINDING() {
        return (int)34964L;
    }
    public static int GL_ELEMENT_ARRAY_BUFFER_BINDING() {
        return (int)34965L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING() {
        return (int)34975L;
    }
    public static int GL_READ_ONLY() {
        return (int)35000L;
    }
    public static int GL_WRITE_ONLY() {
        return (int)35001L;
    }
    public static int GL_READ_WRITE() {
        return (int)35002L;
    }
    public static int GL_BUFFER_ACCESS() {
        return (int)35003L;
    }
    public static int GL_BUFFER_MAPPED() {
        return (int)35004L;
    }
    public static int GL_BUFFER_MAP_POINTER() {
        return (int)35005L;
    }
    public static int GL_STREAM_DRAW() {
        return (int)35040L;
    }
    public static int GL_STREAM_READ() {
        return (int)35041L;
    }
    public static int GL_STREAM_COPY() {
        return (int)35042L;
    }
    public static int GL_STATIC_DRAW() {
        return (int)35044L;
    }
    public static int GL_STATIC_READ() {
        return (int)35045L;
    }
    public static int GL_STATIC_COPY() {
        return (int)35046L;
    }
    public static int GL_DYNAMIC_DRAW() {
        return (int)35048L;
    }
    public static int GL_DYNAMIC_READ() {
        return (int)35049L;
    }
    public static int GL_DYNAMIC_COPY() {
        return (int)35050L;
    }
    public static int GL_SAMPLES_PASSED() {
        return (int)35092L;
    }
    public static int GL_SRC1_ALPHA() {
        return (int)34185L;
    }
    public static int GL_VERTEX_ARRAY_BUFFER_BINDING() {
        return (int)34966L;
    }
    public static int GL_NORMAL_ARRAY_BUFFER_BINDING() {
        return (int)34967L;
    }
    public static int GL_COLOR_ARRAY_BUFFER_BINDING() {
        return (int)34968L;
    }
    public static int GL_INDEX_ARRAY_BUFFER_BINDING() {
        return (int)34969L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING() {
        return (int)34970L;
    }
    public static int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING() {
        return (int)34971L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING() {
        return (int)34972L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING() {
        return (int)34973L;
    }
    public static int GL_WEIGHT_ARRAY_BUFFER_BINDING() {
        return (int)34974L;
    }
    public static int GL_FOG_COORD_SRC() {
        return (int)33872L;
    }
    public static int GL_FOG_COORD() {
        return (int)33873L;
    }
    public static int GL_CURRENT_FOG_COORD() {
        return (int)33875L;
    }
    public static int GL_FOG_COORD_ARRAY_TYPE() {
        return (int)33876L;
    }
    public static int GL_FOG_COORD_ARRAY_STRIDE() {
        return (int)33877L;
    }
    public static int GL_FOG_COORD_ARRAY_POINTER() {
        return (int)33878L;
    }
    public static int GL_FOG_COORD_ARRAY() {
        return (int)33879L;
    }
    public static int GL_FOG_COORD_ARRAY_BUFFER_BINDING() {
        return (int)34973L;
    }
    public static int GL_SRC0_RGB() {
        return (int)34176L;
    }
    public static int GL_SRC1_RGB() {
        return (int)34177L;
    }
    public static int GL_SRC2_RGB() {
        return (int)34178L;
    }
    public static int GL_SRC0_ALPHA() {
        return (int)34184L;
    }
    public static int GL_SRC2_ALPHA() {
        return (int)34186L;
    }
    public static int GL_VERSION_2_0() {
        return (int)1L;
    }
    public static int GL_BLEND_EQUATION_RGB() {
        return (int)32777L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_ENABLED() {
        return (int)34338L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_SIZE() {
        return (int)34339L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_STRIDE() {
        return (int)34340L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_TYPE() {
        return (int)34341L;
    }
    public static int GL_CURRENT_VERTEX_ATTRIB() {
        return (int)34342L;
    }
    public static int GL_VERTEX_PROGRAM_POINT_SIZE() {
        return (int)34370L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_POINTER() {
        return (int)34373L;
    }
    public static int GL_STENCIL_BACK_FUNC() {
        return (int)34816L;
    }
    public static int GL_STENCIL_BACK_FAIL() {
        return (int)34817L;
    }
    public static int GL_STENCIL_BACK_PASS_DEPTH_FAIL() {
        return (int)34818L;
    }
    public static int GL_STENCIL_BACK_PASS_DEPTH_PASS() {
        return (int)34819L;
    }
    public static int GL_MAX_DRAW_BUFFERS() {
        return (int)34852L;
    }
    public static int GL_DRAW_BUFFER0() {
        return (int)34853L;
    }
    public static int GL_DRAW_BUFFER1() {
        return (int)34854L;
    }
    public static int GL_DRAW_BUFFER2() {
        return (int)34855L;
    }
    public static int GL_DRAW_BUFFER3() {
        return (int)34856L;
    }
    public static int GL_DRAW_BUFFER4() {
        return (int)34857L;
    }
    public static int GL_DRAW_BUFFER5() {
        return (int)34858L;
    }
    public static int GL_DRAW_BUFFER6() {
        return (int)34859L;
    }
    public static int GL_DRAW_BUFFER7() {
        return (int)34860L;
    }
    public static int GL_DRAW_BUFFER8() {
        return (int)34861L;
    }
    public static int GL_DRAW_BUFFER9() {
        return (int)34862L;
    }
    public static int GL_DRAW_BUFFER10() {
        return (int)34863L;
    }
    public static int GL_DRAW_BUFFER11() {
        return (int)34864L;
    }
    public static int GL_DRAW_BUFFER12() {
        return (int)34865L;
    }
    public static int GL_DRAW_BUFFER13() {
        return (int)34866L;
    }
    public static int GL_DRAW_BUFFER14() {
        return (int)34867L;
    }
    public static int GL_DRAW_BUFFER15() {
        return (int)34868L;
    }
    public static int GL_BLEND_EQUATION_ALPHA() {
        return (int)34877L;
    }
    public static int GL_MAX_VERTEX_ATTRIBS() {
        return (int)34921L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED() {
        return (int)34922L;
    }
    public static int GL_MAX_TEXTURE_IMAGE_UNITS() {
        return (int)34930L;
    }
    public static int GL_FRAGMENT_SHADER() {
        return (int)35632L;
    }
    public static int GL_VERTEX_SHADER() {
        return (int)35633L;
    }
    public static int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS() {
        return (int)35657L;
    }
    public static int GL_MAX_VERTEX_UNIFORM_COMPONENTS() {
        return (int)35658L;
    }
    public static int GL_MAX_VARYING_FLOATS() {
        return (int)35659L;
    }
    public static int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS() {
        return (int)35660L;
    }
    public static int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS() {
        return (int)35661L;
    }
    public static int GL_SHADER_TYPE() {
        return (int)35663L;
    }
    public static int GL_FLOAT_VEC2() {
        return (int)35664L;
    }
    public static int GL_FLOAT_VEC3() {
        return (int)35665L;
    }
    public static int GL_FLOAT_VEC4() {
        return (int)35666L;
    }
    public static int GL_INT_VEC2() {
        return (int)35667L;
    }
    public static int GL_INT_VEC3() {
        return (int)35668L;
    }
    public static int GL_INT_VEC4() {
        return (int)35669L;
    }
    public static int GL_BOOL() {
        return (int)35670L;
    }
    public static int GL_BOOL_VEC2() {
        return (int)35671L;
    }
    public static int GL_BOOL_VEC3() {
        return (int)35672L;
    }
    public static int GL_BOOL_VEC4() {
        return (int)35673L;
    }
    public static int GL_FLOAT_MAT2() {
        return (int)35674L;
    }
    public static int GL_FLOAT_MAT3() {
        return (int)35675L;
    }
    public static int GL_FLOAT_MAT4() {
        return (int)35676L;
    }
    public static int GL_SAMPLER_1D() {
        return (int)35677L;
    }
    public static int GL_SAMPLER_2D() {
        return (int)35678L;
    }
    public static int GL_SAMPLER_3D() {
        return (int)35679L;
    }
    public static int GL_SAMPLER_CUBE() {
        return (int)35680L;
    }
    public static int GL_SAMPLER_1D_SHADOW() {
        return (int)35681L;
    }
    public static int GL_SAMPLER_2D_SHADOW() {
        return (int)35682L;
    }
    public static int GL_DELETE_STATUS() {
        return (int)35712L;
    }
    public static int GL_COMPILE_STATUS() {
        return (int)35713L;
    }
    public static int GL_LINK_STATUS() {
        return (int)35714L;
    }
    public static int GL_VALIDATE_STATUS() {
        return (int)35715L;
    }
    public static int GL_INFO_LOG_LENGTH() {
        return (int)35716L;
    }
    public static int GL_ATTACHED_SHADERS() {
        return (int)35717L;
    }
    public static int GL_ACTIVE_UNIFORMS() {
        return (int)35718L;
    }
    public static int GL_ACTIVE_UNIFORM_MAX_LENGTH() {
        return (int)35719L;
    }
    public static int GL_SHADER_SOURCE_LENGTH() {
        return (int)35720L;
    }
    public static int GL_ACTIVE_ATTRIBUTES() {
        return (int)35721L;
    }
    public static int GL_ACTIVE_ATTRIBUTE_MAX_LENGTH() {
        return (int)35722L;
    }
    public static int GL_FRAGMENT_SHADER_DERIVATIVE_HINT() {
        return (int)35723L;
    }
    public static int GL_SHADING_LANGUAGE_VERSION() {
        return (int)35724L;
    }
    public static int GL_CURRENT_PROGRAM() {
        return (int)35725L;
    }
    public static int GL_POINT_SPRITE_COORD_ORIGIN() {
        return (int)36000L;
    }
    public static int GL_LOWER_LEFT() {
        return (int)36001L;
    }
    public static int GL_UPPER_LEFT() {
        return (int)36002L;
    }
}


