// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
 class glut_h_4 extends glut_h_3 {

    public static int GL_MAX_VERTEX_SHADER_INSTRUCTIONS_EXT() {
        return (int)34757L;
    }
    public static int GL_MAX_VERTEX_SHADER_VARIANTS_EXT() {
        return (int)34758L;
    }
    public static int GL_MAX_VERTEX_SHADER_INVARIANTS_EXT() {
        return (int)34759L;
    }
    public static int GL_MAX_VERTEX_SHADER_LOCAL_CONSTANTS_EXT() {
        return (int)34760L;
    }
    public static int GL_MAX_VERTEX_SHADER_LOCALS_EXT() {
        return (int)34761L;
    }
    public static int GL_MAX_OPTIMIZED_VERTEX_SHADER_INSTRUCTIONS_EXT() {
        return (int)34762L;
    }
    public static int GL_MAX_OPTIMIZED_VERTEX_SHADER_VARIANTS_EXT() {
        return (int)34763L;
    }
    public static int GL_MAX_OPTIMIZED_VERTEX_SHADER_LOCAL_CONSTANTS_EXT() {
        return (int)34764L;
    }
    public static int GL_MAX_OPTIMIZED_VERTEX_SHADER_INVARIANTS_EXT() {
        return (int)34765L;
    }
    public static int GL_MAX_OPTIMIZED_VERTEX_SHADER_LOCALS_EXT() {
        return (int)34766L;
    }
    public static int GL_VERTEX_SHADER_INSTRUCTIONS_EXT() {
        return (int)34767L;
    }
    public static int GL_VERTEX_SHADER_VARIANTS_EXT() {
        return (int)34768L;
    }
    public static int GL_VERTEX_SHADER_INVARIANTS_EXT() {
        return (int)34769L;
    }
    public static int GL_VERTEX_SHADER_LOCAL_CONSTANTS_EXT() {
        return (int)34770L;
    }
    public static int GL_VERTEX_SHADER_LOCALS_EXT() {
        return (int)34771L;
    }
    public static int GL_VERTEX_SHADER_OPTIMIZED_EXT() {
        return (int)34772L;
    }
    public static int GL_X_EXT() {
        return (int)34773L;
    }
    public static int GL_Y_EXT() {
        return (int)34774L;
    }
    public static int GL_Z_EXT() {
        return (int)34775L;
    }
    public static int GL_W_EXT() {
        return (int)34776L;
    }
    public static int GL_NEGATIVE_X_EXT() {
        return (int)34777L;
    }
    public static int GL_NEGATIVE_Y_EXT() {
        return (int)34778L;
    }
    public static int GL_NEGATIVE_Z_EXT() {
        return (int)34779L;
    }
    public static int GL_NEGATIVE_W_EXT() {
        return (int)34780L;
    }
    public static int GL_ZERO_EXT() {
        return (int)34781L;
    }
    public static int GL_ONE_EXT() {
        return (int)34782L;
    }
    public static int GL_NEGATIVE_ONE_EXT() {
        return (int)34783L;
    }
    public static int GL_NORMALIZED_RANGE_EXT() {
        return (int)34784L;
    }
    public static int GL_FULL_RANGE_EXT() {
        return (int)34785L;
    }
    public static int GL_CURRENT_VERTEX_EXT() {
        return (int)34786L;
    }
    public static int GL_MVP_MATRIX_EXT() {
        return (int)34787L;
    }
    public static int GL_VARIANT_VALUE_EXT() {
        return (int)34788L;
    }
    public static int GL_VARIANT_DATATYPE_EXT() {
        return (int)34789L;
    }
    public static int GL_VARIANT_ARRAY_STRIDE_EXT() {
        return (int)34790L;
    }
    public static int GL_VARIANT_ARRAY_TYPE_EXT() {
        return (int)34791L;
    }
    public static int GL_VARIANT_ARRAY_EXT() {
        return (int)34792L;
    }
    public static int GL_VARIANT_ARRAY_POINTER_EXT() {
        return (int)34793L;
    }
    public static int GL_INVARIANT_VALUE_EXT() {
        return (int)34794L;
    }
    public static int GL_INVARIANT_DATATYPE_EXT() {
        return (int)34795L;
    }
    public static int GL_LOCAL_CONSTANT_VALUE_EXT() {
        return (int)34796L;
    }
    public static int GL_LOCAL_CONSTANT_DATATYPE_EXT() {
        return (int)34797L;
    }
    public static int GL_EXT_vertex_weighting() {
        return (int)1L;
    }
    public static int GL_MODELVIEW0_STACK_DEPTH_EXT() {
        return (int)2979L;
    }
    public static int GL_MODELVIEW1_STACK_DEPTH_EXT() {
        return (int)34050L;
    }
    public static int GL_MODELVIEW0_MATRIX_EXT() {
        return (int)2982L;
    }
    public static int GL_MODELVIEW1_MATRIX_EXT() {
        return (int)34054L;
    }
    public static int GL_VERTEX_WEIGHTING_EXT() {
        return (int)34057L;
    }
    public static int GL_MODELVIEW0_EXT() {
        return (int)5888L;
    }
    public static int GL_MODELVIEW1_EXT() {
        return (int)34058L;
    }
    public static int GL_CURRENT_VERTEX_WEIGHT_EXT() {
        return (int)34059L;
    }
    public static int GL_VERTEX_WEIGHT_ARRAY_EXT() {
        return (int)34060L;
    }
    public static int GL_VERTEX_WEIGHT_ARRAY_SIZE_EXT() {
        return (int)34061L;
    }
    public static int GL_VERTEX_WEIGHT_ARRAY_TYPE_EXT() {
        return (int)34062L;
    }
    public static int GL_VERTEX_WEIGHT_ARRAY_STRIDE_EXT() {
        return (int)34063L;
    }
    public static int GL_VERTEX_WEIGHT_ARRAY_POINTER_EXT() {
        return (int)34064L;
    }
    public static int GL_EXT_win32_keyed_mutex() {
        return (int)1L;
    }
    public static int GL_EXT_window_rectangles() {
        return (int)1L;
    }
    public static int GL_INCLUSIVE_EXT() {
        return (int)36624L;
    }
    public static int GL_EXCLUSIVE_EXT() {
        return (int)36625L;
    }
    public static int GL_WINDOW_RECTANGLE_EXT() {
        return (int)36626L;
    }
    public static int GL_WINDOW_RECTANGLE_MODE_EXT() {
        return (int)36627L;
    }
    public static int GL_MAX_WINDOW_RECTANGLES_EXT() {
        return (int)36628L;
    }
    public static int GL_NUM_WINDOW_RECTANGLES_EXT() {
        return (int)36629L;
    }
    public static int GL_EXT_x11_sync_object() {
        return (int)1L;
    }
    public static int GL_SYNC_X11_FENCE_EXT() {
        return (int)37089L;
    }
    public static int GL_GREMEDY_frame_terminator() {
        return (int)1L;
    }
    public static int GL_GREMEDY_string_marker() {
        return (int)1L;
    }
    public static int GL_HP_convolution_border_modes() {
        return (int)1L;
    }
    public static int GL_IGNORE_BORDER_HP() {
        return (int)33104L;
    }
    public static int GL_CONSTANT_BORDER_HP() {
        return (int)33105L;
    }
    public static int GL_REPLICATE_BORDER_HP() {
        return (int)33107L;
    }
    public static int GL_CONVOLUTION_BORDER_COLOR_HP() {
        return (int)33108L;
    }
    public static int GL_HP_image_transform() {
        return (int)1L;
    }
    public static int GL_IMAGE_SCALE_X_HP() {
        return (int)33109L;
    }
    public static int GL_IMAGE_SCALE_Y_HP() {
        return (int)33110L;
    }
    public static int GL_IMAGE_TRANSLATE_X_HP() {
        return (int)33111L;
    }
    public static int GL_IMAGE_TRANSLATE_Y_HP() {
        return (int)33112L;
    }
    public static int GL_IMAGE_ROTATE_ANGLE_HP() {
        return (int)33113L;
    }
    public static int GL_IMAGE_ROTATE_ORIGIN_X_HP() {
        return (int)33114L;
    }
    public static int GL_IMAGE_ROTATE_ORIGIN_Y_HP() {
        return (int)33115L;
    }
    public static int GL_IMAGE_MAG_FILTER_HP() {
        return (int)33116L;
    }
    public static int GL_IMAGE_MIN_FILTER_HP() {
        return (int)33117L;
    }
    public static int GL_IMAGE_CUBIC_WEIGHT_HP() {
        return (int)33118L;
    }
    public static int GL_CUBIC_HP() {
        return (int)33119L;
    }
    public static int GL_AVERAGE_HP() {
        return (int)33120L;
    }
    public static int GL_IMAGE_TRANSFORM_2D_HP() {
        return (int)33121L;
    }
    public static int GL_POST_IMAGE_TRANSFORM_COLOR_TABLE_HP() {
        return (int)33122L;
    }
    public static int GL_PROXY_POST_IMAGE_TRANSFORM_COLOR_TABLE_HP() {
        return (int)33123L;
    }
    public static int GL_HP_occlusion_test() {
        return (int)1L;
    }
    public static int GL_OCCLUSION_TEST_HP() {
        return (int)33125L;
    }
    public static int GL_OCCLUSION_TEST_RESULT_HP() {
        return (int)33126L;
    }
    public static int GL_HP_texture_lighting() {
        return (int)1L;
    }
    public static int GL_TEXTURE_LIGHTING_MODE_HP() {
        return (int)33127L;
    }
    public static int GL_TEXTURE_POST_SPECULAR_HP() {
        return (int)33128L;
    }
    public static int GL_TEXTURE_PRE_SPECULAR_HP() {
        return (int)33129L;
    }
    public static int GL_IBM_cull_vertex() {
        return (int)1L;
    }
    public static int GL_CULL_VERTEX_IBM() {
        return (int)103050L;
    }
    public static int GL_IBM_multimode_draw_arrays() {
        return (int)1L;
    }
    public static int GL_IBM_rasterpos_clip() {
        return (int)1L;
    }
    public static int GL_RASTER_POSITION_UNCLIPPED_IBM() {
        return (int)103010L;
    }
    public static int GL_IBM_static_data() {
        return (int)1L;
    }
    public static int GL_ALL_STATIC_DATA_IBM() {
        return (int)103060L;
    }
    public static int GL_STATIC_VERTEX_ARRAY_IBM() {
        return (int)103061L;
    }
    public static int GL_IBM_texture_mirrored_repeat() {
        return (int)1L;
    }
    public static int GL_MIRRORED_REPEAT_IBM() {
        return (int)33648L;
    }
    public static int GL_IBM_vertex_array_lists() {
        return (int)1L;
    }
    public static int GL_VERTEX_ARRAY_LIST_IBM() {
        return (int)103070L;
    }
    public static int GL_NORMAL_ARRAY_LIST_IBM() {
        return (int)103071L;
    }
    public static int GL_COLOR_ARRAY_LIST_IBM() {
        return (int)103072L;
    }
    public static int GL_INDEX_ARRAY_LIST_IBM() {
        return (int)103073L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_LIST_IBM() {
        return (int)103074L;
    }
    public static int GL_EDGE_FLAG_ARRAY_LIST_IBM() {
        return (int)103075L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_LIST_IBM() {
        return (int)103076L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_LIST_IBM() {
        return (int)103077L;
    }
    public static int GL_VERTEX_ARRAY_LIST_STRIDE_IBM() {
        return (int)103080L;
    }
    public static int GL_NORMAL_ARRAY_LIST_STRIDE_IBM() {
        return (int)103081L;
    }
    public static int GL_COLOR_ARRAY_LIST_STRIDE_IBM() {
        return (int)103082L;
    }
    public static int GL_INDEX_ARRAY_LIST_STRIDE_IBM() {
        return (int)103083L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_LIST_STRIDE_IBM() {
        return (int)103084L;
    }
    public static int GL_EDGE_FLAG_ARRAY_LIST_STRIDE_IBM() {
        return (int)103085L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_LIST_STRIDE_IBM() {
        return (int)103086L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_LIST_STRIDE_IBM() {
        return (int)103087L;
    }
    public static int GL_INGR_blend_func_separate() {
        return (int)1L;
    }
    public static int GL_INGR_color_clamp() {
        return (int)1L;
    }
    public static int GL_RED_MIN_CLAMP_INGR() {
        return (int)34144L;
    }
    public static int GL_GREEN_MIN_CLAMP_INGR() {
        return (int)34145L;
    }
    public static int GL_BLUE_MIN_CLAMP_INGR() {
        return (int)34146L;
    }
    public static int GL_ALPHA_MIN_CLAMP_INGR() {
        return (int)34147L;
    }
    public static int GL_RED_MAX_CLAMP_INGR() {
        return (int)34148L;
    }
    public static int GL_GREEN_MAX_CLAMP_INGR() {
        return (int)34149L;
    }
    public static int GL_BLUE_MAX_CLAMP_INGR() {
        return (int)34150L;
    }
    public static int GL_ALPHA_MAX_CLAMP_INGR() {
        return (int)34151L;
    }
    public static int GL_INGR_interlace_read() {
        return (int)1L;
    }
    public static int GL_INTERLACE_READ_INGR() {
        return (int)34152L;
    }
    public static int GL_INTEL_blackhole_render() {
        return (int)1L;
    }
    public static int GL_BLACKHOLE_RENDER_INTEL() {
        return (int)33788L;
    }
    public static int GL_INTEL_conservative_rasterization() {
        return (int)1L;
    }
    public static int GL_CONSERVATIVE_RASTERIZATION_INTEL() {
        return (int)33790L;
    }
    public static int GL_INTEL_fragment_shader_ordering() {
        return (int)1L;
    }
    public static int GL_INTEL_framebuffer_CMAA() {
        return (int)1L;
    }
    public static int GL_INTEL_map_texture() {
        return (int)1L;
    }
    public static int GL_TEXTURE_MEMORY_LAYOUT_INTEL() {
        return (int)33791L;
    }
    public static int GL_LAYOUT_DEFAULT_INTEL() {
        return (int)0L;
    }
    public static int GL_LAYOUT_LINEAR_INTEL() {
        return (int)1L;
    }
    public static int GL_LAYOUT_LINEAR_CPU_CACHED_INTEL() {
        return (int)2L;
    }
    public static int GL_INTEL_parallel_arrays() {
        return (int)1L;
    }
    public static int GL_PARALLEL_ARRAYS_INTEL() {
        return (int)33780L;
    }
    public static int GL_VERTEX_ARRAY_PARALLEL_POINTERS_INTEL() {
        return (int)33781L;
    }
    public static int GL_NORMAL_ARRAY_PARALLEL_POINTERS_INTEL() {
        return (int)33782L;
    }
    public static int GL_COLOR_ARRAY_PARALLEL_POINTERS_INTEL() {
        return (int)33783L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_PARALLEL_POINTERS_INTEL() {
        return (int)33784L;
    }
    public static int GL_INTEL_performance_query() {
        return (int)1L;
    }
    public static int GL_PERFQUERY_SINGLE_CONTEXT_INTEL() {
        return (int)0L;
    }
    public static int GL_PERFQUERY_GLOBAL_CONTEXT_INTEL() {
        return (int)1L;
    }
    public static int GL_PERFQUERY_WAIT_INTEL() {
        return (int)33787L;
    }
    public static int GL_PERFQUERY_FLUSH_INTEL() {
        return (int)33786L;
    }
    public static int GL_PERFQUERY_DONOT_FLUSH_INTEL() {
        return (int)33785L;
    }
    public static int GL_PERFQUERY_COUNTER_EVENT_INTEL() {
        return (int)38128L;
    }
    public static int GL_PERFQUERY_COUNTER_DURATION_NORM_INTEL() {
        return (int)38129L;
    }
    public static int GL_PERFQUERY_COUNTER_DURATION_RAW_INTEL() {
        return (int)38130L;
    }
    public static int GL_PERFQUERY_COUNTER_THROUGHPUT_INTEL() {
        return (int)38131L;
    }
    public static int GL_PERFQUERY_COUNTER_RAW_INTEL() {
        return (int)38132L;
    }
    public static int GL_PERFQUERY_COUNTER_TIMESTAMP_INTEL() {
        return (int)38133L;
    }
    public static int GL_PERFQUERY_COUNTER_DATA_UINT32_INTEL() {
        return (int)38136L;
    }
    public static int GL_PERFQUERY_COUNTER_DATA_UINT64_INTEL() {
        return (int)38137L;
    }
    public static int GL_PERFQUERY_COUNTER_DATA_FLOAT_INTEL() {
        return (int)38138L;
    }
    public static int GL_PERFQUERY_COUNTER_DATA_DOUBLE_INTEL() {
        return (int)38139L;
    }
    public static int GL_PERFQUERY_COUNTER_DATA_BOOL32_INTEL() {
        return (int)38140L;
    }
    public static int GL_PERFQUERY_QUERY_NAME_LENGTH_MAX_INTEL() {
        return (int)38141L;
    }
    public static int GL_PERFQUERY_COUNTER_NAME_LENGTH_MAX_INTEL() {
        return (int)38142L;
    }
    public static int GL_PERFQUERY_COUNTER_DESC_LENGTH_MAX_INTEL() {
        return (int)38143L;
    }
    public static int GL_PERFQUERY_GPA_EXTENDED_COUNTERS_INTEL() {
        return (int)38144L;
    }
    public static int GL_MESAX_texture_stack() {
        return (int)1L;
    }
    public static int GL_TEXTURE_1D_STACK_MESAX() {
        return (int)34649L;
    }
    public static int GL_TEXTURE_2D_STACK_MESAX() {
        return (int)34650L;
    }
    public static int GL_PROXY_TEXTURE_1D_STACK_MESAX() {
        return (int)34651L;
    }
    public static int GL_PROXY_TEXTURE_2D_STACK_MESAX() {
        return (int)34652L;
    }
    public static int GL_TEXTURE_1D_STACK_BINDING_MESAX() {
        return (int)34653L;
    }
    public static int GL_TEXTURE_2D_STACK_BINDING_MESAX() {
        return (int)34654L;
    }
    public static int GL_MESA_pack_invert() {
        return (int)1L;
    }
    public static int GL_PACK_INVERT_MESA() {
        return (int)34648L;
    }
    public static int GL_MESA_program_binary_formats() {
        return (int)1L;
    }
    public static int GL_PROGRAM_BINARY_FORMAT_MESA() {
        return (int)34655L;
    }
    public static int GL_MESA_resize_buffers() {
        return (int)1L;
    }
    public static int GL_MESA_shader_integer_functions() {
        return (int)1L;
    }
    public static int GL_MESA_tile_raster_order() {
        return (int)1L;
    }
    public static int GL_TILE_RASTER_ORDER_FIXED_MESA() {
        return (int)35768L;
    }
    public static int GL_TILE_RASTER_ORDER_INCREASING_X_MESA() {
        return (int)35769L;
    }
    public static int GL_TILE_RASTER_ORDER_INCREASING_Y_MESA() {
        return (int)35770L;
    }
    public static int GL_MESA_window_pos() {
        return (int)1L;
    }
    public static int GL_MESA_ycbcr_texture() {
        return (int)1L;
    }
    public static int GL_UNSIGNED_SHORT_8_8_MESA() {
        return (int)34234L;
    }
    public static int GL_UNSIGNED_SHORT_8_8_REV_MESA() {
        return (int)34235L;
    }
    public static int GL_YCBCR_MESA() {
        return (int)34647L;
    }
    public static int GL_NVX_blend_equation_advanced_multi_draw_buffers() {
        return (int)1L;
    }
    public static int GL_NVX_conditional_render() {
        return (int)1L;
    }
    public static int GL_NVX_gpu_memory_info() {
        return (int)1L;
    }
    public static int GL_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX() {
        return (int)36935L;
    }
    public static int GL_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX() {
        return (int)36936L;
    }
    public static int GL_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX() {
        return (int)36937L;
    }
    public static int GL_GPU_MEMORY_INFO_EVICTION_COUNT_NVX() {
        return (int)36938L;
    }
    public static int GL_GPU_MEMORY_INFO_EVICTED_MEMORY_NVX() {
        return (int)36939L;
    }
    public static int GL_NVX_linked_gpu_multicast() {
        return (int)1L;
    }
    public static int GL_LGPU_SEPARATE_STORAGE_BIT_NVX() {
        return (int)2048L;
    }
    public static int GL_MAX_LGPU_GPUS_NVX() {
        return (int)37562L;
    }
    public static int GL_NV_alpha_to_coverage_dither_control() {
        return (int)1L;
    }
    public static int GL_ALPHA_TO_COVERAGE_DITHER_DEFAULT_NV() {
        return (int)37709L;
    }
    public static int GL_ALPHA_TO_COVERAGE_DITHER_ENABLE_NV() {
        return (int)37710L;
    }
    public static int GL_ALPHA_TO_COVERAGE_DITHER_DISABLE_NV() {
        return (int)37711L;
    }
    public static int GL_ALPHA_TO_COVERAGE_DITHER_MODE_NV() {
        return (int)37567L;
    }
    public static int GL_NV_bindless_multi_draw_indirect() {
        return (int)1L;
    }
    public static int GL_NV_bindless_multi_draw_indirect_count() {
        return (int)1L;
    }
    public static int GL_NV_bindless_texture() {
        return (int)1L;
    }
    public static int GL_NV_blend_equation_advanced() {
        return (int)1L;
    }
    public static int GL_BLEND_OVERLAP_NV() {
        return (int)37505L;
    }
    public static int GL_BLEND_PREMULTIPLIED_SRC_NV() {
        return (int)37504L;
    }
    public static int GL_BLUE_NV() {
        return (int)6405L;
    }
    public static int GL_COLORBURN_NV() {
        return (int)37530L;
    }
    public static int GL_COLORDODGE_NV() {
        return (int)37529L;
    }
    public static int GL_CONJOINT_NV() {
        return (int)37508L;
    }
    public static int GL_CONTRAST_NV() {
        return (int)37537L;
    }
    public static int GL_DARKEN_NV() {
        return (int)37527L;
    }
    public static int GL_DIFFERENCE_NV() {
        return (int)37534L;
    }
    public static int GL_DISJOINT_NV() {
        return (int)37507L;
    }
    public static int GL_DST_ATOP_NV() {
        return (int)37519L;
    }
    public static int GL_DST_IN_NV() {
        return (int)37515L;
    }
    public static int GL_DST_NV() {
        return (int)37511L;
    }
    public static int GL_DST_OUT_NV() {
        return (int)37517L;
    }
    public static int GL_DST_OVER_NV() {
        return (int)37513L;
    }
    public static int GL_EXCLUSION_NV() {
        return (int)37536L;
    }
    public static int GL_GREEN_NV() {
        return (int)6404L;
    }
    public static int GL_HARDLIGHT_NV() {
        return (int)37531L;
    }
    public static int GL_HARDMIX_NV() {
        return (int)37545L;
    }
    public static int GL_HSL_COLOR_NV() {
        return (int)37551L;
    }
    public static int GL_HSL_HUE_NV() {
        return (int)37549L;
    }
    public static int GL_HSL_LUMINOSITY_NV() {
        return (int)37552L;
    }
    public static int GL_HSL_SATURATION_NV() {
        return (int)37550L;
    }
    public static int GL_INVERT_OVG_NV() {
        return (int)37556L;
    }
    public static int GL_INVERT_RGB_NV() {
        return (int)37539L;
    }
    public static int GL_LIGHTEN_NV() {
        return (int)37528L;
    }
    public static int GL_LINEARBURN_NV() {
        return (int)37541L;
    }
    public static int GL_LINEARDODGE_NV() {
        return (int)37540L;
    }
    public static int GL_LINEARLIGHT_NV() {
        return (int)37543L;
    }
    public static int GL_MINUS_CLAMPED_NV() {
        return (int)37555L;
    }
    public static int GL_MINUS_NV() {
        return (int)37535L;
    }
    public static int GL_MULTIPLY_NV() {
        return (int)37524L;
    }
    public static int GL_OVERLAY_NV() {
        return (int)37526L;
    }
    public static int GL_PINLIGHT_NV() {
        return (int)37544L;
    }
    public static int GL_PLUS_CLAMPED_ALPHA_NV() {
        return (int)37554L;
    }
    public static int GL_PLUS_CLAMPED_NV() {
        return (int)37553L;
    }
    public static int GL_PLUS_DARKER_NV() {
        return (int)37522L;
    }
    public static int GL_PLUS_NV() {
        return (int)37521L;
    }
    public static int GL_RED_NV() {
        return (int)6403L;
    }
    public static int GL_SCREEN_NV() {
        return (int)37525L;
    }
    public static int GL_SOFTLIGHT_NV() {
        return (int)37532L;
    }
    public static int GL_SRC_ATOP_NV() {
        return (int)37518L;
    }
    public static int GL_SRC_IN_NV() {
        return (int)37514L;
    }
    public static int GL_SRC_NV() {
        return (int)37510L;
    }
    public static int GL_SRC_OUT_NV() {
        return (int)37516L;
    }
    public static int GL_SRC_OVER_NV() {
        return (int)37512L;
    }
    public static int GL_UNCORRELATED_NV() {
        return (int)37506L;
    }
    public static int GL_VIVIDLIGHT_NV() {
        return (int)37542L;
    }
    public static int GL_XOR_NV() {
        return (int)5382L;
    }
    public static int GL_NV_blend_equation_advanced_coherent() {
        return (int)1L;
    }
    public static int GL_BLEND_ADVANCED_COHERENT_NV() {
        return (int)37509L;
    }
    public static int GL_NV_blend_minmax_factor() {
        return (int)1L;
    }
    public static int GL_NV_blend_square() {
        return (int)1L;
    }
    public static int GL_NV_clip_space_w_scaling() {
        return (int)1L;
    }
    public static int GL_VIEWPORT_POSITION_W_SCALE_NV() {
        return (int)37756L;
    }
    public static int GL_VIEWPORT_POSITION_W_SCALE_X_COEFF_NV() {
        return (int)37757L;
    }
    public static int GL_VIEWPORT_POSITION_W_SCALE_Y_COEFF_NV() {
        return (int)37758L;
    }
    public static int GL_NV_command_list() {
        return (int)1L;
    }
    public static int GL_TERMINATE_SEQUENCE_COMMAND_NV() {
        return (int)0L;
    }
    public static int GL_NOP_COMMAND_NV() {
        return (int)1L;
    }
    public static int GL_DRAW_ELEMENTS_COMMAND_NV() {
        return (int)2L;
    }
    public static int GL_DRAW_ARRAYS_COMMAND_NV() {
        return (int)3L;
    }
    public static int GL_DRAW_ELEMENTS_STRIP_COMMAND_NV() {
        return (int)4L;
    }
    public static int GL_DRAW_ARRAYS_STRIP_COMMAND_NV() {
        return (int)5L;
    }
    public static int GL_DRAW_ELEMENTS_INSTANCED_COMMAND_NV() {
        return (int)6L;
    }
    public static int GL_DRAW_ARRAYS_INSTANCED_COMMAND_NV() {
        return (int)7L;
    }
    public static int GL_ELEMENT_ADDRESS_COMMAND_NV() {
        return (int)8L;
    }
    public static int GL_ATTRIBUTE_ADDRESS_COMMAND_NV() {
        return (int)9L;
    }
    public static int GL_UNIFORM_ADDRESS_COMMAND_NV() {
        return (int)10L;
    }
    public static int GL_BLEND_COLOR_COMMAND_NV() {
        return (int)11L;
    }
    public static int GL_STENCIL_REF_COMMAND_NV() {
        return (int)12L;
    }
    public static int GL_LINE_WIDTH_COMMAND_NV() {
        return (int)13L;
    }
    public static int GL_POLYGON_OFFSET_COMMAND_NV() {
        return (int)14L;
    }
    public static int GL_ALPHA_REF_COMMAND_NV() {
        return (int)15L;
    }
    public static int GL_VIEWPORT_COMMAND_NV() {
        return (int)16L;
    }
    public static int GL_SCISSOR_COMMAND_NV() {
        return (int)17L;
    }
    public static int GL_FRONT_FACE_COMMAND_NV() {
        return (int)18L;
    }
    public static int GL_NV_compute_program5() {
        return (int)1L;
    }
    public static int GL_COMPUTE_PROGRAM_NV() {
        return (int)37115L;
    }
    public static int GL_COMPUTE_PROGRAM_PARAMETER_BUFFER_NV() {
        return (int)37116L;
    }
    public static int GL_NV_conditional_render() {
        return (int)1L;
    }
    public static int GL_QUERY_WAIT_NV() {
        return (int)36371L;
    }
    public static int GL_QUERY_NO_WAIT_NV() {
        return (int)36372L;
    }
    public static int GL_QUERY_BY_REGION_WAIT_NV() {
        return (int)36373L;
    }
    public static int GL_QUERY_BY_REGION_NO_WAIT_NV() {
        return (int)36374L;
    }
    public static int GL_NV_conservative_raster() {
        return (int)1L;
    }
    public static int GL_CONSERVATIVE_RASTERIZATION_NV() {
        return (int)37702L;
    }
    public static int GL_SUBPIXEL_PRECISION_BIAS_X_BITS_NV() {
        return (int)37703L;
    }
    public static int GL_SUBPIXEL_PRECISION_BIAS_Y_BITS_NV() {
        return (int)37704L;
    }
    public static int GL_MAX_SUBPIXEL_PRECISION_BIAS_BITS_NV() {
        return (int)37705L;
    }
    public static int GL_NV_conservative_raster_dilate() {
        return (int)1L;
    }
    public static int GL_CONSERVATIVE_RASTER_DILATE_NV() {
        return (int)37753L;
    }
    public static int GL_CONSERVATIVE_RASTER_DILATE_RANGE_NV() {
        return (int)37754L;
    }
    public static int GL_CONSERVATIVE_RASTER_DILATE_GRANULARITY_NV() {
        return (int)37755L;
    }
    public static int GL_NV_conservative_raster_pre_snap() {
        return (int)1L;
    }
    public static int GL_CONSERVATIVE_RASTER_MODE_PRE_SNAP_NV() {
        return (int)38224L;
    }
    public static int GL_NV_conservative_raster_pre_snap_triangles() {
        return (int)1L;
    }
    public static int GL_CONSERVATIVE_RASTER_MODE_NV() {
        return (int)38221L;
    }
    public static int GL_CONSERVATIVE_RASTER_MODE_POST_SNAP_NV() {
        return (int)38222L;
    }
    public static int GL_CONSERVATIVE_RASTER_MODE_PRE_SNAP_TRIANGLES_NV() {
        return (int)38223L;
    }
    public static int GL_NV_conservative_raster_underestimation() {
        return (int)1L;
    }
    public static int GL_NV_copy_depth_to_color() {
        return (int)1L;
    }
    public static int GL_DEPTH_STENCIL_TO_RGBA_NV() {
        return (int)34926L;
    }
    public static int GL_DEPTH_STENCIL_TO_BGRA_NV() {
        return (int)34927L;
    }
    public static int GL_NV_copy_image() {
        return (int)1L;
    }
    public static int GL_NV_deep_texture3D() {
        return (int)1L;
    }
    public static int GL_MAX_DEEP_3D_TEXTURE_WIDTH_HEIGHT_NV() {
        return (int)37072L;
    }
    public static int GL_MAX_DEEP_3D_TEXTURE_DEPTH_NV() {
        return (int)37073L;
    }
    public static int GL_NV_depth_buffer_float() {
        return (int)1L;
    }
    public static int GL_DEPTH_COMPONENT32F_NV() {
        return (int)36267L;
    }
    public static int GL_DEPTH32F_STENCIL8_NV() {
        return (int)36268L;
    }
    public static int GL_FLOAT_32_UNSIGNED_INT_24_8_REV_NV() {
        return (int)36269L;
    }
    public static int GL_DEPTH_BUFFER_FLOAT_MODE_NV() {
        return (int)36271L;
    }
    public static int GL_NV_depth_clamp() {
        return (int)1L;
    }
    public static int GL_DEPTH_CLAMP_NV() {
        return (int)34383L;
    }
    public static int GL_NV_draw_texture() {
        return (int)1L;
    }
    public static int GL_NV_draw_vulkan_image() {
        return (int)1L;
    }
    public static int GL_NV_evaluators() {
        return (int)1L;
    }
    public static int GL_EVAL_2D_NV() {
        return (int)34496L;
    }
    public static int GL_EVAL_TRIANGULAR_2D_NV() {
        return (int)34497L;
    }
    public static int GL_MAP_TESSELLATION_NV() {
        return (int)34498L;
    }
    public static int GL_MAP_ATTRIB_U_ORDER_NV() {
        return (int)34499L;
    }
    public static int GL_MAP_ATTRIB_V_ORDER_NV() {
        return (int)34500L;
    }
    public static int GL_EVAL_FRACTIONAL_TESSELLATION_NV() {
        return (int)34501L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB0_NV() {
        return (int)34502L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB1_NV() {
        return (int)34503L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB2_NV() {
        return (int)34504L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB3_NV() {
        return (int)34505L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB4_NV() {
        return (int)34506L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB5_NV() {
        return (int)34507L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB6_NV() {
        return (int)34508L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB7_NV() {
        return (int)34509L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB8_NV() {
        return (int)34510L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB9_NV() {
        return (int)34511L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB10_NV() {
        return (int)34512L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB11_NV() {
        return (int)34513L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB12_NV() {
        return (int)34514L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB13_NV() {
        return (int)34515L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB14_NV() {
        return (int)34516L;
    }
    public static int GL_EVAL_VERTEX_ATTRIB15_NV() {
        return (int)34517L;
    }
    public static int GL_MAX_MAP_TESSELLATION_NV() {
        return (int)34518L;
    }
    public static int GL_MAX_RATIONAL_EVAL_ORDER_NV() {
        return (int)34519L;
    }
    public static int GL_NV_explicit_multisample() {
        return (int)1L;
    }
    public static int GL_SAMPLE_POSITION_NV() {
        return (int)36432L;
    }
    public static int GL_SAMPLE_MASK_NV() {
        return (int)36433L;
    }
    public static int GL_SAMPLE_MASK_VALUE_NV() {
        return (int)36434L;
    }
    public static int GL_TEXTURE_BINDING_RENDERBUFFER_NV() {
        return (int)36435L;
    }
    public static int GL_TEXTURE_RENDERBUFFER_DATA_STORE_BINDING_NV() {
        return (int)36436L;
    }
    public static int GL_TEXTURE_RENDERBUFFER_NV() {
        return (int)36437L;
    }
    public static int GL_SAMPLER_RENDERBUFFER_NV() {
        return (int)36438L;
    }
    public static int GL_INT_SAMPLER_RENDERBUFFER_NV() {
        return (int)36439L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_RENDERBUFFER_NV() {
        return (int)36440L;
    }
    public static int GL_MAX_SAMPLE_MASK_WORDS_NV() {
        return (int)36441L;
    }
    public static int GL_NV_fence() {
        return (int)1L;
    }
    public static int GL_ALL_COMPLETED_NV() {
        return (int)34034L;
    }
    public static int GL_FENCE_STATUS_NV() {
        return (int)34035L;
    }
    public static int GL_FENCE_CONDITION_NV() {
        return (int)34036L;
    }
    public static int GL_NV_fill_rectangle() {
        return (int)1L;
    }
    public static int GL_FILL_RECTANGLE_NV() {
        return (int)37692L;
    }
    public static int GL_NV_float_buffer() {
        return (int)1L;
    }
    public static int GL_FLOAT_R_NV() {
        return (int)34944L;
    }
    public static int GL_FLOAT_RG_NV() {
        return (int)34945L;
    }
    public static int GL_FLOAT_RGB_NV() {
        return (int)34946L;
    }
    public static int GL_FLOAT_RGBA_NV() {
        return (int)34947L;
    }
    public static int GL_FLOAT_R16_NV() {
        return (int)34948L;
    }
    public static int GL_FLOAT_R32_NV() {
        return (int)34949L;
    }
    public static int GL_FLOAT_RG16_NV() {
        return (int)34950L;
    }
    public static int GL_FLOAT_RG32_NV() {
        return (int)34951L;
    }
    public static int GL_FLOAT_RGB16_NV() {
        return (int)34952L;
    }
    public static int GL_FLOAT_RGB32_NV() {
        return (int)34953L;
    }
    public static int GL_FLOAT_RGBA16_NV() {
        return (int)34954L;
    }
    public static int GL_FLOAT_RGBA32_NV() {
        return (int)34955L;
    }
    public static int GL_TEXTURE_FLOAT_COMPONENTS_NV() {
        return (int)34956L;
    }
    public static int GL_FLOAT_CLEAR_COLOR_VALUE_NV() {
        return (int)34957L;
    }
    public static int GL_FLOAT_RGBA_MODE_NV() {
        return (int)34958L;
    }
    public static int GL_NV_fog_distance() {
        return (int)1L;
    }
    public static int GL_FOG_DISTANCE_MODE_NV() {
        return (int)34138L;
    }
    public static int GL_EYE_RADIAL_NV() {
        return (int)34139L;
    }
    public static int GL_EYE_PLANE_ABSOLUTE_NV() {
        return (int)34140L;
    }
    public static int GL_NV_fragment_coverage_to_color() {
        return (int)1L;
    }
    public static int GL_FRAGMENT_COVERAGE_TO_COLOR_NV() {
        return (int)37597L;
    }
    public static int GL_FRAGMENT_COVERAGE_COLOR_NV() {
        return (int)37598L;
    }
    public static int GL_NV_fragment_program() {
        return (int)1L;
    }
    public static int GL_MAX_FRAGMENT_PROGRAM_LOCAL_PARAMETERS_NV() {
        return (int)34920L;
    }
    public static int GL_FRAGMENT_PROGRAM_NV() {
        return (int)34928L;
    }
    public static int GL_MAX_TEXTURE_COORDS_NV() {
        return (int)34929L;
    }
    public static int GL_MAX_TEXTURE_IMAGE_UNITS_NV() {
        return (int)34930L;
    }
    public static int GL_FRAGMENT_PROGRAM_BINDING_NV() {
        return (int)34931L;
    }
    public static int GL_PROGRAM_ERROR_STRING_NV() {
        return (int)34932L;
    }
    public static int GL_NV_fragment_program2() {
        return (int)1L;
    }
    public static int GL_MAX_PROGRAM_EXEC_INSTRUCTIONS_NV() {
        return (int)35060L;
    }
    public static int GL_MAX_PROGRAM_CALL_DEPTH_NV() {
        return (int)35061L;
    }
    public static int GL_MAX_PROGRAM_IF_DEPTH_NV() {
        return (int)35062L;
    }
    public static int GL_MAX_PROGRAM_LOOP_DEPTH_NV() {
        return (int)35063L;
    }
    public static int GL_MAX_PROGRAM_LOOP_COUNT_NV() {
        return (int)35064L;
    }
    public static int GL_NV_fragment_program4() {
        return (int)1L;
    }
    public static int GL_NV_fragment_program_option() {
        return (int)1L;
    }
    public static int GL_NV_fragment_shader_interlock() {
        return (int)1L;
    }
    public static int GL_NV_framebuffer_mixed_samples() {
        return (int)1L;
    }
    public static int GL_COVERAGE_MODULATION_TABLE_NV() {
        return (int)37681L;
    }
    public static int GL_COLOR_SAMPLES_NV() {
        return (int)36384L;
    }
    public static int GL_DEPTH_SAMPLES_NV() {
        return (int)37677L;
    }
    public static int GL_STENCIL_SAMPLES_NV() {
        return (int)37678L;
    }
    public static int GL_MIXED_DEPTH_SAMPLES_SUPPORTED_NV() {
        return (int)37679L;
    }
    public static int GL_MIXED_STENCIL_SAMPLES_SUPPORTED_NV() {
        return (int)37680L;
    }
    public static int GL_COVERAGE_MODULATION_NV() {
        return (int)37682L;
    }
    public static int GL_COVERAGE_MODULATION_TABLE_SIZE_NV() {
        return (int)37683L;
    }
    public static int GL_NV_framebuffer_multisample_coverage() {
        return (int)1L;
    }
    public static int GL_RENDERBUFFER_COVERAGE_SAMPLES_NV() {
        return (int)36011L;
    }
    public static int GL_RENDERBUFFER_COLOR_SAMPLES_NV() {
        return (int)36368L;
    }
    public static int GL_MAX_MULTISAMPLE_COVERAGE_MODES_NV() {
        return (int)36369L;
    }
    public static int GL_MULTISAMPLE_COVERAGE_MODES_NV() {
        return (int)36370L;
    }
    public static int GL_NV_geometry_program4() {
        return (int)1L;
    }
    public static int GL_GEOMETRY_PROGRAM_NV() {
        return (int)35878L;
    }
    public static int GL_MAX_PROGRAM_OUTPUT_VERTICES_NV() {
        return (int)35879L;
    }
    public static int GL_MAX_PROGRAM_TOTAL_OUTPUT_COMPONENTS_NV() {
        return (int)35880L;
    }
    public static int GL_NV_geometry_shader4() {
        return (int)1L;
    }
    public static int GL_NV_geometry_shader_passthrough() {
        return (int)1L;
    }
    public static int GL_NV_gpu_multicast() {
        return (int)1L;
    }
    public static int GL_PER_GPU_STORAGE_BIT_NV() {
        return (int)2048L;
    }
    public static int GL_MULTICAST_GPUS_NV() {
        return (int)37562L;
    }
    public static int GL_RENDER_GPU_MASK_NV() {
        return (int)38232L;
    }
    public static int GL_PER_GPU_STORAGE_NV() {
        return (int)38216L;
    }
    public static int GL_MULTICAST_PROGRAMMABLE_SAMPLE_LOCATION_NV() {
        return (int)38217L;
    }
    public static int GL_NV_gpu_program4() {
        return (int)1L;
    }
    public static int GL_MIN_PROGRAM_TEXEL_OFFSET_NV() {
        return (int)35076L;
    }
    public static int GL_MAX_PROGRAM_TEXEL_OFFSET_NV() {
        return (int)35077L;
    }
    public static int GL_PROGRAM_ATTRIB_COMPONENTS_NV() {
        return (int)35078L;
    }
    public static int GL_PROGRAM_RESULT_COMPONENTS_NV() {
        return (int)35079L;
    }
    public static int GL_MAX_PROGRAM_ATTRIB_COMPONENTS_NV() {
        return (int)35080L;
    }
    public static int GL_MAX_PROGRAM_RESULT_COMPONENTS_NV() {
        return (int)35081L;
    }
    public static int GL_MAX_PROGRAM_GENERIC_ATTRIBS_NV() {
        return (int)36261L;
    }
    public static int GL_MAX_PROGRAM_GENERIC_RESULTS_NV() {
        return (int)36262L;
    }
    public static int GL_NV_gpu_program5() {
        return (int)1L;
    }
    public static int GL_MAX_GEOMETRY_PROGRAM_INVOCATIONS_NV() {
        return (int)36442L;
    }
    public static int GL_MIN_FRAGMENT_INTERPOLATION_OFFSET_NV() {
        return (int)36443L;
    }
    public static int GL_MAX_FRAGMENT_INTERPOLATION_OFFSET_NV() {
        return (int)36444L;
    }
    public static int GL_FRAGMENT_PROGRAM_INTERPOLATION_OFFSET_BITS_NV() {
        return (int)36445L;
    }
    public static int GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_NV() {
        return (int)36446L;
    }
    public static int GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_NV() {
        return (int)36447L;
    }
    public static int GL_MAX_PROGRAM_SUBROUTINE_PARAMETERS_NV() {
        return (int)36676L;
    }
    public static int GL_MAX_PROGRAM_SUBROUTINE_NUM_NV() {
        return (int)36677L;
    }
    public static int GL_NV_gpu_program5_mem_extended() {
        return (int)1L;
    }
    public static int GL_NV_gpu_shader5() {
        return (int)1L;
    }
    public static int GL_NV_half_float() {
        return (int)1L;
    }
    public static int GL_HALF_FLOAT_NV() {
        return (int)5131L;
    }
    public static int GL_NV_internalformat_sample_query() {
        return (int)1L;
    }
    public static int GL_MULTISAMPLES_NV() {
        return (int)37745L;
    }
    public static int GL_SUPERSAMPLE_SCALE_X_NV() {
        return (int)37746L;
    }
    public static int GL_SUPERSAMPLE_SCALE_Y_NV() {
        return (int)37747L;
    }
    public static int GL_CONFORMANT_NV() {
        return (int)37748L;
    }
    public static int GL_NV_light_max_exponent() {
        return (int)1L;
    }
    public static int GL_MAX_SHININESS_NV() {
        return (int)34052L;
    }
    public static int GL_MAX_SPOT_EXPONENT_NV() {
        return (int)34053L;
    }
    public static int GL_NV_multisample_coverage() {
        return (int)1L;
    }
    public static int GL_NV_multisample_filter_hint() {
        return (int)1L;
    }
    public static int GL_MULTISAMPLE_FILTER_HINT_NV() {
        return (int)34100L;
    }
    public static int GL_NV_occlusion_query() {
        return (int)1L;
    }
    public static int GL_PIXEL_COUNTER_BITS_NV() {
        return (int)34916L;
    }
    public static int GL_CURRENT_OCCLUSION_QUERY_ID_NV() {
        return (int)34917L;
    }
    public static int GL_PIXEL_COUNT_NV() {
        return (int)34918L;
    }
    public static int GL_PIXEL_COUNT_AVAILABLE_NV() {
        return (int)34919L;
    }
    public static int GL_NV_packed_depth_stencil() {
        return (int)1L;
    }
    public static int GL_DEPTH_STENCIL_NV() {
        return (int)34041L;
    }
    public static int GL_UNSIGNED_INT_24_8_NV() {
        return (int)34042L;
    }
    public static int GL_NV_parameter_buffer_object() {
        return (int)1L;
    }
    public static int GL_MAX_PROGRAM_PARAMETER_BUFFER_BINDINGS_NV() {
        return (int)36256L;
    }
    public static int GL_MAX_PROGRAM_PARAMETER_BUFFER_SIZE_NV() {
        return (int)36257L;
    }
    public static int GL_VERTEX_PROGRAM_PARAMETER_BUFFER_NV() {
        return (int)36258L;
    }
    public static int GL_GEOMETRY_PROGRAM_PARAMETER_BUFFER_NV() {
        return (int)36259L;
    }
    public static int GL_FRAGMENT_PROGRAM_PARAMETER_BUFFER_NV() {
        return (int)36260L;
    }
    public static int GL_NV_parameter_buffer_object2() {
        return (int)1L;
    }
    public static int GL_NV_path_rendering() {
        return (int)1L;
    }
    public static int GL_PATH_FORMAT_SVG_NV() {
        return (int)36976L;
    }
    public static int GL_PATH_FORMAT_PS_NV() {
        return (int)36977L;
    }
    public static int GL_STANDARD_FONT_NAME_NV() {
        return (int)36978L;
    }
    public static int GL_SYSTEM_FONT_NAME_NV() {
        return (int)36979L;
    }
    public static int GL_FILE_NAME_NV() {
        return (int)36980L;
    }
    public static int GL_PATH_STROKE_WIDTH_NV() {
        return (int)36981L;
    }
    public static int GL_PATH_END_CAPS_NV() {
        return (int)36982L;
    }
    public static int GL_PATH_INITIAL_END_CAP_NV() {
        return (int)36983L;
    }
    public static int GL_PATH_TERMINAL_END_CAP_NV() {
        return (int)36984L;
    }
    public static int GL_PATH_JOIN_STYLE_NV() {
        return (int)36985L;
    }
    public static int GL_PATH_MITER_LIMIT_NV() {
        return (int)36986L;
    }
    public static int GL_PATH_DASH_CAPS_NV() {
        return (int)36987L;
    }
    public static int GL_PATH_INITIAL_DASH_CAP_NV() {
        return (int)36988L;
    }
    public static int GL_PATH_TERMINAL_DASH_CAP_NV() {
        return (int)36989L;
    }
    public static int GL_PATH_DASH_OFFSET_NV() {
        return (int)36990L;
    }
    public static int GL_PATH_CLIENT_LENGTH_NV() {
        return (int)36991L;
    }
    public static int GL_PATH_FILL_MODE_NV() {
        return (int)36992L;
    }
    public static int GL_PATH_FILL_MASK_NV() {
        return (int)36993L;
    }
    public static int GL_PATH_FILL_COVER_MODE_NV() {
        return (int)36994L;
    }
    public static int GL_PATH_STROKE_COVER_MODE_NV() {
        return (int)36995L;
    }
    public static int GL_PATH_STROKE_MASK_NV() {
        return (int)36996L;
    }
    public static int GL_COUNT_UP_NV() {
        return (int)37000L;
    }
    public static int GL_COUNT_DOWN_NV() {
        return (int)37001L;
    }
    public static int GL_PATH_OBJECT_BOUNDING_BOX_NV() {
        return (int)37002L;
    }
    public static int GL_CONVEX_HULL_NV() {
        return (int)37003L;
    }
    public static int GL_BOUNDING_BOX_NV() {
        return (int)37005L;
    }
    public static int GL_TRANSLATE_X_NV() {
        return (int)37006L;
    }
    public static int GL_TRANSLATE_Y_NV() {
        return (int)37007L;
    }
    public static int GL_TRANSLATE_2D_NV() {
        return (int)37008L;
    }
    public static int GL_TRANSLATE_3D_NV() {
        return (int)37009L;
    }
    public static int GL_AFFINE_2D_NV() {
        return (int)37010L;
    }
    public static int GL_AFFINE_3D_NV() {
        return (int)37012L;
    }
    public static int GL_TRANSPOSE_AFFINE_2D_NV() {
        return (int)37014L;
    }
    public static int GL_TRANSPOSE_AFFINE_3D_NV() {
        return (int)37016L;
    }
    public static int GL_UTF8_NV() {
        return (int)37018L;
    }
    public static int GL_UTF16_NV() {
        return (int)37019L;
    }
    public static int GL_BOUNDING_BOX_OF_BOUNDING_BOXES_NV() {
        return (int)37020L;
    }
    public static int GL_PATH_COMMAND_COUNT_NV() {
        return (int)37021L;
    }
    public static int GL_PATH_COORD_COUNT_NV() {
        return (int)37022L;
    }
    public static int GL_PATH_DASH_ARRAY_COUNT_NV() {
        return (int)37023L;
    }
    public static int GL_PATH_COMPUTED_LENGTH_NV() {
        return (int)37024L;
    }
    public static int GL_PATH_FILL_BOUNDING_BOX_NV() {
        return (int)37025L;
    }
    public static int GL_PATH_STROKE_BOUNDING_BOX_NV() {
        return (int)37026L;
    }
    public static int GL_SQUARE_NV() {
        return (int)37027L;
    }
    public static int GL_ROUND_NV() {
        return (int)37028L;
    }
    public static int GL_TRIANGULAR_NV() {
        return (int)37029L;
    }
    public static int GL_BEVEL_NV() {
        return (int)37030L;
    }
    public static int GL_MITER_REVERT_NV() {
        return (int)37031L;
    }
    public static int GL_MITER_TRUNCATE_NV() {
        return (int)37032L;
    }
    public static int GL_SKIP_MISSING_GLYPH_NV() {
        return (int)37033L;
    }
    public static int GL_USE_MISSING_GLYPH_NV() {
        return (int)37034L;
    }
    public static int GL_PATH_ERROR_POSITION_NV() {
        return (int)37035L;
    }
    public static int GL_ACCUM_ADJACENT_PAIRS_NV() {
        return (int)37037L;
    }
    public static int GL_ADJACENT_PAIRS_NV() {
        return (int)37038L;
    }
    public static int GL_FIRST_TO_REST_NV() {
        return (int)37039L;
    }
    public static int GL_PATH_GEN_MODE_NV() {
        return (int)37040L;
    }
    public static int GL_PATH_GEN_COEFF_NV() {
        return (int)37041L;
    }
    public static int GL_PATH_GEN_COMPONENTS_NV() {
        return (int)37043L;
    }
    public static int GL_PATH_STENCIL_FUNC_NV() {
        return (int)37047L;
    }
    public static int GL_PATH_STENCIL_REF_NV() {
        return (int)37048L;
    }
    public static int GL_PATH_STENCIL_VALUE_MASK_NV() {
        return (int)37049L;
    }
    public static int GL_PATH_STENCIL_DEPTH_OFFSET_FACTOR_NV() {
        return (int)37053L;
    }
    public static int GL_PATH_STENCIL_DEPTH_OFFSET_UNITS_NV() {
        return (int)37054L;
    }
    public static int GL_PATH_COVER_DEPTH_FUNC_NV() {
        return (int)37055L;
    }
    public static int GL_PATH_DASH_OFFSET_RESET_NV() {
        return (int)37044L;
    }
    public static int GL_MOVE_TO_RESETS_NV() {
        return (int)37045L;
    }
    public static int GL_MOVE_TO_CONTINUES_NV() {
        return (int)37046L;
    }
    public static int GL_CLOSE_PATH_NV() {
        return (int)0L;
    }
    public static int GL_MOVE_TO_NV() {
        return (int)2L;
    }
    public static int GL_RELATIVE_MOVE_TO_NV() {
        return (int)3L;
    }
    public static int GL_LINE_TO_NV() {
        return (int)4L;
    }
    public static int GL_RELATIVE_LINE_TO_NV() {
        return (int)5L;
    }
    public static int GL_HORIZONTAL_LINE_TO_NV() {
        return (int)6L;
    }
    public static int GL_RELATIVE_HORIZONTAL_LINE_TO_NV() {
        return (int)7L;
    }
    public static int GL_VERTICAL_LINE_TO_NV() {
        return (int)8L;
    }
    public static int GL_RELATIVE_VERTICAL_LINE_TO_NV() {
        return (int)9L;
    }
    public static int GL_QUADRATIC_CURVE_TO_NV() {
        return (int)10L;
    }
    public static int GL_RELATIVE_QUADRATIC_CURVE_TO_NV() {
        return (int)11L;
    }
    public static int GL_CUBIC_CURVE_TO_NV() {
        return (int)12L;
    }
    public static int GL_RELATIVE_CUBIC_CURVE_TO_NV() {
        return (int)13L;
    }
    public static int GL_SMOOTH_QUADRATIC_CURVE_TO_NV() {
        return (int)14L;
    }
    public static int GL_RELATIVE_SMOOTH_QUADRATIC_CURVE_TO_NV() {
        return (int)15L;
    }
    public static int GL_SMOOTH_CUBIC_CURVE_TO_NV() {
        return (int)16L;
    }
    public static int GL_RELATIVE_SMOOTH_CUBIC_CURVE_TO_NV() {
        return (int)17L;
    }
    public static int GL_SMALL_CCW_ARC_TO_NV() {
        return (int)18L;
    }
    public static int GL_RELATIVE_SMALL_CCW_ARC_TO_NV() {
        return (int)19L;
    }
    public static int GL_SMALL_CW_ARC_TO_NV() {
        return (int)20L;
    }
    public static int GL_RELATIVE_SMALL_CW_ARC_TO_NV() {
        return (int)21L;
    }
    public static int GL_LARGE_CCW_ARC_TO_NV() {
        return (int)22L;
    }
    public static int GL_RELATIVE_LARGE_CCW_ARC_TO_NV() {
        return (int)23L;
    }
    public static int GL_LARGE_CW_ARC_TO_NV() {
        return (int)24L;
    }
    public static int GL_RELATIVE_LARGE_CW_ARC_TO_NV() {
        return (int)25L;
    }
    public static int GL_RESTART_PATH_NV() {
        return (int)240L;
    }
    public static int GL_DUP_FIRST_CUBIC_CURVE_TO_NV() {
        return (int)242L;
    }
    public static int GL_DUP_LAST_CUBIC_CURVE_TO_NV() {
        return (int)244L;
    }
    public static int GL_RECT_NV() {
        return (int)246L;
    }
    public static int GL_CIRCULAR_CCW_ARC_TO_NV() {
        return (int)248L;
    }
    public static int GL_CIRCULAR_CW_ARC_TO_NV() {
        return (int)250L;
    }
    public static int GL_CIRCULAR_TANGENT_ARC_TO_NV() {
        return (int)252L;
    }
    public static int GL_ARC_TO_NV() {
        return (int)254L;
    }
    public static int GL_RELATIVE_ARC_TO_NV() {
        return (int)255L;
    }
    public static int GL_BOLD_BIT_NV() {
        return (int)1L;
    }
    public static int GL_ITALIC_BIT_NV() {
        return (int)2L;
    }
    public static int GL_GLYPH_WIDTH_BIT_NV() {
        return (int)1L;
    }
    public static int GL_GLYPH_HEIGHT_BIT_NV() {
        return (int)2L;
    }
    public static int GL_GLYPH_HORIZONTAL_BEARING_X_BIT_NV() {
        return (int)4L;
    }
    public static int GL_GLYPH_HORIZONTAL_BEARING_Y_BIT_NV() {
        return (int)8L;
    }
    public static int GL_GLYPH_HORIZONTAL_BEARING_ADVANCE_BIT_NV() {
        return (int)16L;
    }
    public static int GL_GLYPH_VERTICAL_BEARING_X_BIT_NV() {
        return (int)32L;
    }
    public static int GL_GLYPH_VERTICAL_BEARING_Y_BIT_NV() {
        return (int)64L;
    }
    public static int GL_GLYPH_VERTICAL_BEARING_ADVANCE_BIT_NV() {
        return (int)128L;
    }
    public static int GL_GLYPH_HAS_KERNING_BIT_NV() {
        return (int)256L;
    }
    public static int GL_FONT_X_MIN_BOUNDS_BIT_NV() {
        return (int)65536L;
    }
    public static int GL_FONT_Y_MIN_BOUNDS_BIT_NV() {
        return (int)131072L;
    }
    public static int GL_FONT_X_MAX_BOUNDS_BIT_NV() {
        return (int)262144L;
    }
    public static int GL_FONT_Y_MAX_BOUNDS_BIT_NV() {
        return (int)524288L;
    }
    public static int GL_FONT_UNITS_PER_EM_BIT_NV() {
        return (int)1048576L;
    }
    public static int GL_FONT_ASCENDER_BIT_NV() {
        return (int)2097152L;
    }
    public static int GL_FONT_DESCENDER_BIT_NV() {
        return (int)4194304L;
    }
    public static int GL_FONT_HEIGHT_BIT_NV() {
        return (int)8388608L;
    }
    public static int GL_FONT_MAX_ADVANCE_WIDTH_BIT_NV() {
        return (int)16777216L;
    }
    public static int GL_FONT_MAX_ADVANCE_HEIGHT_BIT_NV() {
        return (int)33554432L;
    }
    public static int GL_FONT_UNDERLINE_POSITION_BIT_NV() {
        return (int)67108864L;
    }
    public static int GL_FONT_UNDERLINE_THICKNESS_BIT_NV() {
        return (int)134217728L;
    }
    public static int GL_FONT_HAS_KERNING_BIT_NV() {
        return (int)268435456L;
    }
    public static int GL_ROUNDED_RECT_NV() {
        return (int)232L;
    }
    public static int GL_RELATIVE_ROUNDED_RECT_NV() {
        return (int)233L;
    }
    public static int GL_ROUNDED_RECT2_NV() {
        return (int)234L;
    }
    public static int GL_RELATIVE_ROUNDED_RECT2_NV() {
        return (int)235L;
    }
    public static int GL_ROUNDED_RECT4_NV() {
        return (int)236L;
    }
    public static int GL_RELATIVE_ROUNDED_RECT4_NV() {
        return (int)237L;
    }
    public static int GL_ROUNDED_RECT8_NV() {
        return (int)238L;
    }
    public static int GL_RELATIVE_ROUNDED_RECT8_NV() {
        return (int)239L;
    }
    public static int GL_RELATIVE_RECT_NV() {
        return (int)247L;
    }
    public static int GL_FONT_GLYPHS_AVAILABLE_NV() {
        return (int)37736L;
    }
    public static int GL_FONT_TARGET_UNAVAILABLE_NV() {
        return (int)37737L;
    }
    public static int GL_FONT_UNAVAILABLE_NV() {
        return (int)37738L;
    }
    public static int GL_FONT_UNINTELLIGIBLE_NV() {
        return (int)37739L;
    }
    public static int GL_CONIC_CURVE_TO_NV() {
        return (int)26L;
    }
    public static int GL_RELATIVE_CONIC_CURVE_TO_NV() {
        return (int)27L;
    }
    public static int GL_FONT_NUM_GLYPH_INDICES_BIT_NV() {
        return (int)536870912L;
    }
    public static int GL_STANDARD_FONT_FORMAT_NV() {
        return (int)37740L;
    }
    public static int GL_2_BYTES_NV() {
        return (int)5127L;
    }
    public static int GL_3_BYTES_NV() {
        return (int)5128L;
    }
    public static int GL_4_BYTES_NV() {
        return (int)5129L;
    }
    public static int GL_EYE_LINEAR_NV() {
        return (int)9216L;
    }
    public static int GL_OBJECT_LINEAR_NV() {
        return (int)9217L;
    }
    public static int GL_CONSTANT_NV() {
        return (int)34166L;
    }
    public static int GL_PATH_FOG_GEN_MODE_NV() {
        return (int)37036L;
    }
    public static int GL_PRIMARY_COLOR_NV() {
        return (int)34092L;
    }
    public static int GL_SECONDARY_COLOR_NV() {
        return (int)34093L;
    }
    public static int GL_PATH_GEN_COLOR_FORMAT_NV() {
        return (int)37042L;
    }
    public static int GL_PATH_PROJECTION_NV() {
        return (int)5889L;
    }
    public static int GL_PATH_MODELVIEW_NV() {
        return (int)5888L;
    }
    public static int GL_PATH_MODELVIEW_STACK_DEPTH_NV() {
        return (int)2979L;
    }
    public static int GL_PATH_MODELVIEW_MATRIX_NV() {
        return (int)2982L;
    }
    public static int GL_PATH_MAX_MODELVIEW_STACK_DEPTH_NV() {
        return (int)3382L;
    }
    public static int GL_PATH_TRANSPOSE_MODELVIEW_MATRIX_NV() {
        return (int)34019L;
    }
    public static int GL_PATH_PROJECTION_STACK_DEPTH_NV() {
        return (int)2980L;
    }
    public static int GL_PATH_PROJECTION_MATRIX_NV() {
        return (int)2983L;
    }
    public static int GL_PATH_MAX_PROJECTION_STACK_DEPTH_NV() {
        return (int)3384L;
    }
    public static int GL_PATH_TRANSPOSE_PROJECTION_MATRIX_NV() {
        return (int)34020L;
    }
    public static int GL_FRAGMENT_INPUT_NV() {
        return (int)37741L;
    }
    public static int GL_NV_path_rendering_shared_edge() {
        return (int)1L;
    }
    public static int GL_SHARED_EDGE_NV() {
        return (int)192L;
    }
    public static int GL_NV_pixel_data_range() {
        return (int)1L;
    }
    public static int GL_WRITE_PIXEL_DATA_RANGE_NV() {
        return (int)34936L;
    }
    public static int GL_READ_PIXEL_DATA_RANGE_NV() {
        return (int)34937L;
    }
    public static int GL_WRITE_PIXEL_DATA_RANGE_LENGTH_NV() {
        return (int)34938L;
    }
    public static int GL_READ_PIXEL_DATA_RANGE_LENGTH_NV() {
        return (int)34939L;
    }
    public static int GL_WRITE_PIXEL_DATA_RANGE_POINTER_NV() {
        return (int)34940L;
    }
    public static int GL_READ_PIXEL_DATA_RANGE_POINTER_NV() {
        return (int)34941L;
    }
    public static int GL_NV_point_sprite() {
        return (int)1L;
    }
    public static int GL_POINT_SPRITE_NV() {
        return (int)34913L;
    }
    public static int GL_COORD_REPLACE_NV() {
        return (int)34914L;
    }
    public static int GL_POINT_SPRITE_R_MODE_NV() {
        return (int)34915L;
    }
    public static int GL_NV_present_video() {
        return (int)1L;
    }
    public static int GL_FRAME_NV() {
        return (int)36390L;
    }
    public static int GL_FIELDS_NV() {
        return (int)36391L;
    }
    public static int GL_CURRENT_TIME_NV() {
        return (int)36392L;
    }
    public static int GL_NUM_FILL_STREAMS_NV() {
        return (int)36393L;
    }
    public static int GL_PRESENT_TIME_NV() {
        return (int)36394L;
    }
    public static int GL_PRESENT_DURATION_NV() {
        return (int)36395L;
    }
    public static int GL_NV_primitive_restart() {
        return (int)1L;
    }
    public static int GL_PRIMITIVE_RESTART_NV() {
        return (int)34136L;
    }
    public static int GL_PRIMITIVE_RESTART_INDEX_NV() {
        return (int)34137L;
    }
    public static int GL_NV_query_resource() {
        return (int)1L;
    }
    public static int GL_QUERY_RESOURCE_TYPE_VIDMEM_ALLOC_NV() {
        return (int)38208L;
    }
    public static int GL_QUERY_RESOURCE_MEMTYPE_VIDMEM_NV() {
        return (int)38210L;
    }
    public static int GL_QUERY_RESOURCE_SYS_RESERVED_NV() {
        return (int)38212L;
    }
    public static int GL_QUERY_RESOURCE_TEXTURE_NV() {
        return (int)38213L;
    }
    public static int GL_QUERY_RESOURCE_RENDERBUFFER_NV() {
        return (int)38214L;
    }
    public static int GL_QUERY_RESOURCE_BUFFEROBJECT_NV() {
        return (int)38215L;
    }
    public static int GL_NV_query_resource_tag() {
        return (int)1L;
    }
    public static int GL_NV_register_combiners() {
        return (int)1L;
    }
    public static int GL_REGISTER_COMBINERS_NV() {
        return (int)34082L;
    }
    public static int GL_VARIABLE_A_NV() {
        return (int)34083L;
    }
    public static int GL_VARIABLE_B_NV() {
        return (int)34084L;
    }
    public static int GL_VARIABLE_C_NV() {
        return (int)34085L;
    }
    public static int GL_VARIABLE_D_NV() {
        return (int)34086L;
    }
    public static int GL_VARIABLE_E_NV() {
        return (int)34087L;
    }
    public static int GL_VARIABLE_F_NV() {
        return (int)34088L;
    }
    public static int GL_VARIABLE_G_NV() {
        return (int)34089L;
    }
    public static int GL_CONSTANT_COLOR0_NV() {
        return (int)34090L;
    }
    public static int GL_CONSTANT_COLOR1_NV() {
        return (int)34091L;
    }
    public static int GL_SPARE0_NV() {
        return (int)34094L;
    }
    public static int GL_SPARE1_NV() {
        return (int)34095L;
    }
    public static int GL_DISCARD_NV() {
        return (int)34096L;
    }
    public static int GL_E_TIMES_F_NV() {
        return (int)34097L;
    }
    public static int GL_SPARE0_PLUS_SECONDARY_COLOR_NV() {
        return (int)34098L;
    }
    public static int GL_UNSIGNED_IDENTITY_NV() {
        return (int)34102L;
    }
    public static int GL_UNSIGNED_INVERT_NV() {
        return (int)34103L;
    }
    public static int GL_EXPAND_NORMAL_NV() {
        return (int)34104L;
    }
    public static int GL_EXPAND_NEGATE_NV() {
        return (int)34105L;
    }
    public static int GL_HALF_BIAS_NORMAL_NV() {
        return (int)34106L;
    }
    public static int GL_HALF_BIAS_NEGATE_NV() {
        return (int)34107L;
    }
    public static int GL_SIGNED_IDENTITY_NV() {
        return (int)34108L;
    }
    public static int GL_SIGNED_NEGATE_NV() {
        return (int)34109L;
    }
    public static int GL_SCALE_BY_TWO_NV() {
        return (int)34110L;
    }
    public static int GL_SCALE_BY_FOUR_NV() {
        return (int)34111L;
    }
    public static int GL_SCALE_BY_ONE_HALF_NV() {
        return (int)34112L;
    }
    public static int GL_BIAS_BY_NEGATIVE_ONE_HALF_NV() {
        return (int)34113L;
    }
    public static int GL_COMBINER_INPUT_NV() {
        return (int)34114L;
    }
    public static int GL_COMBINER_MAPPING_NV() {
        return (int)34115L;
    }
    public static int GL_COMBINER_COMPONENT_USAGE_NV() {
        return (int)34116L;
    }
    public static int GL_COMBINER_AB_DOT_PRODUCT_NV() {
        return (int)34117L;
    }
    public static int GL_COMBINER_CD_DOT_PRODUCT_NV() {
        return (int)34118L;
    }
    public static int GL_COMBINER_MUX_SUM_NV() {
        return (int)34119L;
    }
    public static int GL_COMBINER_SCALE_NV() {
        return (int)34120L;
    }
    public static int GL_COMBINER_BIAS_NV() {
        return (int)34121L;
    }
    public static int GL_COMBINER_AB_OUTPUT_NV() {
        return (int)34122L;
    }
    public static int GL_COMBINER_CD_OUTPUT_NV() {
        return (int)34123L;
    }
    public static int GL_COMBINER_SUM_OUTPUT_NV() {
        return (int)34124L;
    }
    public static int GL_MAX_GENERAL_COMBINERS_NV() {
        return (int)34125L;
    }
    public static int GL_NUM_GENERAL_COMBINERS_NV() {
        return (int)34126L;
    }
    public static int GL_COLOR_SUM_CLAMP_NV() {
        return (int)34127L;
    }
    public static int GL_COMBINER0_NV() {
        return (int)34128L;
    }
    public static int GL_COMBINER1_NV() {
        return (int)34129L;
    }
    public static int GL_COMBINER2_NV() {
        return (int)34130L;
    }
    public static int GL_COMBINER3_NV() {
        return (int)34131L;
    }
    public static int GL_COMBINER4_NV() {
        return (int)34132L;
    }
    public static int GL_COMBINER5_NV() {
        return (int)34133L;
    }
    public static int GL_COMBINER6_NV() {
        return (int)34134L;
    }
    public static int GL_COMBINER7_NV() {
        return (int)34135L;
    }
    public static int GL_NV_register_combiners2() {
        return (int)1L;
    }
    public static int GL_PER_STAGE_CONSTANTS_NV() {
        return (int)34101L;
    }
    public static int GL_NV_robustness_video_memory_purge() {
        return (int)1L;
    }
    public static int GL_PURGED_CONTEXT_RESET_NV() {
        return (int)37563L;
    }
    public static int GL_NV_sample_locations() {
        return (int)1L;
    }
    public static int GL_SAMPLE_LOCATION_SUBPIXEL_BITS_NV() {
        return (int)37693L;
    }
    public static int GL_SAMPLE_LOCATION_PIXEL_GRID_WIDTH_NV() {
        return (int)37694L;
    }
    public static int GL_SAMPLE_LOCATION_PIXEL_GRID_HEIGHT_NV() {
        return (int)37695L;
    }
    public static int GL_PROGRAMMABLE_SAMPLE_LOCATION_TABLE_SIZE_NV() {
        return (int)37696L;
    }
    public static int GL_SAMPLE_LOCATION_NV() {
        return (int)36432L;
    }
    public static int GL_PROGRAMMABLE_SAMPLE_LOCATION_NV() {
        return (int)37697L;
    }
    public static int GL_FRAMEBUFFER_PROGRAMMABLE_SAMPLE_LOCATIONS_NV() {
        return (int)37698L;
    }
    public static int GL_FRAMEBUFFER_SAMPLE_LOCATION_PIXEL_GRID_NV() {
        return (int)37699L;
    }
    public static int GL_NV_sample_mask_override_coverage() {
        return (int)1L;
    }
    public static int GL_NV_shader_atomic_counters() {
        return (int)1L;
    }
    public static int GL_NV_shader_atomic_float() {
        return (int)1L;
    }
    public static int GL_NV_shader_atomic_float64() {
        return (int)1L;
    }
    public static int GL_NV_shader_atomic_fp16_vector() {
        return (int)1L;
    }
    public static int GL_NV_shader_atomic_int64() {
        return (int)1L;
    }
    public static int GL_NV_shader_buffer_load() {
        return (int)1L;
    }
    public static int GL_BUFFER_GPU_ADDRESS_NV() {
        return (int)36637L;
    }
    public static int GL_GPU_ADDRESS_NV() {
        return (int)36660L;
    }
    public static int GL_MAX_SHADER_BUFFER_ADDRESS_NV() {
        return (int)36661L;
    }
    public static int GL_NV_shader_buffer_store() {
        return (int)1L;
    }
    public static int GL_SHADER_GLOBAL_ACCESS_BARRIER_BIT_NV() {
        return (int)16L;
    }
    public static int GL_NV_shader_storage_buffer_object() {
        return (int)1L;
    }
    public static int GL_NV_shader_thread_group() {
        return (int)1L;
    }
    public static int GL_WARP_SIZE_NV() {
        return (int)37689L;
    }
    public static int GL_WARPS_PER_SM_NV() {
        return (int)37690L;
    }
    public static int GL_SM_COUNT_NV() {
        return (int)37691L;
    }
    public static int GL_NV_shader_thread_shuffle() {
        return (int)1L;
    }
    public static int GL_NV_stereo_view_rendering() {
        return (int)1L;
    }
    public static int GL_NV_tessellation_program5() {
        return (int)1L;
    }
    public static int GL_MAX_PROGRAM_PATCH_ATTRIBS_NV() {
        return (int)34520L;
    }
    public static int GL_TESS_CONTROL_PROGRAM_NV() {
        return (int)35102L;
    }
    public static int GL_TESS_EVALUATION_PROGRAM_NV() {
        return (int)35103L;
    }
    public static int GL_TESS_CONTROL_PROGRAM_PARAMETER_BUFFER_NV() {
        return (int)35956L;
    }
    public static int GL_TESS_EVALUATION_PROGRAM_PARAMETER_BUFFER_NV() {
        return (int)35957L;
    }
    public static int GL_NV_texgen_emboss() {
        return (int)1L;
    }
    public static int GL_EMBOSS_LIGHT_NV() {
        return (int)34141L;
    }
    public static int GL_EMBOSS_CONSTANT_NV() {
        return (int)34142L;
    }
    public static int GL_EMBOSS_MAP_NV() {
        return (int)34143L;
    }
    public static int GL_NV_texgen_reflection() {
        return (int)1L;
    }
    public static int GL_NORMAL_MAP_NV() {
        return (int)34065L;
    }
    public static int GL_REFLECTION_MAP_NV() {
        return (int)34066L;
    }
    public static int GL_NV_texture_barrier() {
        return (int)1L;
    }
    public static int GL_NV_texture_compression_vtc() {
        return (int)1L;
    }
    public static int GL_NV_texture_env_combine4() {
        return (int)1L;
    }
    public static int GL_COMBINE4_NV() {
        return (int)34051L;
    }
    public static int GL_SOURCE3_RGB_NV() {
        return (int)34179L;
    }
    public static int GL_SOURCE3_ALPHA_NV() {
        return (int)34187L;
    }
    public static int GL_OPERAND3_RGB_NV() {
        return (int)34195L;
    }
    public static int GL_OPERAND3_ALPHA_NV() {
        return (int)34203L;
    }
    public static int GL_NV_texture_expand_normal() {
        return (int)1L;
    }
    public static int GL_TEXTURE_UNSIGNED_REMAP_MODE_NV() {
        return (int)34959L;
    }
    public static int GL_NV_texture_multisample() {
        return (int)1L;
    }
    public static int GL_TEXTURE_COVERAGE_SAMPLES_NV() {
        return (int)36933L;
    }
    public static int GL_TEXTURE_COLOR_SAMPLES_NV() {
        return (int)36934L;
    }
    public static int GL_NV_texture_rectangle() {
        return (int)1L;
    }
    public static int GL_TEXTURE_RECTANGLE_NV() {
        return (int)34037L;
    }
    public static int GL_TEXTURE_BINDING_RECTANGLE_NV() {
        return (int)34038L;
    }
    public static int GL_PROXY_TEXTURE_RECTANGLE_NV() {
        return (int)34039L;
    }
    public static int GL_MAX_RECTANGLE_TEXTURE_SIZE_NV() {
        return (int)34040L;
    }
    public static int GL_NV_texture_rectangle_compressed() {
        return (int)1L;
    }
    public static int GL_NV_texture_shader() {
        return (int)1L;
    }
    public static int GL_OFFSET_TEXTURE_RECTANGLE_NV() {
        return (int)34380L;
    }
    public static int GL_OFFSET_TEXTURE_RECTANGLE_SCALE_NV() {
        return (int)34381L;
    }
    public static int GL_DOT_PRODUCT_TEXTURE_RECTANGLE_NV() {
        return (int)34382L;
    }
    public static int GL_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV() {
        return (int)34521L;
    }
    public static int GL_UNSIGNED_INT_S8_S8_8_8_NV() {
        return (int)34522L;
    }
    public static int GL_UNSIGNED_INT_8_8_S8_S8_REV_NV() {
        return (int)34523L;
    }
    public static int GL_DSDT_MAG_INTENSITY_NV() {
        return (int)34524L;
    }
    public static int GL_SHADER_CONSISTENT_NV() {
        return (int)34525L;
    }
    public static int GL_TEXTURE_SHADER_NV() {
        return (int)34526L;
    }
    public static int GL_SHADER_OPERATION_NV() {
        return (int)34527L;
    }
    public static int GL_CULL_MODES_NV() {
        return (int)34528L;
    }
    public static int GL_OFFSET_TEXTURE_MATRIX_NV() {
        return (int)34529L;
    }
    public static int GL_OFFSET_TEXTURE_SCALE_NV() {
        return (int)34530L;
    }
    public static int GL_OFFSET_TEXTURE_BIAS_NV() {
        return (int)34531L;
    }
    public static int GL_OFFSET_TEXTURE_2D_MATRIX_NV() {
        return (int)34529L;
    }
    public static int GL_OFFSET_TEXTURE_2D_SCALE_NV() {
        return (int)34530L;
    }
    public static int GL_OFFSET_TEXTURE_2D_BIAS_NV() {
        return (int)34531L;
    }
    public static int GL_PREVIOUS_TEXTURE_INPUT_NV() {
        return (int)34532L;
    }
    public static int GL_CONST_EYE_NV() {
        return (int)34533L;
    }
    public static int GL_PASS_THROUGH_NV() {
        return (int)34534L;
    }
    public static int GL_CULL_FRAGMENT_NV() {
        return (int)34535L;
    }
    public static int GL_OFFSET_TEXTURE_2D_NV() {
        return (int)34536L;
    }
    public static int GL_DEPENDENT_AR_TEXTURE_2D_NV() {
        return (int)34537L;
    }
    public static int GL_DEPENDENT_GB_TEXTURE_2D_NV() {
        return (int)34538L;
    }
    public static int GL_DOT_PRODUCT_NV() {
        return (int)34540L;
    }
    public static int GL_DOT_PRODUCT_DEPTH_REPLACE_NV() {
        return (int)34541L;
    }
    public static int GL_DOT_PRODUCT_TEXTURE_2D_NV() {
        return (int)34542L;
    }
    public static int GL_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV() {
        return (int)34544L;
    }
    public static int GL_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV() {
        return (int)34545L;
    }
    public static int GL_DOT_PRODUCT_REFLECT_CUBE_MAP_NV() {
        return (int)34546L;
    }
    public static int GL_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV() {
        return (int)34547L;
    }
    public static int GL_HILO_NV() {
        return (int)34548L;
    }
    public static int GL_DSDT_NV() {
        return (int)34549L;
    }
    public static int GL_DSDT_MAG_NV() {
        return (int)34550L;
    }
    public static int GL_DSDT_MAG_VIB_NV() {
        return (int)34551L;
    }
    public static int GL_HILO16_NV() {
        return (int)34552L;
    }
    public static int GL_SIGNED_HILO_NV() {
        return (int)34553L;
    }
    public static int GL_SIGNED_HILO16_NV() {
        return (int)34554L;
    }
    public static int GL_SIGNED_RGBA_NV() {
        return (int)34555L;
    }
    public static int GL_SIGNED_RGBA8_NV() {
        return (int)34556L;
    }
    public static int GL_SIGNED_RGB_NV() {
        return (int)34558L;
    }
    public static int GL_SIGNED_RGB8_NV() {
        return (int)34559L;
    }
    public static int GL_SIGNED_LUMINANCE_NV() {
        return (int)34561L;
    }
    public static int GL_SIGNED_LUMINANCE8_NV() {
        return (int)34562L;
    }
    public static int GL_SIGNED_LUMINANCE_ALPHA_NV() {
        return (int)34563L;
    }
    public static int GL_SIGNED_LUMINANCE8_ALPHA8_NV() {
        return (int)34564L;
    }
    public static int GL_SIGNED_ALPHA_NV() {
        return (int)34565L;
    }
    public static int GL_SIGNED_ALPHA8_NV() {
        return (int)34566L;
    }
    public static int GL_SIGNED_INTENSITY_NV() {
        return (int)34567L;
    }
    public static int GL_SIGNED_INTENSITY8_NV() {
        return (int)34568L;
    }
    public static int GL_DSDT8_NV() {
        return (int)34569L;
    }
    public static int GL_DSDT8_MAG8_NV() {
        return (int)34570L;
    }
    public static int GL_DSDT8_MAG8_INTENSITY8_NV() {
        return (int)34571L;
    }
    public static int GL_SIGNED_RGB_UNSIGNED_ALPHA_NV() {
        return (int)34572L;
    }
    public static int GL_SIGNED_RGB8_UNSIGNED_ALPHA8_NV() {
        return (int)34573L;
    }
    public static int GL_HI_SCALE_NV() {
        return (int)34574L;
    }
    public static int GL_LO_SCALE_NV() {
        return (int)34575L;
    }
    public static int GL_DS_SCALE_NV() {
        return (int)34576L;
    }
    public static int GL_DT_SCALE_NV() {
        return (int)34577L;
    }
    public static int GL_MAGNITUDE_SCALE_NV() {
        return (int)34578L;
    }
    public static int GL_VIBRANCE_SCALE_NV() {
        return (int)34579L;
    }
    public static int GL_HI_BIAS_NV() {
        return (int)34580L;
    }
    public static int GL_LO_BIAS_NV() {
        return (int)34581L;
    }
    public static int GL_DS_BIAS_NV() {
        return (int)34582L;
    }
    public static int GL_DT_BIAS_NV() {
        return (int)34583L;
    }
    public static int GL_MAGNITUDE_BIAS_NV() {
        return (int)34584L;
    }
    public static int GL_VIBRANCE_BIAS_NV() {
        return (int)34585L;
    }
    public static int GL_TEXTURE_BORDER_VALUES_NV() {
        return (int)34586L;
    }
    public static int GL_TEXTURE_HI_SIZE_NV() {
        return (int)34587L;
    }
    public static int GL_TEXTURE_LO_SIZE_NV() {
        return (int)34588L;
    }
    public static int GL_TEXTURE_DS_SIZE_NV() {
        return (int)34589L;
    }
    public static int GL_TEXTURE_DT_SIZE_NV() {
        return (int)34590L;
    }
    public static int GL_TEXTURE_MAG_SIZE_NV() {
        return (int)34591L;
    }
    public static int GL_NV_texture_shader2() {
        return (int)1L;
    }
    public static int GL_DOT_PRODUCT_TEXTURE_3D_NV() {
        return (int)34543L;
    }
    public static int GL_NV_texture_shader3() {
        return (int)1L;
    }
    public static int GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV() {
        return (int)34896L;
    }
    public static int GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV() {
        return (int)34897L;
    }
    public static int GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV() {
        return (int)34898L;
    }
    public static int GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV() {
        return (int)34899L;
    }
    public static int GL_OFFSET_HILO_TEXTURE_2D_NV() {
        return (int)34900L;
    }
    public static int GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV() {
        return (int)34901L;
    }
    public static int GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV() {
        return (int)34902L;
    }
    public static int GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV() {
        return (int)34903L;
    }
    public static int GL_DEPENDENT_HILO_TEXTURE_2D_NV() {
        return (int)34904L;
    }
    public static int GL_DEPENDENT_RGB_TEXTURE_3D_NV() {
        return (int)34905L;
    }
    public static int GL_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV() {
        return (int)34906L;
    }
    public static int GL_DOT_PRODUCT_PASS_THROUGH_NV() {
        return (int)34907L;
    }
    public static int GL_DOT_PRODUCT_TEXTURE_1D_NV() {
        return (int)34908L;
    }
    public static int GL_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV() {
        return (int)34909L;
    }
    public static int GL_HILO8_NV() {
        return (int)34910L;
    }
    public static int GL_SIGNED_HILO8_NV() {
        return (int)34911L;
    }
    public static int GL_FORCE_BLUE_TO_ONE_NV() {
        return (int)34912L;
    }
    public static int GL_NV_transform_feedback() {
        return (int)1L;
    }
    public static int GL_BACK_PRIMARY_COLOR_NV() {
        return (int)35959L;
    }
    public static int GL_BACK_SECONDARY_COLOR_NV() {
        return (int)35960L;
    }
    public static int GL_TEXTURE_COORD_NV() {
        return (int)35961L;
    }
    public static int GL_CLIP_DISTANCE_NV() {
        return (int)35962L;
    }
    public static int GL_VERTEX_ID_NV() {
        return (int)35963L;
    }
    public static int GL_PRIMITIVE_ID_NV() {
        return (int)35964L;
    }
    public static int GL_GENERIC_ATTRIB_NV() {
        return (int)35965L;
    }
    public static int GL_TRANSFORM_FEEDBACK_ATTRIBS_NV() {
        return (int)35966L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_MODE_NV() {
        return (int)35967L;
    }
    public static int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS_NV() {
        return (int)35968L;
    }
    public static int GL_ACTIVE_VARYINGS_NV() {
        return (int)35969L;
    }
    public static int GL_ACTIVE_VARYING_MAX_LENGTH_NV() {
        return (int)35970L;
    }
    public static int GL_TRANSFORM_FEEDBACK_VARYINGS_NV() {
        return (int)35971L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_START_NV() {
        return (int)35972L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_SIZE_NV() {
        return (int)35973L;
    }
    public static int GL_TRANSFORM_FEEDBACK_RECORD_NV() {
        return (int)35974L;
    }
    public static int GL_PRIMITIVES_GENERATED_NV() {
        return (int)35975L;
    }
    public static int GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN_NV() {
        return (int)35976L;
    }
    public static int GL_RASTERIZER_DISCARD_NV() {
        return (int)35977L;
    }
    public static int GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS_NV() {
        return (int)35978L;
    }
    public static int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS_NV() {
        return (int)35979L;
    }
    public static int GL_INTERLEAVED_ATTRIBS_NV() {
        return (int)35980L;
    }
    public static int GL_SEPARATE_ATTRIBS_NV() {
        return (int)35981L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_NV() {
        return (int)35982L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_BINDING_NV() {
        return (int)35983L;
    }
    public static int GL_LAYER_NV() {
        return (int)36266L;
    }
    public static int GL_NV_transform_feedback2() {
        return (int)1L;
    }
    public static int GL_TRANSFORM_FEEDBACK_NV() {
        return (int)36386L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED_NV() {
        return (int)36387L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE_NV() {
        return (int)36388L;
    }
    public static int GL_TRANSFORM_FEEDBACK_BINDING_NV() {
        return (int)36389L;
    }
    public static int GL_NV_uniform_buffer_unified_memory() {
        return (int)1L;
    }
    public static int GL_UNIFORM_BUFFER_UNIFIED_NV() {
        return (int)37742L;
    }
    public static int GL_UNIFORM_BUFFER_ADDRESS_NV() {
        return (int)37743L;
    }
    public static int GL_UNIFORM_BUFFER_LENGTH_NV() {
        return (int)37744L;
    }
    public static int GL_NV_vdpau_interop() {
        return (int)1L;
    }
    public static int GL_SURFACE_STATE_NV() {
        return (int)34539L;
    }
    public static int GL_SURFACE_REGISTERED_NV() {
        return (int)34557L;
    }
    public static int GL_SURFACE_MAPPED_NV() {
        return (int)34560L;
    }
    public static int GL_WRITE_DISCARD_NV() {
        return (int)35006L;
    }
    public static int GL_NV_vertex_array_range() {
        return (int)1L;
    }
    public static int GL_VERTEX_ARRAY_RANGE_NV() {
        return (int)34077L;
    }
    public static int GL_VERTEX_ARRAY_RANGE_LENGTH_NV() {
        return (int)34078L;
    }
    public static int GL_VERTEX_ARRAY_RANGE_VALID_NV() {
        return (int)34079L;
    }
    public static int GL_MAX_VERTEX_ARRAY_RANGE_ELEMENT_NV() {
        return (int)34080L;
    }
    public static int GL_VERTEX_ARRAY_RANGE_POINTER_NV() {
        return (int)34081L;
    }
    public static int GL_NV_vertex_array_range2() {
        return (int)1L;
    }
    public static int GL_VERTEX_ARRAY_RANGE_WITHOUT_FLUSH_NV() {
        return (int)34099L;
    }
    public static int GL_NV_vertex_attrib_integer_64bit() {
        return (int)1L;
    }
    public static int GL_NV_vertex_buffer_unified_memory() {
        return (int)1L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_UNIFIED_NV() {
        return (int)36638L;
    }
    public static int GL_ELEMENT_ARRAY_UNIFIED_NV() {
        return (int)36639L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_ADDRESS_NV() {
        return (int)36640L;
    }
    public static int GL_VERTEX_ARRAY_ADDRESS_NV() {
        return (int)36641L;
    }
    public static int GL_NORMAL_ARRAY_ADDRESS_NV() {
        return (int)36642L;
    }
    public static int GL_COLOR_ARRAY_ADDRESS_NV() {
        return (int)36643L;
    }
    public static int GL_INDEX_ARRAY_ADDRESS_NV() {
        return (int)36644L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_ADDRESS_NV() {
        return (int)36645L;
    }
    public static int GL_EDGE_FLAG_ARRAY_ADDRESS_NV() {
        return (int)36646L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_ADDRESS_NV() {
        return (int)36647L;
    }
    public static int GL_FOG_COORD_ARRAY_ADDRESS_NV() {
        return (int)36648L;
    }
    public static int GL_ELEMENT_ARRAY_ADDRESS_NV() {
        return (int)36649L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_LENGTH_NV() {
        return (int)36650L;
    }
    public static int GL_VERTEX_ARRAY_LENGTH_NV() {
        return (int)36651L;
    }
    public static int GL_NORMAL_ARRAY_LENGTH_NV() {
        return (int)36652L;
    }
    public static int GL_COLOR_ARRAY_LENGTH_NV() {
        return (int)36653L;
    }
    public static int GL_INDEX_ARRAY_LENGTH_NV() {
        return (int)36654L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_LENGTH_NV() {
        return (int)36655L;
    }
    public static int GL_EDGE_FLAG_ARRAY_LENGTH_NV() {
        return (int)36656L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_LENGTH_NV() {
        return (int)36657L;
    }
    public static int GL_FOG_COORD_ARRAY_LENGTH_NV() {
        return (int)36658L;
    }
    public static int GL_ELEMENT_ARRAY_LENGTH_NV() {
        return (int)36659L;
    }
    public static int GL_DRAW_INDIRECT_UNIFIED_NV() {
        return (int)36672L;
    }
    public static int GL_DRAW_INDIRECT_ADDRESS_NV() {
        return (int)36673L;
    }
    public static int GL_DRAW_INDIRECT_LENGTH_NV() {
        return (int)36674L;
    }
    public static int GL_NV_vertex_program() {
        return (int)1L;
    }
    public static int GL_VERTEX_PROGRAM_NV() {
        return (int)34336L;
    }
    public static int GL_VERTEX_STATE_PROGRAM_NV() {
        return (int)34337L;
    }
    public static int GL_ATTRIB_ARRAY_SIZE_NV() {
        return (int)34339L;
    }
    public static int GL_ATTRIB_ARRAY_STRIDE_NV() {
        return (int)34340L;
    }
    public static int GL_ATTRIB_ARRAY_TYPE_NV() {
        return (int)34341L;
    }
    public static int GL_CURRENT_ATTRIB_NV() {
        return (int)34342L;
    }
    public static int GL_PROGRAM_LENGTH_NV() {
        return (int)34343L;
    }
    public static int GL_PROGRAM_STRING_NV() {
        return (int)34344L;
    }
    public static int GL_MODELVIEW_PROJECTION_NV() {
        return (int)34345L;
    }
    public static int GL_IDENTITY_NV() {
        return (int)34346L;
    }
    public static int GL_INVERSE_NV() {
        return (int)34347L;
    }
    public static int GL_TRANSPOSE_NV() {
        return (int)34348L;
    }
    public static int GL_INVERSE_TRANSPOSE_NV() {
        return (int)34349L;
    }
    public static int GL_MAX_TRACK_MATRIX_STACK_DEPTH_NV() {
        return (int)34350L;
    }
    public static int GL_MAX_TRACK_MATRICES_NV() {
        return (int)34351L;
    }
    public static int GL_MATRIX0_NV() {
        return (int)34352L;
    }
    public static int GL_MATRIX1_NV() {
        return (int)34353L;
    }
    public static int GL_MATRIX2_NV() {
        return (int)34354L;
    }
    public static int GL_MATRIX3_NV() {
        return (int)34355L;
    }
    public static int GL_MATRIX4_NV() {
        return (int)34356L;
    }
    public static int GL_MATRIX5_NV() {
        return (int)34357L;
    }
    public static int GL_MATRIX6_NV() {
        return (int)34358L;
    }
    public static int GL_MATRIX7_NV() {
        return (int)34359L;
    }
    public static int GL_CURRENT_MATRIX_STACK_DEPTH_NV() {
        return (int)34368L;
    }
    public static int GL_CURRENT_MATRIX_NV() {
        return (int)34369L;
    }
    public static int GL_VERTEX_PROGRAM_POINT_SIZE_NV() {
        return (int)34370L;
    }
    public static int GL_VERTEX_PROGRAM_TWO_SIDE_NV() {
        return (int)34371L;
    }
    public static int GL_PROGRAM_PARAMETER_NV() {
        return (int)34372L;
    }
    public static int GL_ATTRIB_ARRAY_POINTER_NV() {
        return (int)34373L;
    }
    public static int GL_PROGRAM_TARGET_NV() {
        return (int)34374L;
    }
    public static int GL_PROGRAM_RESIDENT_NV() {
        return (int)34375L;
    }
    public static int GL_TRACK_MATRIX_NV() {
        return (int)34376L;
    }
    public static int GL_TRACK_MATRIX_TRANSFORM_NV() {
        return (int)34377L;
    }
    public static int GL_VERTEX_PROGRAM_BINDING_NV() {
        return (int)34378L;
    }
}


