// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLGETINTERNALFORMATSAMPLEIVNVPROC {

    void apply(int x0, int x1, int x2, int x3, int x4, jdk.incubator.foreign.MemoryAddress x5);
    static MemoryAddress allocate(PFNGLGETINTERNALFORMATSAMPLEIVNVPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLGETINTERNALFORMATSAMPLEIVNVPROC.class, fi, constants$776.PFNGLGETINTERNALFORMATSAMPLEIVNVPROC$FUNC, "(IIIIILjdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(PFNGLGETINTERNALFORMATSAMPLEIVNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGETINTERNALFORMATSAMPLEIVNVPROC.class, fi, constants$776.PFNGLGETINTERNALFORMATSAMPLEIVNVPROC$FUNC, "(IIIIILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static PFNGLGETINTERNALFORMATSAMPLEIVNVPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, int x2, int x3, int x4, jdk.incubator.foreign.MemoryAddress x5) -> {
            try {
                constants$776.PFNGLGETINTERNALFORMATSAMPLEIVNVPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


