// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLPROGRAMUNIFORM2DEXTPROC {

    void apply(int x0, int x1, double x2, double x3);
    static MemoryAddress allocate(PFNGLPROGRAMUNIFORM2DEXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMUNIFORM2DEXTPROC.class, fi, constants$611.PFNGLPROGRAMUNIFORM2DEXTPROC$FUNC, "(IIDD)V");
    }
    static MemoryAddress allocate(PFNGLPROGRAMUNIFORM2DEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMUNIFORM2DEXTPROC.class, fi, constants$611.PFNGLPROGRAMUNIFORM2DEXTPROC$FUNC, "(IIDD)V", scope);
    }
    static PFNGLPROGRAMUNIFORM2DEXTPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, double x2, double x3) -> {
            try {
                constants$611.PFNGLPROGRAMUNIFORM2DEXTPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


