// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLUNIFORM3IPROC {

    void apply(int x0, int x1, int x2, int x3);
    static MemoryAddress allocate(PFNGLUNIFORM3IPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLUNIFORM3IPROC.class, fi, constants$127.PFNGLUNIFORM3IPROC$FUNC, "(IIII)V");
    }
    static MemoryAddress allocate(PFNGLUNIFORM3IPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLUNIFORM3IPROC.class, fi, constants$127.PFNGLUNIFORM3IPROC$FUNC, "(IIII)V", scope);
    }
    static PFNGLUNIFORM3IPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, int x2, int x3) -> {
            try {
                constants$127.PFNGLUNIFORM3IPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


