// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLSAMPLEMASKIPROC {

    void apply(int x0, int x1);
    static MemoryAddress allocate(PFNGLSAMPLEMASKIPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLSAMPLEMASKIPROC.class, fi, constants$185.PFNGLSAMPLEMASKIPROC$FUNC, "(II)V");
    }
    static MemoryAddress allocate(PFNGLSAMPLEMASKIPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLSAMPLEMASKIPROC.class, fi, constants$185.PFNGLSAMPLEMASKIPROC$FUNC, "(II)V", scope);
    }
    static PFNGLSAMPLEMASKIPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1) -> {
            try {
                constants$185.PFNGLSAMPLEMASKIPROC$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


