// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC {

    void apply(int x0);
    static MemoryAddress allocate(PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC.class, fi, constants$814.PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC$FUNC, "(I)V");
    }
    static MemoryAddress allocate(PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC.class, fi, constants$814.PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC$FUNC, "(I)V", scope);
    }
    static PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$814.PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


