// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC {

    void apply(int x0, int x1, int x2, int x3, int x4, jdk.incubator.foreign.MemoryAddress x5);
    static MemoryAddress allocate(PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC.class, fi, constants$456.PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC$FUNC, "(IIIIILjdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC.class, fi, constants$456.PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC$FUNC, "(IIIIILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, int x2, int x3, int x4, jdk.incubator.foreign.MemoryAddress x5) -> {
            try {
                constants$456.PFNGLGETFRAMEBUFFERPARAMETERFVAMDPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


