// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLPROGRAMUNIFORM3DPROC {

    void apply(int x0, int x1, double x2, double x3, double x4);
    static MemoryAddress allocate(PFNGLPROGRAMUNIFORM3DPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMUNIFORM3DPROC.class, fi, constants$232.PFNGLPROGRAMUNIFORM3DPROC$FUNC, "(IIDDD)V");
    }
    static MemoryAddress allocate(PFNGLPROGRAMUNIFORM3DPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMUNIFORM3DPROC.class, fi, constants$232.PFNGLPROGRAMUNIFORM3DPROC$FUNC, "(IIDDD)V", scope);
    }
    static PFNGLPROGRAMUNIFORM3DPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, double x2, double x3, double x4) -> {
            try {
                constants$232.PFNGLPROGRAMUNIFORM3DPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


