// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLBINDTEXTUREUNITPARAMETEREXTPROC {

    int apply(int x0, int x1);
    static MemoryAddress allocate(PFNGLBINDTEXTUREUNITPARAMETEREXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLBINDTEXTUREUNITPARAMETEREXTPROC.class, fi, constants$692.PFNGLBINDTEXTUREUNITPARAMETEREXTPROC$FUNC, "(II)I");
    }
    static MemoryAddress allocate(PFNGLBINDTEXTUREUNITPARAMETEREXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLBINDTEXTUREUNITPARAMETEREXTPROC.class, fi, constants$692.PFNGLBINDTEXTUREUNITPARAMETEREXTPROC$FUNC, "(II)I", scope);
    }
    static PFNGLBINDTEXTUREUNITPARAMETEREXTPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1) -> {
            try {
                return (int)constants$692.PFNGLBINDTEXTUREUNITPARAMETEREXTPROC$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


