// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLBINDBUFFERARBPROC {

    void apply(int x0, int x1);
    static MemoryAddress allocate(PFNGLBINDBUFFERARBPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLBINDBUFFERARBPROC.class, fi, constants$382.PFNGLBINDBUFFERARBPROC$FUNC, "(II)V");
    }
    static MemoryAddress allocate(PFNGLBINDBUFFERARBPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLBINDBUFFERARBPROC.class, fi, constants$382.PFNGLBINDBUFFERARBPROC$FUNC, "(II)V", scope);
    }
    static PFNGLBINDBUFFERARBPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1) -> {
            try {
                constants$382.PFNGLBINDBUFFERARBPROC$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


