// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLUNLOCKARRAYSEXTPROC {

    void apply();
    static MemoryAddress allocate(PFNGLUNLOCKARRAYSEXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLUNLOCKARRAYSEXTPROC.class, fi, constants$520.PFNGLUNLOCKARRAYSEXTPROC$FUNC, "()V");
    }
    static MemoryAddress allocate(PFNGLUNLOCKARRAYSEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLUNLOCKARRAYSEXTPROC.class, fi, constants$520.PFNGLUNLOCKARRAYSEXTPROC$FUNC, "()V", scope);
    }
    static PFNGLUNLOCKARRAYSEXTPROC ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                constants$520.PFNGLUNLOCKARRAYSEXTPROC$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


