// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLUNIFORM3I64ARBPROC {

    void apply(int x0, long x1, long x2, long x3);
    static MemoryAddress allocate(PFNGLUNIFORM3I64ARBPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLUNIFORM3I64ARBPROC.class, fi, constants$332.PFNGLUNIFORM3I64ARBPROC$FUNC, "(IJJJ)V");
    }
    static MemoryAddress allocate(PFNGLUNIFORM3I64ARBPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLUNIFORM3I64ARBPROC.class, fi, constants$332.PFNGLUNIFORM3I64ARBPROC$FUNC, "(IJJJ)V", scope);
    }
    static PFNGLUNIFORM3I64ARBPROC ofAddress(MemoryAddress addr) {
        return (int x0, long x1, long x2, long x3) -> {
            try {
                constants$332.PFNGLUNIFORM3I64ARBPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


