// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC {

    void apply(int x0, int x1, int x2, int x3, int x4, int x5, byte x6);
    static MemoryAddress allocate(PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC.class, fi, constants$618.PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC$FUNC, "(IIIIIIB)V");
    }
    static MemoryAddress allocate(PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC.class, fi, constants$618.PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC$FUNC, "(IIIIIIB)V", scope);
    }
    static PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, int x2, int x3, int x4, int x5, byte x6) -> {
            try {
                constants$618.PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5, x6);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


