// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLCREATEPROGRAMPIPELINESPROC {

    void apply(int x0, jdk.incubator.foreign.MemoryAddress x1);
    static MemoryAddress allocate(PFNGLCREATEPROGRAMPIPELINESPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLCREATEPROGRAMPIPELINESPROC.class, fi, constants$302.PFNGLCREATEPROGRAMPIPELINESPROC$FUNC, "(ILjdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(PFNGLCREATEPROGRAMPIPELINESPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLCREATEPROGRAMPIPELINESPROC.class, fi, constants$302.PFNGLCREATEPROGRAMPIPELINESPROC$FUNC, "(ILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static PFNGLCREATEPROGRAMPIPELINESPROC ofAddress(MemoryAddress addr) {
        return (int x0, jdk.incubator.foreign.MemoryAddress x1) -> {
            try {
                constants$302.PFNGLCREATEPROGRAMPIPELINESPROC$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


