// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLFRAGMENTLIGHTISGIXPROC {

    void apply(int x0, int x1, int x2);
    static MemoryAddress allocate(PFNGLFRAGMENTLIGHTISGIXPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLFRAGMENTLIGHTISGIXPROC.class, fi, constants$884.PFNGLFRAGMENTLIGHTISGIXPROC$FUNC, "(III)V");
    }
    static MemoryAddress allocate(PFNGLFRAGMENTLIGHTISGIXPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLFRAGMENTLIGHTISGIXPROC.class, fi, constants$884.PFNGLFRAGMENTLIGHTISGIXPROC$FUNC, "(III)V", scope);
    }
    static PFNGLFRAGMENTLIGHTISGIXPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, int x2) -> {
            try {
                constants$884.PFNGLFRAGMENTLIGHTISGIXPROC$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


