// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLVERTEXATTRIB2SPROC {

    void apply(int x0, short x1, short x2);
    static MemoryAddress allocate(PFNGLVERTEXATTRIB2SPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLVERTEXATTRIB2SPROC.class, fi, constants$135.PFNGLVERTEXATTRIB2SPROC$FUNC, "(ISS)V");
    }
    static MemoryAddress allocate(PFNGLVERTEXATTRIB2SPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLVERTEXATTRIB2SPROC.class, fi, constants$135.PFNGLVERTEXATTRIB2SPROC$FUNC, "(ISS)V", scope);
    }
    static PFNGLVERTEXATTRIB2SPROC ofAddress(MemoryAddress addr) {
        return (int x0, short x1, short x2) -> {
            try {
                constants$135.PFNGLVERTEXATTRIB2SPROC$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


