// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLGETSTRINGIPROC {

    jdk.incubator.foreign.MemoryAddress apply(int x0, int x1);
    static MemoryAddress allocate(PFNGLGETSTRINGIPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLGETSTRINGIPROC.class, fi, constants$165.PFNGLGETSTRINGIPROC$FUNC, "(II)Ljdk/incubator/foreign/MemoryAddress;");
    }
    static MemoryAddress allocate(PFNGLGETSTRINGIPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGETSTRINGIPROC.class, fi, constants$165.PFNGLGETSTRINGIPROC$FUNC, "(II)Ljdk/incubator/foreign/MemoryAddress;", scope);
    }
    static PFNGLGETSTRINGIPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1) -> {
            try {
                return (jdk.incubator.foreign.MemoryAddress)constants$165.PFNGLGETSTRINGIPROC$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


