// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLVERTEX2XOESPROC {

    void apply(int x0);
    static MemoryAddress allocate(PFNGLVERTEX2XOESPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLVERTEX2XOESPROC.class, fi, constants$447.PFNGLVERTEX2XOESPROC$FUNC, "(I)V");
    }
    static MemoryAddress allocate(PFNGLVERTEX2XOESPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLVERTEX2XOESPROC.class, fi, constants$447.PFNGLVERTEX2XOESPROC$FUNC, "(I)V", scope);
    }
    static PFNGLVERTEX2XOESPROC ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$447.PFNGLVERTEX2XOESPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


