name: Publish Version Check Results

on:
  workflow_run:
    workflows: [ 'Pull-Request Checks' ]
    types: [ completed ]

jobs:
  publish-version-check-results:
    uses: HannesWell/eclipse.platform.releng.aggregator/.github/workflows/publishVersionCheckResults.yml@update-snapshots-in-versions-workflow
    with:
      botGithubId: eclipse-platform-bot
    secrets:
      githubBotPAT: ${{ secrets.PLATFORM_BOT_PAT }}
